const ENTITLEMENT_IDS = Object.freeze([
  'tenant.administration',
  'tenant.audit_history',
  'microsoft.calendar',
  'microsoft.calendar.write',
]);

function entitlements(calendarWrite = false) {
  return ENTITLEMENT_IDS.map((id) => ({
    id,
    state: id === 'microsoft.calendar.write' && !calendarWrite ? 'disabled' : 'enabled',
  }));
}

function tenant({
  id,
  reference,
  displayName,
  lifecycleState,
  invitationState,
  onboardingState = 'complete',
  identityState = 'active',
  invitationId = '90000000-0000-4000-8000-000000000001',
  readinessState,
  blockers = [],
  integrationState,
  diagnosticsState = 'clear',
  failureCode = null,
  correlationId = null,
  calendarWrite = false,
  activeUsers = 0,
  rooms = 0,
  requestsThisMonth = 0,
  quotaState = 'within_limit',
  runtimeState = 'current',
  allowedActions = [],
}) {
  const channelState = integrationState === 'healthy' ? 'healthy' : integrationState;
  return {
    id,
    reference,
    displayName,
    lifecycleState,
    version: 1,
    onboardingState,
    identityState,
    invitationState,
    invitationId: invitationState === 'none' ? null : invitationId,
    invitationRevision: invitationState === 'none' ? null : 1,
    invitationExpiresAt: invitationState === 'none' ? null : '2099-01-02T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
    readiness: {
      state: readinessState,
      blockers,
      evaluatedAt: '2026-08-01T08:00:00.000Z',
    },
    entitlements: entitlements(calendarWrite),
    integration: {
      state: integrationState,
      directoryState: channelState,
      calendarReadState: channelState,
      calendarWriteState: calendarWrite ? channelState : 'not_configured',
      checkedAt: '2026-08-01T08:00:00.000Z',
    },
    diagnostics: {
      state: diagnosticsState,
      lastCorrelationId: correlationId,
      lastFailureCode: failureCode,
    },
    usage: { activeUsers, rooms, requestsThisMonth, quotaState },
    runtime: {
      state: runtimeState,
      frontendVersion: '3.0.0',
      apiVersion: '3.0.0',
      schemaVersion: runtimeState === 'migration_required' ? 2 : 3,
    },
    allowedActions,
  };
}

export function createPendingPlatformAdminDemoTenant({ id, invitationId, reference, displayName, createdAt }) {
  return {
    ...tenant({
      id,
      reference,
      displayName,
      lifecycleState: 'pending',
      invitationState: 'open',
      invitationId,
      onboardingState: 'invited',
      identityState: 'unbound',
      readinessState: 'blocked',
      blockers: ['tenant_identity_missing', 'microsoft_connection_missing'],
      integrationState: 'not_configured',
      allowedActions: ['invitation_revoke', 'invitation_reissue'],
    }),
    updatedAt: createdAt,
  };
}

export function createPlatformAdminDemoFixtures() {
  const tenants = [
    tenant({
      id: '10000000-0000-4000-8000-000000000001',
      reference: 'TEN-001',
      displayName: 'Aster Works',
      lifecycleState: 'pending',
      invitationState: 'none',
      onboardingState: 'not_started',
      identityState: 'unbound',
      readinessState: 'blocked',
      blockers: ['tenant_identity_missing', 'microsoft_connection_missing'],
      integrationState: 'not_configured',
      allowedActions: [],
    }),
    tenant({
      id: '10000000-0000-4000-8000-000000000002',
      reference: 'TEN-002',
      displayName: 'Birch Labs',
      lifecycleState: 'onboarding',
      invitationState: 'consumed',
      onboardingState: 'complete',
      invitationId: '90000000-0000-4000-8000-000000000002',
      readinessState: 'ready',
      integrationState: 'healthy',
      activeUsers: 12,
      rooms: 3,
      requestsThisMonth: 18,
      allowedActions: ['mark_ready'],
    }),
    tenant({
      id: '10000000-0000-4000-8000-000000000003',
      reference: 'TEN-003',
      displayName: 'Cedar Services',
      lifecycleState: 'ready',
      invitationState: 'consumed',
      invitationId: '90000000-0000-4000-8000-000000000003',
      readinessState: 'ready',
      integrationState: 'healthy',
      activeUsers: 38,
      rooms: 8,
      requestsThisMonth: 74,
      allowedActions: ['activate'],
    }),
    tenant({
      id: '10000000-0000-4000-8000-000000000004',
      reference: 'TEN-004',
      displayName: 'Dune Collective',
      lifecycleState: 'active',
      invitationState: 'consumed',
      invitationId: '90000000-0000-4000-8000-000000000004',
      readinessState: 'ready',
      integrationState: 'healthy',
      calendarWrite: true,
      activeUsers: 247,
      rooms: 24,
      requestsThisMonth: 896,
      quotaState: 'approaching_limit',
      allowedActions: ['suspend'],
    }),
    tenant({
      id: '10000000-0000-4000-8000-000000000005',
      reference: 'TEN-005',
      displayName: 'Elm Partners',
      lifecycleState: 'suspended',
      invitationState: 'consumed',
      invitationId: '90000000-0000-4000-8000-000000000005',
      readinessState: 'stale',
      blockers: ['verification_stale'],
      integrationState: 'degraded',
      diagnosticsState: 'incident',
      failureCode: 'projection_out_of_sync',
      correlationId: '20000000-0000-4000-8000-000000000005',
      calendarWrite: true,
      activeUsers: 94,
      rooms: 11,
      requestsThisMonth: 312,
      runtimeState: 'migration_required',
      allowedActions: ['reactivate', 'archive'],
    }),
    tenant({
      id: '10000000-0000-4000-8000-000000000006',
      reference: 'TEN-006',
      displayName: 'Fir Network',
      lifecycleState: 'archived',
      invitationState: 'revoked',
      invitationId: '90000000-0000-4000-8000-000000000006',
      readinessState: 'stale',
      blockers: ['verification_stale'],
      integrationState: 'unavailable',
      diagnosticsState: 'attention',
      failureCode: 'directory_sync_delayed',
      correlationId: '20000000-0000-4000-8000-000000000006',
      activeUsers: 0,
      rooms: 5,
      requestsThisMonth: 0,
      runtimeState: 'upgrade_scheduled',
      allowedActions: [],
    }),
  ];

  const auditEvents = tenants.map((item, index) => ({
    id: `30000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
    tenantId: item.id,
    occurredAt: `2026-08-01T08:0${index}:00.000Z`,
    action: 'tenant_registered',
    actorType: 'system',
    result: 'succeeded',
    correlationId: `31000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
  }));

  return {
    schemaVersion: 1,
    roleId: 'support_reader',
    mutationCounter: 0,
    tenants,
    auditEvents,
  };
}
