(function(){
  const REQUEST_KEY='conference_requests',CATALOG_KEY='conference_catalog_v2';
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const getCatalog=()=>{try{return JSON.parse(localStorage.getItem(CATALOG_KEY)||'null')}catch{return null}};
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  let activeModal=null,returnFocus=null,scheduled=false;
  const setText=(el,v)=>{if(el&&el.textContent!==String(v))el.textContent=String(v)};

  function styles(){if(q('#a11yCoreStyles'))return;const s=document.createElement('style');s.id='a11yCoreStyles';s.textContent=`
    .skip-link{position:fixed;left:12px;top:12px;z-index:20000;background:#000;color:#fff;padding:10px 14px;transform:translateY(-160%);text-decoration:none;border-bottom:4px solid #86bc25}.skip-link:focus{transform:translateY(0)}
    :where(button,a,input,select,textarea,[tabindex]):focus-visible{outline:3px solid #000!important;outline-offset:3px!important;box-shadow:none!important}.primary:focus-visible,.nav-item:focus-visible{outline-color:#86bc25!important}
    .field-error{display:block;color:#b42318;font-size:13px;font-weight:700;margin-top:6px}.field-error-group{border-left:4px solid #b42318;background:#fef3f2;padding:10px 12px;margin:12px 0;color:#8a1c13;font-weight:700}[aria-invalid="true"]{border-color:#b42318!important;box-shadow:0 0 0 2px rgba(180,35,24,.12)!important}
    .mobile-step-progress{display:none;background:#fff;border:1px solid #d0d0ce;margin-bottom:14px;padding:12px 14px}.mobile-step-progress strong{display:block;margin-bottom:7px}.mobile-progress-track{height:6px;background:#ededed;overflow:hidden}.mobile-progress-fill{height:100%;background:#86bc25;transition:width .2s ease}
    .ux-card-select{margin-top:12px;width:100%;min-height:42px}.ux-card-select[aria-pressed="true"]{border-color:#000;font-weight:800;box-shadow:inset 0 -4px 0 #86bc25}.qty-control button,.icon-btn{min-width:40px!important;min-height:40px!important}
    @media(max-width:640px){.stepper{display:none!important}.mobile-step-progress{display:block}.request-actions button{min-height:42px}.topbar h1{font-size:25px}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
  `;document.head.appendChild(s)}

  function base(){if(!q('.skip-link')){const a=document.createElement('a');a.className='skip-link';a.href='#mainContent';a.textContent='Direkt zum Hauptinhalt';document.body.insertBefore(a,document.body.firstChild)}const main=q('main.main');if(main){main.id='mainContent';main.tabIndex=-1}q('.sidebar nav')?.setAttribute('aria-label','Hauptnavigation');const chip=q('.user-chip');if(chip&&!chip.hasAttribute('aria-label'))chip.setAttribute('aria-label',`Angemeldeter Benutzer ${chip.textContent.trim()}`);const toast=q('#toast');if(toast){toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');toast.setAttribute('aria-atomic','true')}const p=q('#participantTotal');if(p){p.setAttribute('role','status');p.setAttribute('aria-live','polite')}const a=q('#allocationStatus');if(a){a.setAttribute('role','status');a.setAttribute('aria-live','polite')}q('#date')?.setAttribute('min',today());const title=q('#viewTitle');if(title)title.tabIndex=-1;qa('.nav-item').forEach(b=>{if(b.classList.contains('active'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');if(!b.__a11yNav){b.__a11yNav=true;b.addEventListener('click',()=>setTimeout(()=>{qa('.nav-item').forEach(n=>{if(n.classList.contains('active'))n.setAttribute('aria-current','page');else n.removeAttribute('aria-current')});q('#viewTitle')?.focus()},0))}})}

  const names={1:'Termin',2:'Raum',3:'Services',4:'Bewirtung',5:'Kosten',6:'Prüfen'};
  function wizard(){const st=q('.stepper');if(!st)return;st.setAttribute('aria-label','Schritte der Konferenzanfrage');let m=q('#mobileStepProgress');if(!m){m=document.createElement('div');m.id='mobileStepProgress';m.className='mobile-step-progress';m.setAttribute('role','status');m.setAttribute('aria-live','polite');m.innerHTML='<strong id="mobileStepText"></strong><div class="mobile-progress-track" aria-hidden="true"><div id="mobileProgressFill" class="mobile-progress-fill"></div></div>';st.parentNode.insertBefore(m,st)}const update=()=>{const active=q('.step.active',st),n=Number(active?.dataset.step||1);qa('.step',st).forEach(b=>{const on=Number(b.dataset.step)===n;if(on)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.setAttribute('aria-label',`Schritt ${b.dataset.step} von 6: ${names[b.dataset.step]||b.textContent.trim()}`)});setText(q('#mobileStepText'),`Schritt ${n} von 6 · ${names[n]}`);if(q('#mobileProgressFill'))q('#mobileProgressFill').style.width=`${n/6*100}%`};update();if(!st.__a11yObs){const o=new MutationObserver(update);o.observe(st,{subtree:true,attributes:true,attributeFilter:['class']});st.__a11yObs=true}}

  function clearError(el){if(!el)return;el.removeAttribute('aria-invalid');const id=el.getAttribute('aria-describedby');if(id&&id.startsWith('err-')){document.getElementById(id)?.remove();el.removeAttribute('aria-describedby')}}
  function error(el,msg){if(!el)return null;clearError(el);const id=`err-${el.id||Math.random().toString(36).slice(2)}`,x=document.createElement('span');x.id=id;x.className='field-error';x.textContent=msg;el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',id);(el.closest('label')||el.parentNode)?.appendChild(x);return el}
  function groupError(container,msg){if(!container)return;qa('.field-error-group',container).forEach(x=>x.remove());const x=document.createElement('div');x.className='field-error-group';x.setAttribute('role','alert');x.textContent=msg;container.insertBefore(x,container.firstChild)}
  function announce(msg){const t=q('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__a11yToast);window.__a11yToast=setTimeout(()=>t.classList.remove('show'),3400)}
  function validate(step){qa('[aria-invalid="true"]').forEach(clearError);qa('.field-error-group').forEach(x=>x.remove());let first=null;if(step===1){const ti=q('#title'),d=q('#date'),s=q('#start'),e=q('#end'),i=q('#internalParticipants'),ex=q('#externalParticipants');if(!ti?.value.trim())first||=error(ti,'Bitte einen Titel für die Veranstaltung angeben.');if(!d?.value)first||=error(d,'Bitte ein Datum auswählen.');else if(d.value<today())first||=error(d,'Das Veranstaltungsdatum darf nicht in der Vergangenheit liegen.');if(!s?.value)first||=error(s,'Bitte eine Startzeit angeben.');if(!e?.value)first||=error(e,'Bitte eine Endzeit angeben.');if(s?.value&&e?.value&&e.value<=s.value)first||=error(e,'Die Endzeit muss nach der Startzeit liegen.');const total=Number(i?.value||0)+Number(ex?.value||0);if(total<1)first||=error(i,'Bitte mindestens eine teilnehmende Person angeben.');if(Number(i?.value||0)<0)first||=error(i,'Die Teilnehmerzahl darf nicht negativ sein.');if(Number(ex?.value||0)<0)first||=error(ex,'Die Teilnehmerzahl darf nicht negativ sein.')}if(step===2&&!q('#rooms [data-room].selected')){groupError(q('#rooms'),'Bitte einen verfügbaren Raum auswählen.');first||=q('#rooms .ux-room-select:not(:disabled)')}if(step===5){let sum=0;qa('#allocations .allocation-row').forEach((row,n)=>{const cc=q('[data-cc]',row),pct=q('[data-pct]',row);if(!cc?.value.trim())first||=error(cc,`Bitte die Kostenstelle ${n+1} angeben.`);sum+=Number(pct?.value||0)});if(Math.abs(sum-100)>.01){groupError(q('#allocations'),`Die Kostenanteile müssen zusammen 100 % ergeben. Aktuell: ${sum.toFixed(0)} %.`);first||=q('#allocations [data-pct]')}}if(first){announce('Bitte die markierten Angaben prüfen.');setTimeout(()=>first.focus?.(),0);return false}return true}
  function validation(){document.addEventListener('click',e=>{const next=e.target.closest('#nextBtn'),submit=e.target.closest('#submitBtn'),step=e.target.closest('.step[data-step]');if(!next&&!submit&&!step)return;const active=Number(q('.step.active')?.dataset.step||1);if(submit){for(const n of [1,2,5])if(!validate(n)){e.preventDefault();e.stopImmediatePropagation();return}return}if((next||(step&&Number(step.dataset.step)>active))&&!validate(active)){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('input',e=>{if(e.target.matches('input,select,textarea'))clearError(e.target)});document.addEventListener('change',e=>{if(e.target.matches('input,select,textarea'))clearError(e.target)})}

  function openFloorplan(id){const c=getCatalog(),r=c?.rooms?.find(x=>x.id===id),o=q('#floorplanModalOverlay');if(!r||!o)return;setText(q('#floorplanModalTitle'),r.name||'Floorplan');setText(q('#floorplanModalSubtitle'),`${r.floor||'Etage unbekannt'} · Kapazität ${r.capacity||'?'} Personen`);if(q('#floorplanModalImage')&&r.floorplanImage)q('#floorplanModalImage').src=r.floorplanImage;setText(q('#floorplanModalDescription'),r.floorplanDescription||'Keine Beschreibung vorhanden.');setText(q('#floorplanModalMeta'),`${r.location||''}${r.equipment?' · '+r.equipment:''}`);o.classList.add('open')}
  function selections(){const rooms=q('#rooms');if(rooms){rooms.setAttribute('role','group');rooms.setAttribute('aria-label','Verfügbare Räume');qa('[data-room]',rooms).forEach(card=>{const busy=/Belegt/i.test(q('.badge',card)?.textContent||''),selected=card.classList.contains('selected');card.setAttribute('role','group');card.setAttribute('aria-label',`${q('h3',card)?.textContent||'Raum'} · ${busy?'belegt':selected?'ausgewählt':'verfügbar'}`);let b=q('.ux-room-select',card);if(!b){b=document.createElement('button');b.type='button';b.className='secondary ux-card-select ux-room-select';card.insertBefore(b,q('.employee-floorplan',card)||null)}b.disabled=busy;b.setAttribute('aria-pressed',selected?'true':'false');setText(b,busy?'Nicht verfügbar':selected?'Ausgewählt':'Raum auswählen');qa('[data-open-floorplan]',card).forEach(fp=>{if(!fp.__a11yFloor){fp.__a11yFloor=true;fp.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();openFloorplan(fp.dataset.openFloorplan)})}})})}const services=q('#services');if(services){services.setAttribute('role','group');services.setAttribute('aria-label','Services auswählen');qa('[data-service]',services).forEach(card=>{const selected=card.classList.contains('selected');let b=q('.ux-service-select',card);if(!b){b=document.createElement('button');b.type='button';b.className='secondary ux-card-select ux-service-select';card.appendChild(b)}b.setAttribute('aria-pressed',selected?'true':'false');b.setAttribute('aria-label',`${q('h3',card)?.textContent||'Service'} ${selected?'entfernen':'hinzufügen'}`);setText(b,selected?'Ausgewählt – entfernen':'Service hinzufügen')})}const packages=q('#packages');if(packages){packages.setAttribute('role','group');packages.setAttribute('aria-label','Catering-Paket und Qualitätsstufe auswählen');qa('[data-package-id]',packages).forEach(card=>{const selected=card.classList.contains('selected'),img=q('img',card);if(img)img.alt=`Illustration: ${q('h4',card)?.textContent||'Catering-Option'}`;let b=q('.ux-package-select',card);if(!b){b=document.createElement('button');b.type='button';b.className='secondary ux-card-select ux-package-select';q('.package-variant-body',card)?.appendChild(b)}b.setAttribute('aria-pressed',selected?'true':'false');b.setAttribute('aria-label',`${q('h4',card)?.textContent||'Catering-Option'} ${selected?'abwählen':'auswählen'}`);setText(b,selected?'Ausgewählt – abwählen':'Option auswählen')})}}
  function controls(){qa('#cateringItems .item-row').forEach(row=>{const name=q('strong',row)?.textContent.trim()||'Einzeloption';q('[data-dec]',row)?.setAttribute('aria-label',`${name} reduzieren`);q('[data-inc]',row)?.setAttribute('aria-label',`${name} hinzufügen`);const qty=q('.qty-control strong',row);if(qty){qty.setAttribute('aria-live','polite');qty.setAttribute('aria-label',`Anzahl ${name}`)}});qa('#allocations .allocation-row').forEach((row,n)=>{q('[data-cc]',row)?.setAttribute('aria-label',`Kostenstelle ${n+1}`);q('[data-pct]',row)?.setAttribute('aria-label',`Anteil Kostenstelle ${n+1} in Prozent`);q('.amount',row)?.setAttribute('aria-label',`Betrag Kostenstelle ${n+1}`);q('[data-remove]',row)?.setAttribute('aria-label',`Kostenstelle ${n+1} entfernen`)})}

  function modals(){[['#requestDetailOverlay','#requestDetailTitle'],['#floorplanModalOverlay','#floorplanModalTitle'],['#guestInfoOverlay','#guestInfoTitle']].forEach(([sel,title])=>{const o=q(sel);if(!o||o.__a11y)return;o.__a11y=true;const d=q('[role="dialog"]',o)||o.firstElementChild;if(d){d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');if(q(title))d.setAttribute('aria-labelledby',title.slice(1));d.tabIndex=-1}const obs=new MutationObserver(()=>{if(o.classList.contains('open')){activeModal=o;q('.app-shell')?.setAttribute('inert','');setTimeout(()=>{const f=q('button:not(:disabled),[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])',d);(f||d)?.focus()},0)}else if(activeModal===o){activeModal=null;q('.app-shell')?.removeAttribute('inert');const back=returnFocus;returnFocus=null;setTimeout(()=>back?.focus?.(),0)}});obs.observe(o,{attributes:true,attributeFilter:['class']})})}
  function focusTrap(){document.addEventListener('click',e=>{const t=e.target.closest('[data-request-detail],[data-open-floorplan],[data-guest-info]');if(t)returnFocus=t},true);document.addEventListener('keydown',e=>{if(!activeModal||!activeModal.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();q('#closeRequestDetail,#closeFloorplanModal,#closeGuestInfo',activeModal)?.click();return}if(e.key!=='Tab')return;const fs=qa('button:not(:disabled),[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])',activeModal).filter(x=>x.offsetParent!==null);if(!fs.length){e.preventDefault();return}const first=fs[0],last=fs[fs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}

  function performance(){try{if(typeof updateCosts==='function'&&!window.__a11yCostPatch){window.__a11yCostPatch=true;updateCosts=function(){const c=costs(),nf=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});[['roomCost',c.roomCost],['serviceCost',c.serviceCost],['cateringCost',c.cateringCost],['totalCost',c.total]].forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=nf.format(v)});renderAllocations()};['internalParticipants','externalParticipants'].forEach(id=>{const el=document.getElementById(id);if(el&&!el.__packageRefresh){el.__packageRefresh=true;el.addEventListener('change',()=>{try{renderPackages()}catch(_){}})}})}}catch(e){console.warn('Performance patch skipped',e)}}

  function enhance(){base();wizard();selections();controls();modals()}
  function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})}
  function init(){styles();base();wizard();validation();focusTrap();performance();enhance();if(!document.body.__a11yObserver){const o=new MutationObserver(schedule);o.observe(document.body,{childList:true,subtree:true});document.body.__a11yObserver=true}document.documentElement.dataset.a11yBuild='2026.08.22.14'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();