const euro = new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});
const qs=id=>document.getElementById(id);
const on=(id,event,handler)=>{const el=qs(id);if(el)el.addEventListener(event,handler)};
const BUILD_VERSION='2026.08.22.3';
const CATALOG_KEY='conference_catalog_v2';
const REQUEST_KEY='conference_requests';

const defaultCatalog={
  rooms:[
    {id:'BER-321',location:'Berlin',name:'Berlin · Raum 3.21',capacity:12,equipment:'Teams Room · Display · Whiteboard',rate:80,active:true},
    {id:'BER-412',location:'Berlin',name:'Berlin · Conference Room 4.12',capacity:20,equipment:'Teams Room · Dual Display · Whiteboard',rate:120,active:true},
    {id:'BER-AUD',location:'Berlin',name:'Berlin · Auditorium',capacity:80,equipment:'Stage · PA · Hybrid Setup',rate:320,active:true},
    {id:'STR-201',location:'Stuttgart',name:'Stuttgart · Raum 2.01',capacity:10,equipment:'Teams Room · Display',rate:70,active:true},
    {id:'STR-ATR',location:'Stuttgart',name:'Stuttgart · Atrium',capacity:50,equipment:'PA · Mobile Display · Stage',rate:250,active:true},
    {id:'FRA-105',location:'Frankfurt',name:'Frankfurt · Raum 1.05',capacity:18,equipment:'Teams Room · Display · Whiteboard',rate:100,active:true}
  ],
  services:[
    {id:'host',name:'Empfang / Host',desc:'Gästebegrüßung und Veranstaltungsbetreuung',price:90,active:true},
    {id:'av',name:'Veranstaltungstechnik',desc:'Technische Betreuung für hybride Meetings',price:160,active:true},
    {id:'it',name:'IT-Support',desc:'On-site Support für Meeting- und Präsentationstechnik',price:140,active:true},
    {id:'service',name:'Servicepersonal',desc:'Betreuung von Catering und Raum während der Veranstaltung',price:120,active:true}
  ],
  cateringPackages:[
    {id:'meeting',name:'Meeting',description:'Getränke und kleine Begleitung für Meetings.',variants:[
      {tier:'Basic',desc:'Kaffee · Tee · Wasser',pricePerPerson:8.5,image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80'},
      {tier:'Standard',desc:'Kaffee · Tee · Wasser · Softdrinks · Gebäck',pricePerPerson:12.5,image:'https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=80'},
      {tier:'Deluxe',desc:'Barista-Kaffee · Premiumgetränke · Gebäck · Obst',pricePerPerson:18.5,image:'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=900&q=80'}
    ]},
    {id:'breakfast',name:'Breakfast',description:'Frühstücksangebot für interne und externe Gäste.',variants:[
      {tier:'Basic',desc:'Kaffee · Tee · Wasser · Croissant',pricePerPerson:14.5,image:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80'},
      {tier:'Standard',desc:'Getränke · Backwaren · Obst · Joghurt',pricePerPerson:19.5,image:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80'},
      {tier:'Deluxe',desc:'Premium-Frühstück · warme Komponenten · Obst · Smoothies',pricePerPerson:27.5,image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80'}
    ]},
    {id:'lunch',name:'Lunch',description:'Mittagsverpflegung für Workshops und Veranstaltungen.',variants:[
      {tier:'Basic',desc:'Sandwiches · Salat · Wasser',pricePerPerson:24,image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80'},
      {tier:'Standard',desc:'Warme Hauptspeise · Salat · Dessert · Getränke',pricePerPerson:31,image:'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80'},
      {tier:'Deluxe',desc:'Premium-Menü · Dessertauswahl · Premiumgetränke',pricePerPerson:42,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'}
    ]},
    {id:'full',name:'Full Day',description:'Ganztägige Bewirtung mit mehreren Verpflegungsphasen.',variants:[
      {tier:'Basic',desc:'Meeting Basic · Lunch Basic · Nachmittagssnack',pricePerPerson:39,image:'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=900&q=80'},
      {tier:'Standard',desc:'Breakfast Standard · Lunch Standard · Snack · Getränke',pricePerPerson:52,image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80'},
      {tier:'Deluxe',desc:'Premium-Verpflegung über den gesamten Veranstaltungstag',pricePerPerson:69,image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80'}
    ]}
  ],
  cateringItems:[
    {id:'water',name:'Mineralwasser',unit:'Flasche',price:2.5,active:true},
    {id:'coffee',name:'Kaffee',unit:'Person',price:3,active:true},
    {id:'fruit',name:'Obstplatte',unit:'für 10 Personen',price:18,active:true},
    {id:'pretzel',name:'Brezel',unit:'Stück',price:2.2,active:true},
    {id:'sandwich',name:'Sandwich',unit:'Stück',price:6.5,active:true},
    {id:'cake',name:'Kuchen',unit:'Stück',price:4,active:true}
  ]
};

let catalog=loadCatalog();
const state={step:1,roomId:null,serviceIds:[],packageSelection:null,quantities:{},allocations:[{costCenter:'471100',percent:100}],managerTab:'requests',catalogTab:'rooms'};

function clone(v){return JSON.parse(JSON.stringify(v))}
function loadCatalog(){try{const raw=localStorage.getItem(CATALOG_KEY);return raw?JSON.parse(raw):clone(defaultCatalog)}catch{return clone(defaultCatalog)}}
function saveCatalog(){localStorage.setItem(CATALOG_KEY,JSON.stringify(catalog))}
function getRequests(){try{return JSON.parse(localStorage.getItem(REQUEST_KEY)||'[]')}catch{return[]}}
function saveRequests(v){localStorage.setItem(REQUEST_KEY,JSON.stringify(v))}
function totalParticipants(){return Number(qs('internalParticipants')?.value||0)+Number(qs('externalParticipants')?.value||0)}
function activeRooms(){return catalog.rooms.filter(r=>r.active!==false)}
function activeServices(){return catalog.services.filter(s=>s.active!==false)}
function activeItems(){return catalog.cateringItems.filter(i=>i.active!==false)}
function selectedPackage(){if(!state.packageSelection)return null;const p=catalog.cateringPackages.find(x=>x.id===state.packageSelection.packageId);const v=p?.variants.find(x=>x.tier===state.packageSelection.tier);return p&&v?{package:p,variant:v}:null}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(msg){const el=qs('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}):''}
function overlaps(a,b,c,d){return a<d&&c<b}
function mockCalendarBusy(roomId){return getRequests().some(r=>r.roomId===roomId&&r.date===qs('date').value&&!['Rejected','Cancelled'].includes(r.status)&&overlaps(qs('start').value,qs('end').value,r.start,r.end))}

function init(){
  state.quantities=Object.fromEntries(catalog.cateringItems.map(i=>[i.id,0]));
  const date=qs('date');if(date)date.value=new Date(Date.now()+86400000).toISOString().slice(0,10);
  renderLocations();updateParticipantTotal();renderServices();renderPackages();renderItems();renderAllocations();renderRooms();bind();updateStep();renderRequests();renderManager();
}
function bind(){
  document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
  document.querySelectorAll('.step').forEach(b=>b.addEventListener('click',()=>{const t=Number(b.dataset.step);if(t<=state.step||validateStep(state.step)){state.step=t;updateStep()}}));
  on('nextBtn','click',()=>{if(validateStep(state.step)&&state.step<6){state.step++;updateStep()}});on('backBtn','click',()=>{if(state.step>1){state.step--;updateStep()}});on('refreshRooms','click',renderRooms);on('addAllocation','click',()=>{state.allocations.push({costCenter:'',percent:0});renderAllocations()});on('submitBtn','click',submitRequest);on('resetCatalog','click',resetCatalog);
  ['internalParticipants','externalParticipants','location','date','start','end','title'].forEach(id=>on(id,'change',()=>{if(['internalParticipants','externalParticipants'].includes(id))updateParticipantTotal();if(['location','internalParticipants','externalParticipants','date','start','end'].includes(id)){if(state.roomId&&!isSelectedRoomStillCandidate())state.roomId=null;renderRooms()}updateCosts()}));
  document.addEventListener('click',e=>{
    const cancel=e.target.closest('[data-cancel-request]');if(cancel)return cancelRequest(cancel.dataset.cancelRequest);
    const action=e.target.closest('[data-manager-action]');if(action)return managerAction(action.dataset.requestId,action.dataset.managerAction);
    const mt=e.target.closest('[data-manager-tab]');if(mt)return setManagerTab(mt.dataset.managerTab);
    const ct=e.target.closest('[data-catalog-tab]');if(ct)return setCatalogTab(ct.dataset.catalogTab);
    const rv=e.target.closest('[data-room-save]');if(rv)return saveRoom(rv.dataset.roomSave);
    const ra=e.target.closest('[data-room-add]');if(ra)return addRoom();
    const rr=e.target.closest('[data-room-remove]');if(rr)return removeRoom(rr.dataset.roomRemove);
    const sv=e.target.closest('[data-service-save]');if(sv)return saveService(sv.dataset.serviceSave);
    const sa=e.target.closest('[data-service-add]');if(sa)return addService();
    const sr=e.target.closest('[data-service-remove]');if(sr)return removeService(sr.dataset.serviceRemove);
    const pv=e.target.closest('[data-package-save]');if(pv)return savePackage(pv.dataset.packageSave);
  });
}
function switchView(view){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));qs('employeeView')?.classList.toggle('hidden',view!=='employee');qs('requestsView')?.classList.toggle('hidden',view!=='requests');qs('managerView')?.classList.toggle('hidden',view!=='manager');const t={employee:['Neue Konferenzanfrage','Raum, Services und Bewirtung in einer Anfrage.'],requests:['Meine Anfragen','Status und Details deiner Konferenzanfragen.'],manager:['Manager Cockpit','Manuelle Freigabe sowie Pflege von Angebot und Preisen.']}[view];if(t){qs('viewTitle').textContent=t[0];qs('viewSubtitle').textContent=t[1]}if(view==='requests')renderRequests();if(view==='manager')renderManager()}
function updateStep(){document.querySelectorAll('.step').forEach(b=>{const s=Number(b.dataset.step);b.classList.toggle('active',s===state.step);b.classList.toggle('done',s<state.step)});document.querySelectorAll('.step-panel').forEach(p=>p.classList.toggle('active',Number(p.dataset.panel)===state.step));qs('backBtn')?.classList.toggle('hidden',state.step===1);qs('nextBtn')?.classList.toggle('hidden',state.step===6);qs('submitBtn')?.classList.toggle('hidden',state.step!==6);if(state.step===2)renderRooms();if(state.step===5)updateCosts();if(state.step===6)renderReview()}
function validateStep(step){if(step===1){const i=Number(qs('internalParticipants').value||0),e=Number(qs('externalParticipants').value||0);if(i<0||e<0){toast('Teilnehmerzahlen dürfen nicht negativ sein.');return false}if(!qs('title').value.trim()||!qs('date').value||!qs('start').value||!qs('end').value||totalParticipants()<1){toast('Bitte Terminangaben vollständig ausfüllen.');return false}if(qs('end').value<=qs('start').value){toast('Die Endzeit muss nach der Startzeit liegen.');return false}}if(step===2&&!state.roomId){toast('Bitte einen verfügbaren Raum auswählen.');return false}if(step===5){const sum=state.allocations.reduce((a,b)=>a+Number(b.percent||0),0);if(Math.abs(sum-100)>.01){toast('Die Kostenanteile müssen zusammen 100 % ergeben.');return false}if(state.allocations.some(a=>!a.costCenter.trim())){toast('Bitte alle Kostenstellen ausfüllen.');return false}}return true}

function renderLocations(){const select=qs('location');if(!select)return;const current=select.value;const locations=[...new Set(activeRooms().map(r=>r.location))].sort();select.innerHTML=locations.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(locations.includes(current))select.value=current}
function updateParticipantTotal(){if(qs('participantTotal'))qs('participantTotal').textContent=`${totalParticipants()} Teilnehmende`}
function renderRooms(){const candidates=activeRooms().filter(r=>r.location===qs('location').value&&r.capacity>=totalParticipants());qs('rooms').innerHTML=candidates.length?candidates.map(r=>{const busy=mockCalendarBusy(r.id);return `<div class="option-card ${busy?'':'selectable'} ${state.roomId===r.id?'selected':''}" data-room="${r.id}"><span class="badge ${busy?'danger':'success'}">${busy?'Belegt':'Verfügbar'}</span><h3>${escapeHtml(r.name)}</h3><p>${r.capacity} Personen</p><p>${escapeHtml(r.equipment)}</p><div class="price">${euro.format(r.rate)} · Raumkosten</div></div>`}).join(''):'<div class="info-box">Kein Raum erfüllt aktuell Standort und Kapazität.</div>';qs('rooms').querySelectorAll('[data-room]').forEach(el=>el.addEventListener('click',()=>{if(mockCalendarBusy(el.dataset.room)){toast('Dieser Raum ist inzwischen belegt.');return}state.roomId=el.dataset.room;renderRooms();updateCosts()}))}
function isSelectedRoomStillCandidate(){const r=activeRooms().find(x=>x.id===state.roomId);return r&&r.location===qs('location').value&&r.capacity>=totalParticipants()}
function renderServices(){qs('services').innerHTML=activeServices().map(s=>`<div class="option-card selectable ${state.serviceIds.includes(s.id)?'selected':''}" data-service="${s.id}"><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.desc)}</p><div class="price">${euro.format(s.price)}</div></div>`).join('');qs('services').querySelectorAll('[data-service]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.service;state.serviceIds=state.serviceIds.includes(id)?state.serviceIds.filter(x=>x!==id):[...state.serviceIds,id];renderServices();updateCosts()}))}
function renderPackages(){qs('packages').innerHTML=catalog.cateringPackages.map(p=>`<section class="package-group"><div class="package-group-header"><div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'')}</p></div></div><div class="package-variants">${p.variants.map(v=>{const selected=state.packageSelection?.packageId===p.id&&state.packageSelection?.tier===v.tier;return `<article class="package-variant ${selected?'selected':''}" data-package-id="${p.id}" data-package-tier="${v.tier}"><img src="${escapeHtml(v.image)}" alt="${escapeHtml(p.name)} ${escapeHtml(v.tier)}" loading="lazy"><div class="package-variant-body"><span class="badge neutral">${escapeHtml(v.tier)}</span><h4>${escapeHtml(p.name)} · ${escapeHtml(v.tier)}</h4><p>${escapeHtml(v.desc)}</p><div class="price">${euro.format(v.pricePerPerson)} / Person · ${euro.format(v.pricePerPerson*totalParticipants())}</div></div></article>`}).join('')}</div></section>`).join('');qs('packages').querySelectorAll('[data-package-id]').forEach(el=>el.addEventListener('click',()=>{const next={packageId:el.dataset.packageId,tier:el.dataset.packageTier};state.packageSelection=state.packageSelection?.packageId===next.packageId&&state.packageSelection?.tier===next.tier?null:next;renderPackages();updateCosts()}))}
function renderItems(){qs('cateringItems').innerHTML=activeItems().map(i=>`<div class="item-row"><div><strong>${escapeHtml(i.name)}</strong><small>${euro.format(i.price)} / ${escapeHtml(i.unit)}</small></div><div class="qty-control"><button type="button" data-dec="${i.id}">−</button><strong>${state.quantities[i.id]||0}</strong><button type="button" data-inc="${i.id}">+</button></div><strong>${euro.format((state.quantities[i.id]||0)*i.price)}</strong></div>`).join('');qs('cateringItems').querySelectorAll('[data-inc]').forEach(b=>b.addEventListener('click',()=>{state.quantities[b.dataset.inc]=(state.quantities[b.dataset.inc]||0)+1;renderItems();updateCosts()}));qs('cateringItems').querySelectorAll('[data-dec]').forEach(b=>b.addEventListener('click',()=>{state.quantities[b.dataset.dec]=Math.max(0,(state.quantities[b.dataset.dec]||0)-1);renderItems();updateCosts()}))}
function costs(){const roomCost=catalog.rooms.find(r=>r.id===state.roomId)?.rate||0;const serviceCost=catalog.services.filter(s=>state.serviceIds.includes(s.id)).reduce((a,b)=>a+Number(b.price||0),0);const pack=selectedPackage();const packageCost=pack?Number(pack.variant.pricePerPerson||0)*totalParticipants():0;const itemCost=catalog.cateringItems.reduce((a,i)=>a+Number(i.price||0)*(state.quantities[i.id]||0),0);return{roomCost,serviceCost,cateringCost:packageCost+itemCost,total:roomCost+serviceCost+packageCost+itemCost}}
function updateCosts(){const c=costs();qs('roomCost').textContent=euro.format(c.roomCost);qs('serviceCost').textContent=euro.format(c.serviceCost);qs('cateringCost').textContent=euro.format(c.cateringCost);qs('totalCost').textContent=euro.format(c.total);renderAllocations();renderPackages()}
function renderAllocations(){const c=costs();qs('allocations').innerHTML=state.allocations.map((a,n)=>`<div class="allocation-row"><input data-cc="${n}" value="${escapeHtml(a.costCenter)}" placeholder="Kostenstelle"><input data-pct="${n}" type="number" min="0" max="100" value="${a.percent}"><input class="amount" value="${euro.format(c.total*(Number(a.percent||0)/100))}" disabled><button type="button" class="icon-btn" data-remove="${n}">×</button></div>`).join('');qs('allocations').querySelectorAll('[data-cc]').forEach(i=>i.addEventListener('input',()=>state.allocations[Number(i.dataset.cc)].costCenter=i.value));qs('allocations').querySelectorAll('[data-pct]').forEach(i=>i.addEventListener('input',()=>{state.allocations[Number(i.dataset.pct)].percent=Number(i.value||0);renderAllocations()}));qs('allocations').querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{if(state.allocations.length>1){state.allocations.splice(Number(b.dataset.remove),1);renderAllocations()}}));const sum=state.allocations.reduce((a,b)=>a+Number(b.percent||0),0);qs('allocationStatus').textContent=`Summe: ${sum.toFixed(0)} %`;qs('allocationStatus').className='validation-line '+(Math.abs(sum-100)<.01?'ok':'bad')}
function renderReview(){const room=catalog.rooms.find(r=>r.id===state.roomId),ss=catalog.services.filter(s=>state.serviceIds.includes(s.id)),pack=selectedPackage(),si=catalog.cateringItems.filter(i=>(state.quantities[i.id]||0)>0),c=costs();qs('review').innerHTML=`<div class="review-grid"><div class="review-card"><h3>Termin</h3><p><strong>${escapeHtml(qs('title').value)}</strong></p><p>${fmtDate(qs('date').value)} · ${qs('start').value}–${qs('end').value}</p><p>${totalParticipants()} Teilnehmende · ${escapeHtml(qs('location').value)}</p><p>${Number(qs('internalParticipants').value||0)} intern · ${Number(qs('externalParticipants').value||0)} extern</p></div><div class="review-card"><h3>Raum</h3><p><strong>${escapeHtml(room?.name||'—')}</strong></p><p>${escapeHtml(room?.equipment||'')}</p></div><div class="review-card"><h3>Services</h3><p>${ss.length?ss.map(s=>escapeHtml(s.name)).join(' · '):'Keine zusätzlichen Services'}</p></div><div class="review-card"><h3>Bewirtung</h3><p>${pack?`${escapeHtml(pack.package.name)} · ${escapeHtml(pack.variant.tier)}`:'Kein Paket'}</p><p>${pack?escapeHtml(pack.variant.desc):''}</p><p>${si.length?si.map(i=>`${state.quantities[i.id]}× ${escapeHtml(i.name)}`).join(' · '):'Keine Einzeloptionen'}</p></div><div class="review-card"><h3>Kostenverteilung</h3>${state.allocations.map(a=>`<p>${escapeHtml(a.costCenter)} · ${a.percent}%</p>`).join('')}</div><div class="review-card"><h3>Gesamtkosten</h3><p style="font-size:24px"><strong>${euro.format(c.total)}</strong></p><p>Geschätzte interne Kosten</p></div></div>`}

function submitRequest(){if(!validateStep(5)||!state.roomId)return;if(mockCalendarBusy(state.roomId)){toast('Raum wurde zwischenzeitlich gebucht. Bitte einen anderen Raum wählen.');state.step=2;state.roomId=null;updateStep();return}const c=costs(),pack=selectedPackage(),request={id:'CR-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5),title:qs('title').value.trim(),location:qs('location').value,date:qs('date').value,start:qs('start').value,end:qs('end').value,participants:totalParticipants(),internalParticipants:Number(qs('internalParticipants').value||0),externalParticipants:Number(qs('externalParticipants').value||0),roomId:state.roomId,serviceIds:[...state.serviceIds],packageSelection:pack?{packageId:pack.package.id,packageName:pack.package.name,tier:pack.variant.tier,pricePerPerson:pack.variant.pricePerPerson}:null,quantities:{...state.quantities},allocations:clone(state.allocations),estimatedCost:c.total,status:'Submitted',calendarStatus:'Tentative',createdAt:new Date().toISOString()};const rs=getRequests();rs.unshift(request);saveRequests(rs);toast(`Anfrage ${request.id} erstellt · Raum tentative reserviert.`);resetForm();switchView('requests')}
function resetForm(){state.step=1;state.roomId=null;state.serviceIds=[];state.packageSelection=null;state.quantities=Object.fromEntries(catalog.cateringItems.map(i=>[i.id,0]));state.allocations=[{costCenter:'471100',percent:100}];qs('title').value='';qs('internalParticipants').value=10;qs('externalParticipants').value=2;updateParticipantTotal();renderServices();renderPackages();renderItems();renderAllocations();updateStep()}
function renderRequests(){const rs=getRequests();qs('requestList').innerHTML=rs.length?rs.map(r=>requestCard(r,false)).join(''):'<div class="info-box">Noch keine Anfragen vorhanden.</div>'}
function requestCard(r,manager=false){const room=catalog.rooms.find(x=>x.id===r.roomId);const internal=r.internalParticipants??r.participants??0,external=r.externalParticipants??0,total=r.participants??internal+external;const managerActions=manager&&['Submitted','In Review'].includes(r.status)?`<div class="request-actions"><button type="button" class="primary success" data-manager-action="confirm" data-request-id="${r.id}">Bestätigen</button><button type="button" class="secondary" data-manager-action="change" data-request-id="${r.id}">Änderung anfordern</button><button type="button" class="danger-btn" data-manager-action="reject" data-request-id="${r.id}">Ablehnen</button></div>`:'';const requesterActions=!manager&&['Submitted','Confirmed','Change Requested'].includes(r.status)?`<div class="request-actions"><button type="button" class="danger-btn" data-cancel-request="${r.id}">Anfrage stornieren</button></div>`:'';return `<div class="request-card ${r.status==='Cancelled'?'cancelled':''}"><div class="request-top"><div><h3>${escapeHtml(r.title)}</h3><div class="request-meta">${r.id} · ${fmtDate(r.date)} · ${r.start}–${r.end}</div></div><span class="badge ${statusBadge(r.status)}">${statusLabel(r.status)}</span></div><div class="request-grid"><div><small>Raum</small><strong>${escapeHtml(room?.name||r.roomId||'—')}</strong></div><div><small>Teilnehmende</small><strong>${total}</strong></div><div><small>Intern / extern</small><strong>${internal} / ${external}</strong></div><div><small>Catering</small><strong>${escapeHtml(r.packageSelection?`${r.packageSelection.packageName} · ${r.packageSelection.tier}`:'—')}</strong></div><div><small>Kosten</small><strong>${euro.format(r.estimatedCost||0)}</strong></div></div>${managerActions}${requesterActions}</div>`}
function renderManager(){const rs=getRequests();qs('managerList').innerHTML=rs.length?rs.map(r=>requestCard(r,true)).join(''):'<div class="info-box">Keine Anfragen zur Prüfung.</div>';qs('statOpen').textContent=rs.filter(r=>['Submitted','In Review'].includes(r.status)).length;qs('statTentative').textContent=rs.filter(r=>r.calendarStatus==='Tentative').length;qs('statConfirmed').textContent=rs.filter(r=>r.status==='Confirmed').length;qs('statRooms').textContent=activeRooms().length;setManagerTab(state.managerTab,false)}
function managerAction(id,action){const rs=getRequests(),r=rs.find(x=>x.id===id);if(!r)return;if(action==='confirm'){r.status='Confirmed';r.calendarStatus='Busy';toast(`${id} bestätigt · Kalenderbuchung verbindlich.`)}else if(action==='reject'){r.status='Rejected';r.calendarStatus='Released';toast(`${id} abgelehnt · Reservierung freigegeben.`)}else if(action==='change'){r.status='Change Requested';r.calendarStatus='Tentative';toast(`${id}: Änderung angefordert.`)}saveRequests(rs);renderManager();renderRequests()}
function cancelRequest(id){const rs=getRequests(),r=rs.find(x=>x.id===id);if(!r||!['Submitted','Confirmed','Change Requested'].includes(r.status))return;if(!window.confirm(`Anfrage ${id} wirklich stornieren? Die Raumreservierung wird freigegeben.`))return;r.status='Cancelled';r.calendarStatus='Released';r.cancelledAt=new Date().toISOString();saveRequests(rs);toast(`${id} storniert · Raumreservierung freigegeben.`);renderRequests();renderManager()}
function statusLabel(s){return({Submitted:'Zur Prüfung',Confirmed:'Bestätigt',Rejected:'Abgelehnt','Change Requested':'Änderung angefordert',Cancelled:'Storniert'})[s]||s}
function statusBadge(s){return({Submitted:'warning',Confirmed:'success',Rejected:'danger','Change Requested':'neutral',Cancelled:'neutral'})[s]||'neutral'}

function setManagerTab(tab,render=true){state.managerTab=tab;document.querySelectorAll('[data-manager-tab]').forEach(b=>b.classList.toggle('active',b.dataset.managerTab===tab));qs('managerRequestsPanel').classList.toggle('hidden',tab!=='requests');qs('managerCatalogPanel').classList.toggle('hidden',tab!=='catalog');if(tab==='catalog'&&render)renderCatalog()}
function setCatalogTab(tab){state.catalogTab=tab;document.querySelectorAll('[data-catalog-tab]').forEach(b=>b.classList.toggle('active',b.dataset.catalogTab===tab));renderCatalog()}
function renderCatalog(){document.querySelectorAll('[data-catalog-tab]').forEach(b=>b.classList.toggle('active',b.dataset.catalogTab===state.catalogTab));if(state.catalogTab==='rooms')renderRoomEditor();else if(state.catalogTab==='services')renderServiceEditor();else renderCateringEditor()}
function renderRoomEditor(){qs('catalogEditor').innerHTML=`<div class="catalog-section">${catalog.rooms.map(r=>`<div class="catalog-row"><div class="catalog-grid"><label><span>Raumname</span><input id="room-name-${r.id}" value="${escapeHtml(r.name)}"></label><label><span>Standort</span><input id="room-location-${r.id}" value="${escapeHtml(r.location)}"></label><label><span>Kapazität</span><input id="room-capacity-${r.id}" type="number" min="1" value="${r.capacity}"></label><label><span>Preis</span><input id="room-rate-${r.id}" type="number" min="0" step="0.01" value="${r.rate}"></label><label class="active-check"><input id="room-active-${r.id}" type="checkbox" ${r.active!==false?'checked':''}> Aktiv</label></div><label><span>Ausstattung</span><input id="room-equipment-${r.id}" value="${escapeHtml(r.equipment)}"></label><div class="catalog-actions"><button type="button" class="danger-btn" data-room-remove="${r.id}">Entfernen</button><button type="button" class="primary" data-room-save="${r.id}">Speichern</button></div></div>`).join('')}<div class="catalog-actions"><button type="button" class="secondary" data-room-add>+ Raum hinzufügen</button></div></div>`}
function saveRoom(id){const r=catalog.rooms.find(x=>x.id===id);if(!r)return;r.name=qs(`room-name-${id}`).value.trim();r.location=qs(`room-location-${id}`).value.trim();r.capacity=Number(qs(`room-capacity-${id}`).value||1);r.rate=Number(qs(`room-rate-${id}`).value||0);r.equipment=qs(`room-equipment-${id}`).value.trim();r.active=qs(`room-active-${id}`).checked;saveCatalog();afterCatalogChange('Raum gespeichert.')}
function addRoom(){const id='ROOM-'+Date.now();catalog.rooms.push({id,location:'Berlin',name:'Neuer Raum',capacity:8,equipment:'',rate:0,active:true});saveCatalog();renderCatalog();toast('Neuer Raum angelegt.')}
function removeRoom(id){if(!window.confirm('Raum wirklich aus dem Angebot entfernen?'))return;catalog.rooms=catalog.rooms.filter(r=>r.id!==id);saveCatalog();afterCatalogChange('Raum entfernt.')}
function renderServiceEditor(){qs('catalogEditor').innerHTML=`<div class="catalog-section">${catalog.services.map(s=>`<div class="catalog-row"><div class="catalog-grid service"><label><span>Leistung</span><input id="service-name-${s.id}" value="${escapeHtml(s.name)}"></label><label><span>Beschreibung</span><input id="service-desc-${s.id}" value="${escapeHtml(s.desc)}"></label><label><span>Preis</span><input id="service-price-${s.id}" type="number" min="0" step="0.01" value="${s.price}"></label><label class="active-check"><input id="service-active-${s.id}" type="checkbox" ${s.active!==false?'checked':''}> Aktiv</label></div><div class="catalog-actions"><button type="button" class="danger-btn" data-service-remove="${s.id}">Entfernen</button><button type="button" class="primary" data-service-save="${s.id}">Speichern</button></div></div>`).join('')}<div class="catalog-actions"><button type="button" class="secondary" data-service-add>+ Service hinzufügen</button></div></div>`}
function saveService(id){const s=catalog.services.find(x=>x.id===id);if(!s)return;s.name=qs(`service-name-${id}`).value.trim();s.desc=qs(`service-desc-${id}`).value.trim();s.price=Number(qs(`service-price-${id}`).value||0);s.active=qs(`service-active-${id}`).checked;saveCatalog();afterCatalogChange('Service gespeichert.')}
function addService(){const id='SERVICE-'+Date.now();catalog.services.push({id,name:'Neue Leistung',desc:'',price:0,active:true});saveCatalog();renderCatalog();toast('Neue Leistung angelegt.')}
function removeService(id){if(!window.confirm('Service wirklich aus dem Angebot entfernen?'))return;catalog.services=catalog.services.filter(s=>s.id!==id);state.serviceIds=state.serviceIds.filter(x=>x!==id);saveCatalog();afterCatalogChange('Service entfernt.')}
function renderCateringEditor(){qs('catalogEditor').innerHTML=catalog.cateringPackages.map(p=>`<section class="catalog-package"><div class="catalog-package-head"><div><h3>${escapeHtml(p.name)}</h3><small>${escapeHtml(p.description||'')}</small></div><button type="button" class="primary" data-package-save="${p.id}">Paket speichern</button></div><div class="catalog-package-body"><label><span>Paketbeschreibung</span><input id="package-description-${p.id}" value="${escapeHtml(p.description||'')}"></label>${p.variants.map((v,n)=>`<div class="catalog-row"><div class="catalog-grid variant"><label><span>Option</span><input value="${escapeHtml(v.tier)}" disabled></label><label><span>Beschreibung</span><input id="package-desc-${p.id}-${n}" value="${escapeHtml(v.desc)}"></label><label><span>Preis / Person</span><input id="package-price-${p.id}-${n}" type="number" min="0" step="0.01" value="${v.pricePerPerson}"></label><label><span>Bild-URL</span><input id="package-image-${p.id}-${n}" value="${escapeHtml(v.image)}"><img class="catalog-image-preview" src="${escapeHtml(v.image)}" alt=""></label></div></div>`).join('')}</div></section>`).join('')}
function savePackage(id){const p=catalog.cateringPackages.find(x=>x.id===id);if(!p)return;p.description=qs(`package-description-${id}`).value.trim();p.variants.forEach((v,n)=>{v.desc=qs(`package-desc-${id}-${n}`).value.trim();v.pricePerPerson=Number(qs(`package-price-${id}-${n}`).value||0);v.image=qs(`package-image-${id}-${n}`).value.trim()});saveCatalog();afterCatalogChange('Catering-Paket gespeichert.')}
function resetCatalog(){if(!window.confirm('Alle Räume, Services und Catering-Preise auf die Standardwerte zurücksetzen?'))return;catalog=clone(defaultCatalog);saveCatalog();state.serviceIds=[];state.roomId=null;state.packageSelection=null;state.quantities=Object.fromEntries(catalog.cateringItems.map(i=>[i.id,0]));afterCatalogChange('Standardwerte wiederhergestellt.')}
function afterCatalogChange(message){renderLocations();renderRooms();renderServices();renderPackages();renderItems();updateCosts();renderCatalog();renderManager();toast(message)}

document.addEventListener('DOMContentLoaded',init);
