(function(){
  const KEY='conference_language_v1';
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  let scheduled=false;
  const dict={
    'Willkommen':'Welcome','Neue Anfrage':'New request','Meine Anfragen':'My requests','Manager Cockpit':'Manager cockpit','Profil':'Profile','Hilfe & Kontakt':'Help & contact',
    'Neue Konferenzanfrage':'New conference request','Raum, Services und Bewirtung in einer Anfrage.':'Room, services and catering in one request.',
    'Termin':'Schedule','Raum':'Room','Services':'Services','Bewirtung':'Catering','Kosten':'Costs','Prüfen':'Review','optional':'optional',
    'Termin und Anlass':'Schedule and purpose','Diese Angaben werden für die Verfügbarkeitsprüfung verwendet.':'These details are used to check availability.',
    'Titel *':'Title *','Standort *':'Location *','Datum *':'Date *','Interne Teilnehmende *':'Internal participants *','Externe Teilnehmende':'External participants','Start *':'Start *','Ende *':'End *','Gesamt':'Total','Relevant für Raumkapazität und Bewirtung':'Relevant for room capacity and catering',
    'Verfügbare Räume':'Available rooms','Anzeige nach Kalenderverfügbarkeit, Standort und Kapazität.':'Shown by calendar availability, location and capacity.','Verfügbarkeit prüfen':'Check availability','Die Verfügbarkeit wird beim Öffnen dieses Schritts und erneut beim Absenden geprüft.':'Availability is checked when this step opens and again when you submit.',
    'Personal & Services (optional)':'Staff & services (optional)','Personal & Services':'Staff & services','Die konkrete Person wird später durch den Konferenzmanager disponiert.':'The specific person will be assigned later by Conference Management.','Keine zusätzlichen Services benötigt? Sie können diesen Schritt ohne Auswahl fortsetzen.':'No additional services needed? You can continue without selecting anything.',
    'Bewirtung (optional)':'Catering (optional)','Wähle ein Paket und darin die Qualitätsstufe Basic, Standard oder Deluxe.':'Choose a package and then the Basic, Standard or Deluxe tier.','Keine Bewirtung':'No catering','Ohne Catering fortfahren':'Continue without catering','Catering-Paket':'Catering package','Vordefiniertes Paket auswählen':'Choose a predefined package','Nur Einzeloptionen':'Individual items only','Getränke oder Snacks einzeln':'Choose drinks or snacks individually','Paket + Extras':'Package + extras','Paket mit Einzeloptionen ergänzen':'Add individual items to a package','Wählen Sie zuerst, welche Art der Bewirtung Sie benötigen.':'First choose what type of catering you need.','Einzeloptionen':'Individual items','Zusätzliche Einzelpositionen können unabhängig vom Paket ergänzt werden.':'Individual items can be added independently of a package.',
    'Catering für wie viele Personen?':'Catering for how many people?','Standardmäßig wird die Gesamtzahl der Teilnehmenden übernommen. Passen Sie die Anzahl nur an, wenn nicht alle Personen am Catering teilnehmen.':'By default, the total number of participants is used. Change it only if not everyone will join the catering.','Ernährung & Unverträglichkeiten':'Dietary requirements & intolerances','Besondere Anforderungen / Hinweise':'Special requirements / notes','Hinweis':'Note','Nutzen Sie dieses Feld für Anforderungen, die nicht durch Raum, Services oder Catering abgedeckt werden.':'Use this field for requirements not covered by room, services or catering.',
    'Voraussichtliche Kosten & Verteilung':'Estimated costs & allocation','Die voraussichtlichen Kosten werden vor der Freigabe transparent ausgewiesen.':'Estimated costs are shown transparently before approval.','Voraussichtlicher Gesamtbetrag':'Estimated total','Kostenanteile':'Cost allocation','Die Summe muss 100 % ergeben.':'The total must equal 100%.','+ Kostenstelle':'+ Cost center','Verwenden Sie die Kostenstelle, der die Veranstaltung belastet werden soll.':'Use the cost center that should be charged for the event.','Hilfe anzeigen':'Show help',
    'Anfrage prüfen':'Review request','Beim Absenden erfolgt eine finale Kalenderprüfung.':'A final calendar check is performed when you submit.','Was passiert nach dem Absenden?':'What happens after submitting?','Der ausgewählte Raum wird vorläufig reserviert.':'The selected room is provisionally reserved.','Das Conference Management prüft Raum, Services, Bewirtung und Kosten.':'Conference Management reviews room, services, catering and costs.','Sie erhalten eine Bestätigung oder eine Änderungsanfrage.':'You receive a confirmation or a change request.','Nach Bestätigung stehen die Gästeinformationen zur Verfügung.':'Guest information is available after confirmation.','Raum wird vorläufig reserviert':'Room will be provisionally reserved','Nach dem Absenden halten wir den ausgewählten Raum zunächst für Sie frei. Die Buchung wird verbindlich, sobald das Conference Management Ihre Anfrage bestätigt.':'After submitting, we initially hold the selected room for you. The booking becomes binding once Conference Management confirms your request.',
    'Zurück':'Back','Weiter':'Next','Anfrage absenden':'Submit request','Entwurf speichern':'Save draft','Entwurf fortsetzen':'Continue draft','Entwurf löschen':'Delete draft',
    'Eigene Konferenzanfragen und deren aktueller Status.':'Your conference requests and their current status.','Liste':'List','Kalender':'Calendar','Aktiv':'Active','Vergangen':'Past','Alle':'All','Heute':'Today',
    'Zur Prüfung':'Pending review','In Prüfung':'In review','Bestätigt':'Confirmed','Abgelehnt':'Rejected','Änderung angefordert':'Change requested','Storniert':'Cancelled','Änderung bearbeiten':'Edit requested change','Anfrage stornieren':'Cancel request','Details anzeigen':'View details','Willkommens-PDF':'Welcome PDF','Neue Anfrage auf Basis dieser Daten':'Create new request from this','Erneut anfragen':'Request again',
    'Keine Aktion erforderlich':'No action required','Der Raum ist vorläufig reserviert. Das Conference Management prüft Ihre Anfrage.':'The room is provisionally reserved. Conference Management is reviewing your request.','Aktion erforderlich':'Action required','Verbindlich bestätigt':'Binding confirmation','Die Buchung ist bestätigt. Gästeinformationen und PDF stehen zur Verfügung.':'The booking is confirmed. Guest information and PDF are available.','Anfrage abgelehnt':'Request rejected','Anfrage storniert':'Request cancelled','Die Reservierung wurde freigegeben. Sie können die Veranstaltung erneut anfragen.':'The reservation has been released. You can request the event again.',
    'Kein passender Raum verfügbar':'No suitable room available','Ändern Sie Termin oder Teilnehmerzahl – oder kontaktieren Sie das Conference Management.':'Change the schedule or participant count, or contact Conference Management.','Termin ändern':'Change schedule','Teilnehmerzahl ändern':'Change participant count','Conference Management kontaktieren':'Contact Conference Management',
    'Bitte noch eine Angabe prüfen':'Please review one more field','Bitte einen Titel eingeben.':'Please enter a title.','Bitte einen Standort auswählen.':'Please select a location.','Bitte ein Datum auswählen.':'Please select a date.','Bitte ein heutiges oder zukünftiges Datum auswählen.':'Please select today or a future date.','Bitte eine Startzeit auswählen.':'Please select a start time.','Bitte eine gültige Endzeit nach der Startzeit auswählen.':'Please select a valid end time after the start time.','Bitte mindestens eine teilnehmende Person angeben.':'Please enter at least one participant.','Bitte einen verfügbaren Raum auswählen.':'Please select an available room.','Die Kostenanteile müssen zusammen 100 % ergeben.':'Cost allocations must total 100%.','Bitte alle Kostenstellen ausfüllen.':'Please complete all cost centers.',
    'Rolle':'Role','Mitarbeiter':'Employee','Demo: Rolle wechseln':'Demo: switch role','Nur für Demo-Zwecke. Produktiv wird die Rolle über SSO und Berechtigungen vorgegeben.':'Demo only. In production, the role is provided by SSO and permissions.','Sprache / Language':'Language','Weitere Sprachen können später ergänzt werden.':'Additional languages can be added later.','Vorname':'First name','Name':'Last name','Logout':'Logout',
    'Auf einen Blick':'At a glance','Offene Anfragen':'Open requests','Kommende Buchungen':'Upcoming bookings','Nächste bestätigte Buchung':'Next confirmed booking','Noch keine kommende bestätigte Buchung.':'No upcoming confirmed booking yet.','Starte eine neue Anfrage oder prüfe deine offenen Vorgänge.':'Start a new request or review your open items.','So funktioniert es':'How it works','Termin & Raum':'Schedule & room','Datum, Teilnehmende und passenden Raum auswählen.':'Choose date, participants and a suitable room.','Leistungen auswählen':'Choose services','Services, Catering und Einzeloptionen ergänzen.':'Add services, catering and individual items.','Anfrage senden':'Submit request','Der Raum wird vorläufig reserviert und vom Manager geprüft.':'The room is provisionally reserved and reviewed by Conference Management.','Bestätigung & Gästeinfo':'Confirmation & guest info','Nach Freigabe stehen Buchungsdetails und Willkommensinformationen bereit.':'After approval, booking details and welcome information are available.','Neue Konferenz anfragen':'Request a new conference','Meine Buchungen ansehen':'View my bookings','In wenigen Schritten von Termin und Raum bis zur geprüften Buchungsanfrage.':'In a few steps from schedule and room to a reviewed booking request.','Aktuelle Hinweise':'Recent updates','Noch keine Benachrichtigungen.':'No notifications yet.',
    'Antworten auf häufige Fragen zur Konferenzanfrage.':'Answers to common questions about conference requests.','Kein Raum verfügbar?':'No room available?','Prüfen Sie Datum, Uhrzeit, Standort und Teilnehmerzahl. Wenn weiterhin kein Raum passt, wenden Sie sich an das Conference Management.':'Check date, time, location and participant count. If no room is suitable, contact Conference Management.','Welche Kostenstelle?':'Which cost center?','Wann ist die Buchung verbindlich?':'When is the booking binding?','Nach dem Absenden wird der Raum zunächst vorläufig reserviert. Verbindlich wird die Buchung erst nach Bestätigung durch das Conference Management.':'After submitting, the room is provisionally reserved. The booking becomes binding only after confirmation by Conference Management.','Sonderwünsche?':'Special requests?','Nutzen Sie „Besondere Anforderungen / Hinweise“ sowie bei Catering „Ernährung & Unverträglichkeiten“.':'Use “Special requirements / notes” and, for catering, “Dietary requirements & intolerances”.','Nachricht senden':'Send message',
    'Buchungen':'Bookings','Raumplanung':'Room planning','Reports':'Reports','Administration':'Administration','Handlungsbedarf':'Action required','7 Tage':'7 days','Kommende':'Upcoming','Suche':'Search','Status':'Status','Standort':'Location','Filter zurücksetzen':'Reset filters','Räume & Standorte':'Rooms & locations','Services & Catering':'Services & catering','Räume':'Rooms','Standorte':'Locations','Catering':'Catering'
  };
  const attrMap={'z. B. Management Workshop':'e.g. Management workshop','Anzahl eingeben':'Enter number','Bitte Standort auswählen':'Select location','z. B. U-Bestuhlung, Vorbereitung ab 08:30, besondere Zugangsanforderungen':'e.g. U-shape seating, preparation from 08:30, special access requirements','z. B. 2× vegan, 1× glutenfrei':'e.g. 2× vegan, 1× gluten-free','Kostenstelle':'Cost center','Ihre Frage oder Ihr Anliegen':'Your question or request','Titel oder Buchungsnummer':'Title or booking number'};
  function lang(){return localStorage.getItem(KEY)||'de'}
  function replaceDynamic(text){if(lang()!=='en')return text;return text.replace(/(\d+) Teilnehmende/g,'$1 participants').replace(/(\d+) Personen/g,'$1 people').replace(/(\d+) Plätze Reserve/g,'$1 seats spare').replace(/1 Platz Reserve/g,'1 seat spare').replace(/Kapazität (\d+) · (\d+) benötigt/g,'Capacity $1 · $2 needed').replace(/Beste Kapazitätspassung/g,'Best capacity fit').replace(/Voraussichtliche Kosten/g,'Estimated costs').replace(/Änderungsgrund:/g,'Change reason:').replace(/Grund der Ablehnung/g,'Reason for rejection').replace(/Änderung erforderlich/g,'Change required').replace(/Entwurf automatisch gespeichert/g,'Draft automatically saved')}
  function translateTextNode(n){const raw=n.nodeValue;if(!raw||!raw.trim())return;const lead=raw.match(/^\s*/)?.[0]||'',trail=raw.match(/\s*$/)?.[0]||'',core=raw.trim(),out=dict[core]||replaceDynamic(core);if(out!==core)n.nodeValue=lead+out+trail}
  function walk(root=document.body){if(lang()!=='en')return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||['SCRIPT','STYLE','NOSCRIPT'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let n;while(n=w.nextNode())translateTextNode(n);qa('[placeholder]',root).forEach(el=>{const v=el.getAttribute('placeholder');if(attrMap[v])el.setAttribute('placeholder',attrMap[v])});qa('[aria-label]',root).forEach(el=>{const v=el.getAttribute('aria-label');if(dict[v])el.setAttribute('aria-label',dict[v])})}
  function apply(){document.documentElement.lang=lang();if(lang()==='en')walk();const sel=q('#profileLanguage');if(sel)sel.value=lang();document.documentElement.dataset.language=lang()}
  function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;apply()},50)}
  function hooks(){document.addEventListener('click',schedule,true);document.addEventListener('change',schedule,true);window.addEventListener('conference-request-updated',schedule);window.addEventListener('conference-notifications-changed',schedule);window.addEventListener('conference-edit-loaded',schedule);['renderRooms','renderServices','renderPackages','renderItems','renderReview','renderRequests','renderManager','renderCatalog','updateStep'].forEach(name=>{try{const fn=window[name];if(typeof fn==='function'&&!fn.__i18nV24){window[name]=function(){const r=fn.apply(this,arguments);schedule();return r};window[name].__i18nV24=true}}catch(_){}})}
  function init(){apply();hooks();setTimeout(apply,120);document.documentElement.dataset.i18nBuild='2026.08.22.24'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
