(function(){
  const REQUEST_KEY='conference_requests',CATALOG_KEY='conference_catalog_v2';
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
  const getRequests=()=>{try{return JSON.parse(localStorage.getItem(REQUEST_KEY)||'[]')}catch{return[]}};
  const getCatalog=()=>{try{return JSON.parse(localStorage.getItem(CATALOG_KEY)||'null')}catch{return null}};
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const setText=(el,v)=>{if(el&&el.textContent!==String(v))el.textContent=String(v)};
  let listObserver=null,applying=false,scheduled=false;

  function styles(){if(q('#managerUxV2Styles'))return;const s=document.createElement('style');s.id='managerUxV2Styles';s.textContent=`
    .manager-tabs[role="tablist"],.catalog-nav[role="tablist"]{scrollbar-width:thin}[role="tab"][aria-selected="true"]{color:#000}.catalog-group-nav{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px}.catalog-group-nav button[aria-pressed="true"]{background:#000;color:#fff;box-shadow:inset 0 -4px 0 #86bc25}.ux-hidden-tab{display:none!important}
    .manager-booking-toolbar{display:grid;grid-template-columns:1.4fr .8fr .8fr .8fr;gap:10px;margin:0 0 18px;padding:14px;background:#f7f7f7;border:1px solid #d0d0ce}.manager-booking-toolbar label span{font-size:12px}.manager-filter-count{grid-column:1/-1;color:#63666a;font-size:13px}
    #managerList .request-grid,#managerList .manager-booking-summary-safe,#managerList .manager-booking-summary:not(.ux-manager-booking-overview){display:none!important}.ux-manager-booking-overview{margin-top:14px;padding:12px;border:1px solid #d0d0ce;background:#fafafa}.ux-manager-booking-overview>strong{display:block;margin-bottom:8px}.ux-booking-chips{display:flex;gap:7px;flex-wrap:wrap}.ux-booking-chips span{font-size:12px;padding:6px 8px;background:#ededed;border-left:3px solid #86bc25}.ux-manager-booking-overview small{display:block;color:#53565a;margin-top:8px;line-height:1.45}.manager-filter-hidden{display:none!important}
    #managerList .request-actions{align-items:center}#managerList [data-manager-action="change"]{margin-left:auto}#managerList [data-manager-action="reject"]{font-weight:600}
    .room-plan-view-toggle{display:flex;gap:8px;margin:0 0 12px}.room-plan-view-toggle button[aria-pressed="true"]{background:#000;color:#fff;box-shadow:inset 0 -4px 0 #86bc25}.room-plan-list-view{overflow:auto}.room-plan-list{width:100%;border-collapse:collapse;background:#fff}.room-plan-list caption{text-align:left;font-weight:700;padding:8px 0 12px}.room-plan-list th,.room-plan-list td{text-align:left;padding:10px;border-bottom:1px solid #d0d0ce;vertical-align:top}.room-plan-list th{background:#f3f3f3}.room-plan-list .status{white-space:nowrap}
    @media(max-width:760px){.manager-booking-toolbar{grid-template-columns:1fr 1fr}}@media(max-width:640px){.manager-booking-toolbar{grid-template-columns:1fr}.manager-booking-toolbar .manager-filter-count{grid-column:auto}#managerList [data-manager-action="change"]{margin-left:0}}
  `;document.head.appendChild(s)}

  function idFromCard(card){const m=(q('.request-meta',card)?.textContent||'').match(/CR-\d{4}-\d+/);return m?m[0]:null}
  function statusLabel(s){return({Submitted:'Zur Prüfung','In Review':'In Prüfung',Confirmed:'Bestätigt',Rejected:'Abgelehnt','Change Requested':'Änderung angefordert',Cancelled:'Storniert'})[s]||s||'—'}
  function tabKey(e,tabs){const i=tabs.indexOf(e.currentTarget);if(i<0)return;let n=null;if(e.key==='ArrowRight')n=tabs[(i+1)%tabs.length];if(e.key==='ArrowLeft')n=tabs[(i-1+tabs.length)%tabs.length];if(e.key==='Home')n=tabs[0];if(e.key==='End')n=tabs[tabs.length-1];if(n){e.preventDefault();n.focus();n.click()}}
  function syncTabs(container,sel){qa(sel,container).forEach(b=>{const on=b.classList.contains('active');b.setAttribute('aria-selected',on?'true':'false');b.tabIndex=on?0:-1;const id=b.getAttribute('aria-controls'),p=id?q(`#${id}`):null;if(p)p.setAttribute('aria-hidden',p.classList.contains('hidden')?'true':'false')})}

  function managerTabs(){const tabs=q('.manager-tabs');if(!tabs)return;tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Manager-Bereiche');setText(q('#managerRequestsPanel .section-heading h2'),'Buchungen');setText(q('#managerRequestsPanel .section-heading p'),'Handlungsbedarf zuerst, bestätigte Termine danach. Gebuchte Leistungen und Details bleiben direkt erreichbar.');setText(q('#managerCatalogPanel .section-heading h2'),'Stammdaten');setText(q('#managerCatalogPanel .section-heading p'),'Räume, Standorte, Services und Catering zentral pflegen.');setText(q('#managerRoomPlanPanel .section-heading h2'),'Raumbelegung');setText(q('#managerRoomPlanPanel .section-heading p'),'Zeitplan und barrierefreie Listenansicht aller Reservierungen.');const order=['requests','roomplan','catalog'],labels={requests:'Buchungen',roomplan:'Raumbelegung',catalog:'Stammdaten'};order.forEach(v=>setText(q(`[data-manager-tab="${v}"]`,tabs),labels[v]));const cur=qa('[data-manager-tab]',tabs).map(x=>x.dataset.managerTab).join('|'),want=order.filter(v=>q(`[data-manager-tab="${v}"]`,tabs)).join('|');if(cur!==want)order.forEach(v=>{const b=q(`[data-manager-tab="${v}"]`,tabs);if(b)tabs.appendChild(b)});qa('[data-manager-tab]',tabs).forEach(b=>{const panel={requests:'managerRequestsPanel',roomplan:'managerRoomPlanPanel',catalog:'managerCatalogPanel'}[b.dataset.managerTab];b.id=`manager-tab-${b.dataset.managerTab}`;b.setAttribute('role','tab');b.setAttribute('aria-controls',panel||'');if(panel){const p=q(`#${panel}`);if(p){p.setAttribute('role','tabpanel');p.setAttribute('aria-labelledby',b.id);p.tabIndex=0}}if(!b.__uxTab){b.__uxTab=true;b.addEventListener('keydown',e=>tabKey(e,qa('[data-manager-tab]',tabs)));b.addEventListener('click',()=>setTimeout(()=>syncTabs(tabs,'[data-manager-tab]'),0))}});syncTabs(tabs,'[data-manager-tab]')}

  function catalogGroups(){const nav=q('.catalog-nav');if(!nav)return;nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Stammdaten-Bereiche');let g=q('.catalog-group-nav');if(!g){g=document.createElement('div');g.className='catalog-group-nav';g.setAttribute('aria-label','Stammdaten gruppieren');g.innerHTML='<button type="button" class="secondary" data-catalog-group="resources" aria-pressed="true">Räume & Standorte</button><button type="button" class="secondary" data-catalog-group="offers" aria-pressed="false">Services & Catering</button>';nav.parentNode.insertBefore(g,nav)}qa('[data-catalog-tab]',nav).forEach(b=>{b.setAttribute('role','tab');b.setAttribute('aria-controls','catalogEditor');if(!b.__uxTab){b.__uxTab=true;b.addEventListener('keydown',e=>tabKey(e,qa('[data-catalog-tab]',nav).filter(x=>!x.classList.contains('ux-hidden-tab'))));b.addEventListener('click',()=>{const group=['rooms','sites'].includes(b.dataset.catalogTab)?'resources':'offers';applyGroup(group,false);setTimeout(()=>syncTabs(nav,'[data-catalog-tab]'),0)})}});const editor=q('#catalogEditor');if(editor){editor.setAttribute('role','tabpanel');editor.setAttribute('aria-label','Stammdaten bearbeiten')}if(!g.__uxBound){g.__uxBound=true;g.addEventListener('click',e=>{const b=e.target.closest('[data-catalog-group]');if(b)applyGroup(b.dataset.catalogGroup,true)})}const active=q('[data-catalog-tab].active',nav);applyGroup(['rooms','sites'].includes(active?.dataset.catalogTab)?'resources':'offers',false)}
  function applyGroup(group,activate){const nav=q('.catalog-nav'),g=q('.catalog-group-nav');if(!nav||!g)return;qa('[data-catalog-group]',g).forEach(b=>b.setAttribute('aria-pressed',b.dataset.catalogGroup===group?'true':'false'));const allowed=group==='resources'?['rooms','sites']:['services','catering','items'];qa('[data-catalog-tab]',nav).forEach(b=>b.classList.toggle('ux-hidden-tab',!allowed.includes(b.dataset.catalogTab)));const a=q('[data-catalog-tab].active',nav);if(activate||!a||a.classList.contains('ux-hidden-tab'))qa('[data-catalog-tab]',nav).find(b=>!b.classList.contains('ux-hidden-tab'))?.click();syncTabs(nav,'[data-catalog-tab]')}

  function toolbar(){const panel=q('#managerRequestsPanel'),list=q('#managerList');if(!panel||!list)return;let t=q('#managerBookingToolbar');if(!t){t=document.createElement('div');t.id='managerBookingToolbar';t.className='manager-booking-toolbar';t.innerHTML=`<label><span>Suche</span><input id="managerSearch" type="search" placeholder="Titel oder Buchungsnummer"></label><label><span>Status</span><select id="managerStatusFilter"><option value="ALL">Alle</option><option value="ACTION">Handlungsbedarf</option><option value="Submitted">Zur Prüfung</option><option value="Confirmed">Bestätigt</option><option value="Change Requested">Änderung angefordert</option><option value="Rejected">Abgelehnt</option><option value="Cancelled">Storniert</option></select></label><label><span>Zeitraum</span><select id="managerDateFilter"><option value="UPCOMING">Kommende</option><option value="TODAY">Heute</option><option value="7D">Nächste 7 Tage</option><option value="ALL">Alle</option><option value="PAST">Vergangen</option></select></label><label><span>Standort</span><select id="managerLocationFilter"><option value="ALL">Alle Standorte</option></select></label><div id="managerFilterCount" class="manager-filter-count" role="status" aria-live="polite"></div>`;panel.insertBefore(t,list);qa('input,select',t).forEach(x=>{x.addEventListener('input',apply);x.addEventListener('change',apply)})}locations();if(!listObserver){listObserver=new MutationObserver(()=>{if(!applying)schedule()});listObserver.observe(list,{childList:true})}apply()}
  function locations(){const s=q('#managerLocationFilter');if(!s)return;const cur=s.value||'ALL',ls=[...new Set((getCatalog()?.rooms||[]).map(r=>r.location).filter(Boolean))].sort(),sig=ls.join('|');if(s.dataset.sig!==sig){s.dataset.sig=sig;s.innerHTML='<option value="ALL">Alle Standorte</option>'+ls.map(l=>`<option value="${esc(l)}">${esc(l)}</option>`).join('')}s.value=['ALL',...ls].includes(cur)?cur:'ALL'}
  function priority(r){const t=today();if(['Submitted','In Review'].includes(r.status))return 0;if(r.status==='Confirmed'&&r.date>=t)return 1;if(!['Cancelled','Rejected'].includes(r.status)&&r.date>=t)return 2;return 3}
  function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;apply()},0)}
  function apply(){const list=q('#managerList');if(!list)return;applying=true;try{const rs=getRequests(),c=getCatalog();decorate(rs,c);const map=new Map(rs.map(r=>[r.id,r])),cards=qa(':scope > .request-card',list),sorted=[...cards].sort((a,b)=>{const ra=map.get(idFromCard(a)),rb=map.get(idFromCard(b));if(!ra||!rb)return 0;const pa=priority(ra),pb=priority(rb);if(pa!==pb)return pa-pb;if(pa===3)return String(rb.date||'').localeCompare(String(ra.date||''));return String(ra.date||'').localeCompare(String(rb.date||''))||String(ra.start||'').localeCompare(String(rb.start||''))});const cur=cards.map(idFromCard).join('|'),want=sorted.map(idFromCard).join('|');if(cur!==want)sorted.forEach(x=>list.appendChild(x));const search=(q('#managerSearch')?.value||'').trim().toLowerCase(),status=q('#managerStatusFilter')?.value||'ALL',df=q('#managerDateFilter')?.value||'UPCOMING',loc=q('#managerLocationFilter')?.value||'ALL',now=today(),d7=new Date();d7.setDate(d7.getDate()+7);const end7=`${d7.getFullYear()}-${String(d7.getMonth()+1).padStart(2,'0')}-${String(d7.getDate()).padStart(2,'0')}`;let shown=0;sorted.forEach(card=>{const r=map.get(idFromCard(card));if(!r)return;const room=c?.rooms?.find(x=>x.id===r.roomId),hay=`${r.id} ${r.title} ${r.location||room?.location||''} ${room?.name||''}`.toLowerCase();let ok=!search||hay.includes(search);if(status==='ACTION')ok=ok&&['Submitted','In Review'].includes(r.status);else if(status!=='ALL')ok=ok&&r.status===status;if(df==='UPCOMING')ok=ok&&r.date>=now;if(df==='TODAY')ok=ok&&r.date===now;if(df==='7D')ok=ok&&r.date>=now&&r.date<=end7;if(df==='PAST')ok=ok&&r.date<now;if(loc!=='ALL')ok=ok&&(r.location||room?.location)===loc;card.classList.toggle('manager-filter-hidden',!ok);if(ok)shown++});setText(q('#managerFilterCount'),`${shown} von ${sorted.length} Buchungen angezeigt`);stats(rs)}finally{applying=false}}
  function decorate(rs,c){qa('#managerList .request-card').forEach(card=>{const id=idFromCard(card),r=rs.find(x=>x.id===id);if(!r)return;const room=c?.rooms?.find(x=>x.id===r.roomId),services=(r.serviceIds||[]).map(x=>c?.services?.find(s=>s.id===x)?.name||x),extras=Object.entries(r.quantities||{}).filter(([,n])=>Number(n)>0).map(([x,n])=>`${n}× ${c?.cateringItems?.find(i=>i.id===x)?.name||x}`),participants=r.participants??((r.internalParticipants||0)+(r.externalParticipants||0)),catering=r.packageSelection?`${r.packageSelection.packageName||r.packageSelection.packageId} · ${r.packageSelection.tier}`:'Ohne Catering-Paket',sig=JSON.stringify([room?.name,participants,r.externalParticipants,catering,r.estimatedCost,services,extras]);let box=q('.ux-manager-booking-overview',card);if(!box){box=document.createElement('div');box.className='ux-manager-booking-overview';card.insertBefore(box,q('.request-actions',card)||null)}if(box.dataset.sig!==sig){box.dataset.sig=sig;box.innerHTML=`<strong>Gebucht</strong><div class="ux-booking-chips"><span>${esc(room?.name||r.roomId||'—')}</span><span>${participants} Personen${r.externalParticipants?` · ${r.externalParticipants} extern`:''}</span><span>${esc(catering)}</span><span>${money(r.estimatedCost||0)}</span></div><small>${services.length?`Services: ${esc(services.join(', '))}`:'Keine Zusatzservices'}${extras.length?` · Extras: ${esc(extras.join(', '))}`:''}</small>`}let actions=q('.request-actions',card);if(!actions){actions=document.createElement('div');actions.className='request-actions';card.appendChild(actions)}let details=q('[data-request-detail]',card);if(!details){details=document.createElement('button');details.type='button';details.className='secondary';details.dataset.requestDetail=id;details.textContent='Details';actions.appendChild(details)}else setText(details,'Details');if(r.status==='Confirmed'&&!q('[data-welcome-pdf]',card)){const pdf=document.createElement('button');pdf.type='button';pdf.className='secondary';pdf.dataset.welcomePdf=id;pdf.textContent='Willkommens-PDF';actions.appendChild(pdf)}const confirm=q('[data-manager-action="confirm"]',actions),change=q('[data-manager-action="change"]',actions),reject=q('[data-manager-action="reject"]',actions),pdf=q('[data-welcome-pdf]',actions);[confirm,details,pdf,change,reject].filter(Boolean).forEach(x=>{actions.appendChild(x);x.setAttribute('aria-label',`${x.textContent.trim()} für ${r.title} (${r.id})`)})})}
  function stats(rs){[['statOpen','Handlungsbedarf'],['statRooms','Heute'],['statTentative','Tentative'],['statConfirmed','Bestätigt']].forEach(([id,l])=>setText(q(`#${id}`)?.parentElement?.querySelector('span'),l));const t=today();setText(q('#statOpen'),rs.filter(r=>['Submitted','In Review'].includes(r.status)).length);setText(q('#statRooms'),rs.filter(r=>r.date===t&&!['Cancelled','Rejected'].includes(r.status)).length);setText(q('#statTentative'),rs.filter(r=>r.calendarStatus==='Tentative'&&!['Cancelled','Rejected'].includes(r.status)).length);setText(q('#statConfirmed'),rs.filter(r=>r.status==='Confirmed').length)}

  function roomPlan(){const panel=q('#managerRoomPlanPanel'),content=q('#roomPlanContent');if(!panel||!content)return;let t=q('.room-plan-view-toggle',panel);if(!t){t=document.createElement('div');t.className='room-plan-view-toggle';t.setAttribute('aria-label','Darstellung der Raumbelegung');t.innerHTML='<button type="button" class="secondary" data-roomplan-view="timeline" aria-pressed="true">Zeitplan</button><button type="button" class="secondary" data-roomplan-view="list" aria-pressed="false">Liste</button>';content.parentNode.insertBefore(t,content)}let l=q('#roomPlanListView');if(!l){l=document.createElement('div');l.id='roomPlanListView';l.className='room-plan-list-view hidden';l.setAttribute('role','region');l.setAttribute('aria-label','Raumbelegung als Liste');content.parentNode.insertBefore(l,content.nextSibling)}if(!t.__ux){t.__ux=true;t.addEventListener('click',e=>{const b=e.target.closest('[data-roomplan-view]');if(!b)return;const v=b.dataset.roomplanView;qa('[data-roomplan-view]',t).forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));content.classList.toggle('hidden',v==='list');l.classList.toggle('hidden',v!=='list');if(v==='list')planList()})}['roomPlanDate','roomPlanLocation','roomPlanRefresh','roomPlanToday'].forEach(id=>{const el=q(`#${id}`);if(el&&!el.__ux){el.__ux=true;el.addEventListener(id==='roomPlanDate'||id==='roomPlanLocation'?'change':'click',()=>setTimeout(()=>{planA11y();planList()},0))}});if(!content.__uxObs){const o=new MutationObserver(()=>{planA11y();planList()});o.observe(content,{childList:true});content.__uxObs=true}planA11y();planList()}
  function planA11y(){qa('#roomPlanContent .room-booking').forEach(b=>{b.tabIndex=0;b.setAttribute('role','group');b.setAttribute('aria-label',b.title||b.textContent.trim())})}
  function planList(){const l=q('#roomPlanListView');if(!l)return;const date=q('#roomPlanDate')?.value||today(),loc=q('#roomPlanLocation')?.value||'ALL',c=getCatalog(),rooms=(c?.rooms||[]).filter(r=>r.active!==false&&(loc==='ALL'||r.location===loc)),ids=new Set(rooms.map(r=>r.id)),rs=getRequests().filter(r=>r.date===date&&ids.has(r.roomId)&&!['Cancelled','Rejected'].includes(r.status)).sort((a,b)=>String(a.start).localeCompare(String(b.start))),sig=JSON.stringify([date,loc,rs.map(r=>[r.id,r.status,r.start,r.end,r.participants])]);if(l.dataset.sig===sig)return;l.dataset.sig=sig;l.innerHTML=rs.length?`<table class="room-plan-list"><caption>Raumbelegung am ${new Date(date+'T12:00:00').toLocaleDateString('de-DE')}</caption><thead><tr><th scope="col">Zeit</th><th scope="col">Raum</th><th scope="col">Veranstaltung</th><th scope="col">Teilnehmende</th><th scope="col">Status</th></tr></thead><tbody>${rs.map(r=>{const room=rooms.find(x=>x.id===r.roomId),p=r.participants??((r.internalParticipants||0)+(r.externalParticipants||0));return`<tr><td>${esc(r.start)}–${esc(r.end)}</td><td>${esc(room?.name||r.roomId)}</td><td>${esc(r.title)}</td><td>${p}</td><td>${esc(statusLabel(r.status))}</td></tr>`}).join('')}</tbody></table>`:'<div class="info-box">Für diesen Tag sind keine Buchungen vorhanden.</div>'}

  function enhance(){managerTabs();catalogGroups();toolbar();roomPlan()}
  function observer(){if(document.body.__managerUxV2)return;const o=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})});o.observe(document.body,{childList:true,subtree:true});document.body.__managerUxV2=true}
  function init(){styles();enhance();observer();qa('.nav-item[data-view="manager"]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{setText(q('#viewSubtitle'),'Buchungen steuern, Raumbelegung planen und Stammdaten pflegen.');enhance()},0)));document.documentElement.dataset.managerUxBuild='2026.08.22.14'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();