(function () {
  const SITE_KEY='conference_site_info_v1', CATALOG_KEY='conference_catalog_v2', MOCK_VERSION=3;
  const qs=id=>document.getElementById(id), qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  function emptySite(name){return{name,address:'',publicTransport:'',carArrival:'',parking:'',reception:'',building:'',visitorNotes:'',accessibility:'',contact:'',contactDetails:'',mapsUrl:'',wifiName:'',wifiPassword:'',wifiInstructions:'',mockData:false,mockVersion:0}}
  const defaults={
    Berlin:{...emptySite('Berlin'),mockData:true,mockVersion:MOCK_VERSION,address:'Musterallee 24, 10115 Berlin (Mock-Adresse)',publicTransport:'Vom Berliner Hauptbahnhof mit der S-Bahn bis Friedrichstraße, anschließend ca. 7 Minuten zu Fuß. Alternativ Buslinie M41 bis Haltestelle Musterallee. (Mock)',carArrival:'Anfahrt über Invalidenstraße, anschließend der Beschilderung „Besucher / Conference Center“ folgen. (Mock)',parking:'Besucherparkplätze P2 in der Tiefgarage, Einfahrt Musterstraße 8. Parkticket am Empfang validieren lassen. (Mock)',reception:'Bitte am Besucherempfang im Erdgeschoss anmelden und einen Lichtbildausweis bereithalten. (Mock)',building:'Nach dem Empfang geradeaus zu Aufzugskern B. Räume im 3. und 4. OG sind über Aufzug B erreichbar; das Auditorium liegt im Erdgeschoss links hinter dem Conference Desk. (Mock)',visitorNotes:'Externe Gäste sollten ca. 15 Minuten vor Veranstaltungsbeginn eintreffen. (Mock)',accessibility:'Stufenloser Zugang, Aufzüge zu allen Konferenzetagen und barrierefreies WC im Erdgeschoss. (Mock)',contact:'Conference Desk Berlin',contactDetails:'+49 30 555 0100 · conference.berlin@example.test',mapsUrl:'https://example.test/route/berlin',wifiName:'GuestConnect-Berlin',wifiPassword:'Welcome2026!',wifiInstructions:'Netzwerk auswählen, WLAN-Code eingeben und die Nutzungsbedingungen im Browser bestätigen. (Mock)'},
    Stuttgart:{...emptySite('Stuttgart'),mockData:true,mockVersion:MOCK_VERSION,address:'Beispielstraße 88, 70565 Stuttgart (Mock-Adresse)',publicTransport:'Ab Stuttgart Hauptbahnhof mit der S-Bahn bis Vaihingen. Von dort Bus 81 bis „Business Campus“. (Mock)',carArrival:'Über A8/A831 Richtung Stuttgart-Vaihingen, Ausfahrt „Business Campus“. (Mock)',parking:'Besucherparkhaus P1, Zufahrt Beispielstraße 90. E-Ladepunkte auf Ebene -1. (Mock)',reception:'Anmeldung am Welcome Desk in Gebäude A. Bitte Buchungsnummer oder Veranstaltungsnamen nennen. (Mock)',building:'Vom Welcome Desk durch die Glaspassage zum Konferenzbereich. Raum 2.01 liegt im 2. OG, das Atrium direkt im Erdgeschoss. (Mock)',visitorNotes:'Für größere Gruppen empfiehlt sich eine gemeinsame Ankunft 20 Minuten vor Beginn. (Mock)',accessibility:'Barrierefreier Eingang an Gebäude A, Aufzug zu allen Etagen, reservierte Stellplätze am Haupteingang. (Mock)',contact:'Visitor & Conference Services Stuttgart',contactDetails:'+49 711 555 0200 · conference.stuttgart@example.test',mapsUrl:'https://example.test/route/stuttgart',wifiName:'GuestConnect-STR',wifiPassword:'MeetInStuttgart!',wifiInstructions:'Mit GuestConnect-STR verbinden und den WLAN-Code eingeben. Das Gastnetz trennt die Verbindung nach 12 Stunden automatisch. (Mock)'},
    Frankfurt:{...emptySite('Frankfurt'),mockData:true,mockVersion:MOCK_VERSION,address:'Demoplatz 5, 60313 Frankfurt am Main (Mock-Adresse)',publicTransport:'Vom Frankfurt Hauptbahnhof mit U4/U5 bis Willy-Brandt-Platz, danach ca. 8 Minuten zu Fuß Richtung Demoplatz. (Mock)',carArrival:'Über Mainzer Landstraße Richtung Innenstadt und anschließend der Beschilderung „Visitor Parking“ folgen. (Mock)',parking:'Besucherstellplätze im Parkdeck P3. Kennzeichen bitte beim Empfang angeben. (Mock)',reception:'Der Besucherempfang befindet sich im Foyer des Hauptgebäudes. Bitte Lichtbildausweis und Veranstaltungsnamen bereithalten. (Mock)',building:'Nach dem Empfang rechts zu den Aufzügen C. Raum 1.05 befindet sich im 1. OG. (Mock)',visitorNotes:'WLAN-Zugangsdaten und weitere Hinweise werden im Raum bereitgestellt. (Mock)',accessibility:'Stufenloser Haupteingang, barrierefreier Aufzug C und barrierefreies WC im 1. OG. (Mock)',contact:'Conference Services Frankfurt',contactDetails:'+49 69 555 0300 · conference.frankfurt@example.test',mapsUrl:'https://example.test/route/frankfurt',wifiName:'GuestConnect-FRA',wifiPassword:'FrankfurtGuest26',wifiInstructions:'Gastnetz auswählen und mit dem WLAN-Code verbinden. Bei Problemen hilft der Conference Desk. (Mock)'}
  };
  function getCatalog(){try{return JSON.parse(localStorage.getItem(CATALOG_KEY)||'null')}catch{return null}}
  function knownLocations(){return[...new Set([...Object.keys(defaults),...(getCatalog()?.rooms?.map(r=>r.location).filter(Boolean)||[])])].sort()}
  function loadAll(){let data={};try{data=JSON.parse(localStorage.getItem(SITE_KEY)||'{}')||{}}catch{}let changed=false;knownLocations().forEach(loc=>{const def=defaults[loc]||emptySite(loc),cur=data[loc];if(!cur){data[loc]={...def};changed=true;return}if((cur.mockData===true||!String(cur.address||'').trim())&&Number(cur.mockVersion||0)<MOCK_VERSION&&defaults[loc]){data[loc]={...def};changed=true;return}const merged={...emptySite(loc),...cur,name:loc};if(JSON.stringify(merged)!==JSON.stringify(cur))changed=true;data[loc]=merged});if(changed)localStorage.setItem(SITE_KEY,JSON.stringify(data));return data}
  function saveAll(data){localStorage.setItem(SITE_KEY,JSON.stringify(data))}
  window.getConferenceSiteInfo=loc=>loadAll()[loc]||emptySite(loc||'Standort');
  function injectStyles(){if(qs('siteInfoStyles'))return;const st=document.createElement('style');st.id='siteInfoStyles';st.textContent=`.site-editor{display:grid;gap:16px}.site-card{border:1px solid #d0d0ce;background:#fafafa;padding:18px}.site-card h3{margin:0 0 4px}.site-sub{margin:0 0 16px;color:#63666a}.site-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.site-fields .wide{grid-column:1/-1}.site-fields textarea{min-height:86px}.site-status{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.site-status span{font-size:12px;padding:5px 8px;background:#ededed}.site-status .ok{background:#eef7df;color:#046a38;border-left:3px solid #86bc25}.site-status .mock{background:#fff7e6;color:#6f4700;border-left:3px solid #f0b429}@media(max-width:760px){.site-fields{grid-template-columns:1fr}.site-fields .wide{grid-column:auto}}`;document.head.appendChild(st)}
  function ensureTab(){const nav=document.querySelector('.catalog-nav');if(!nav||nav.querySelector('[data-catalog-tab="sites"]'))return;const b=document.createElement('button');b.type='button';b.className='catalog-tab';b.dataset.catalogTab='sites';b.textContent='Standorte';nav.appendChild(b)}
  const slug=v=>String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const field=(id,l,v,c='')=>`<label class="${c}"><span>${l}</span><input id="${id}" value="${esc(v)}"></label>`;
  const area=(id,l,v,c='')=>`<label class="${c}"><span>${l}</span><textarea id="${id}">${esc(v)}</textarea></label>`;
  function completeness(s){const keys=['address','publicTransport','carArrival','parking','reception','building','contact','wifiName','wifiPassword'];const n=keys.filter(k=>String(s[k]||'').trim()).length;return{n,total:keys.length,ok:n===keys.length}}
  function renderEditor(){const ed=qs('catalogEditor');if(!ed)return;qsa('[data-catalog-tab]').forEach(b=>b.classList.toggle('active',b.dataset.catalogTab==='sites'));try{if(typeof state!=='undefined')state.catalogTab='sites'}catch{}const data=loadAll();ed.innerHTML=`<div class="info-box">Diese Angaben werden automatisch im Willkommens-PDF und in den Buchungsdetails verwendet.</div><div class="site-editor">${knownLocations().map(loc=>{const s=data[loc],c=completeness(s),id=slug(loc);return`<div class="site-card"><h3>${esc(loc)}</h3><p class="site-sub">Standort-, Gäste- und WLAN-Informationen.</p><div class="site-fields">${field(`site-address-${id}`,'Adresse',s.address,'wide')}${area(`site-public-${id}`,'ÖPNV-Anfahrt',s.publicTransport)}${area(`site-car-${id}`,'PKW-Anfahrt',s.carArrival)}${area(`site-parking-${id}`,'Parken',s.parking)}${area(`site-reception-${id}`,'Empfang / Zutritt',s.reception)}${area(`site-building-${id}`,'Im Gebäude / Weg zum Raum',s.building,'wide')}${area(`site-visitor-${id}`,'Hinweise für Besucher',s.visitorNotes)}${area(`site-access-${id}`,'Barrierefreiheit',s.accessibility)}${field(`site-contact-${id}`,'Ansprechpartner / Funktion',s.contact)}${field(`site-contactdetails-${id}`,'Kontakt',s.contactDetails)}${field(`site-wifi-${id}`,'WLAN / SSID',s.wifiName)}${field(`site-wifipw-${id}`,'WLAN-Code',s.wifiPassword)}${area(`site-wifiinfo-${id}`,'WLAN-Hinweise',s.wifiInstructions,'wide')}${field(`site-maps-${id}`,'Maps-/Routen-Link',s.mapsUrl,'wide')}</div><div class="site-status"><span class="${c.ok?'ok':''}">${c.n}/${c.total} Kernangaben gepflegt</span>${s.mockData?'<span class="mock">MOCK</span>':''}</div><div class="catalog-actions"><button type="button" class="primary" data-site-save="${esc(loc)}">Standort speichern</button></div></div>`}).join('')}</div>`}
  function saveSite(loc){const d=loadAll(),id=slug(loc),prev=d[loc]||emptySite(loc);d[loc]={name:loc,address:qs(`site-address-${id}`)?.value.trim()||'',publicTransport:qs(`site-public-${id}`)?.value.trim()||'',carArrival:qs(`site-car-${id}`)?.value.trim()||'',parking:qs(`site-parking-${id}`)?.value.trim()||'',reception:qs(`site-reception-${id}`)?.value.trim()||'',building:qs(`site-building-${id}`)?.value.trim()||'',visitorNotes:qs(`site-visitor-${id}`)?.value.trim()||'',accessibility:qs(`site-access-${id}`)?.value.trim()||'',contact:qs(`site-contact-${id}`)?.value.trim()||'',contactDetails:qs(`site-contactdetails-${id}`)?.value.trim()||'',wifiName:qs(`site-wifi-${id}`)?.value.trim()||'',wifiPassword:qs(`site-wifipw-${id}`)?.value.trim()||'',wifiInstructions:qs(`site-wifiinfo-${id}`)?.value.trim()||'',mapsUrl:qs(`site-maps-${id}`)?.value.trim()||'',mockData:prev.mockData===true,mockVersion:prev.mockVersion||0};saveAll(d);renderEditor();try{if(typeof toast==='function')toast(`${loc}: Standortinformationen gespeichert.`)}catch{}}
  document.addEventListener('click',e=>{const tab=e.target.closest('[data-catalog-tab="sites"]');if(tab){e.preventDefault();e.stopImmediatePropagation();renderEditor();return}const save=e.target.closest('[data-site-save]');if(save){e.preventDefault();e.stopImmediatePropagation();saveSite(save.dataset.siteSave)}},true);
  function init(){injectStyles();loadAll();ensureTab();const nav=document.querySelector('.catalog-nav');if(nav&&!nav.__siteObserver){const o=new MutationObserver(ensureTab);o.observe(nav,{childList:true});nav.__siteObserver=true}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
