(function(){
 const RK='conference_requests',q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const reqs=()=>{try{return JSON.parse(localStorage.getItem(RK)||'[]')}catch{return[]}};
 let month=new Date(),view='list',observer=null;
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const statusLabel=s=>({Submitted:'Zur Prüfung','In Review':'In Prüfung',Confirmed:'Bestätigt',Rejected:'Abgelehnt','Change Requested':'Änderung angefordert',Cancelled:'Storniert'})[s]||s||'—';
 const statusClass=s=>({Submitted:'submitted','In Review':'review',Confirmed:'confirmed',Rejected:'rejected','Change Requested':'change',Cancelled:'cancelled'})[s]||'neutral';
 function styles(){if(q('#uiV17Styles'))return;const s=document.createElement('style');s.id='uiV17Styles';s.textContent=`
 .topbar{background:#fff!important;color:#000!important;border-bottom:1px solid #d0d0ce!important}.topbar h1{color:#000!important}.topbar p{color:#63666a!important}
 .request-view-tools{display:flex;gap:8px;flex-wrap:wrap}.request-view-tools button[aria-pressed="true"]{background:#000;color:#fff;box-shadow:inset 0 -4px 0 #86bc25}.request-calendar-shell{margin-top:4px}.request-calendar-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:12px}.request-calendar-toolbar strong{margin-right:auto;font-size:18px}.request-calendar-wrap{overflow:auto;border:1px solid #d0d0ce;background:#fff}.request-calendar{width:100%;min-width:860px;border-collapse:collapse;table-layout:fixed}.request-calendar caption{text-align:left;padding:12px 14px;font-weight:800;background:#f5f5f5}.request-calendar th{padding:9px 8px;background:#000;color:#fff;border-right:1px solid #353535;font-size:12px}.request-calendar td{height:128px;vertical-align:top;border:1px solid #d0d0ce;padding:7px;background:#fff}.request-calendar td.other-month{background:#f7f7f7;color:#97999b}.request-calendar td.today{box-shadow:inset 0 0 0 3px #86bc25}.calendar-date{display:block;font-weight:800;font-size:12px;margin-bottom:6px}.calendar-events{display:grid;gap:4px;max-height:96px;overflow:auto}.calendar-event{width:100%;text-align:left;border:1px solid #d0d0ce;background:#f5f5f5;padding:5px 6px;font-size:11px;line-height:1.25;color:#000}.calendar-event.confirmed{border-left:4px solid #046a38}.calendar-event.submitted,.calendar-event.review{border-left:4px solid #a15c00}.calendar-event.change{border-left:4px solid #75787b}.calendar-event.rejected{border-left:4px solid #b42318}.calendar-event.cancelled{border-left:4px solid #97999b;opacity:.72}.calendar-event strong,.calendar-event small{display:block}.calendar-event small{color:#53565a;margin-top:2px}.request-calendar-legend{display:flex;gap:12px;flex-wrap:wrap;margin-top:10px;font-size:12px;color:#53565a}.request-calendar-legend span::before{content:'';display:inline-block;width:10px;height:10px;margin-right:5px;border-radius:50%;background:#97999b}.request-calendar-legend .confirmed::before{background:#046a38}.request-calendar-legend .open::before{background:#a15c00}.request-calendar-legend .rejected::before{background:#b42318}
 @media(max-width:640px){#requestsView .section-heading{align-items:flex-start}.request-view-tools{width:100%}.request-view-tools button{flex:1}.request-calendar-toolbar strong{width:100%;order:-1}.request-calendar td{height:112px}}
 `;document.head.appendChild(s)}
 function ensure(){const card=q('#requestsView .card'),heading=q('#requestsView .section-heading'),list=q('#requestList');if(!card||!heading||!list)return;let tools=q('#requestViewTools');if(!tools){tools=document.createElement('div');tools.id='requestViewTools';tools.className='request-view-tools';tools.setAttribute('aria-label','Darstellung der Anfragen');tools.innerHTML='<button type="button" class="secondary" data-request-view="list" aria-pressed="true">Liste</button><button type="button" class="secondary" data-request-view="calendar" aria-pressed="false">Kalender</button>';heading.appendChild(tools);tools.addEventListener('click',e=>{const b=e.target.closest('[data-request-view]');if(!b)return;setView(b.dataset.requestView)})}let cal=q('#requestCalendarShell');if(!cal){cal=document.createElement('div');cal.id='requestCalendarShell';cal.className='request-calendar-shell hidden';cal.innerHTML='<div class="request-calendar-toolbar"><strong id="requestCalendarMonth"></strong><button type="button" class="secondary" id="calendarPrev" aria-label="Vorheriger Monat">‹</button><button type="button" class="secondary" id="calendarToday">Heute</button><button type="button" class="secondary" id="calendarNext" aria-label="Nächster Monat">›</button></div><div id="requestCalendar" class="request-calendar-wrap"></div><div class="request-calendar-legend" aria-label="Statuslegende"><span class="confirmed">Bestätigt</span><span class="open">Offen / Prüfung</span><span>Änderung / Storniert</span><span class="rejected">Abgelehnt</span></div>';card.insertBefore(cal,list);q('#calendarPrev').addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()});q('#calendarNext').addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()});q('#calendarToday').addEventListener('click',()=>{month=new Date();render()})}if(!observer){observer=new MutationObserver(()=>{if(view==='calendar')render()});observer.observe(list,{childList:true})}setView(view,false)}
 function setView(next,focus=true){view=next==='calendar'?'calendar':'list';qa('[data-request-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.requestView===view?'true':'false'));q('#requestList')?.classList.toggle('hidden',view==='calendar');q('#requestCalendarShell')?.classList.toggle('hidden',view!=='calendar');if(view==='calendar')render();if(focus)q(`[data-request-view="${view}"]`)?.focus()}
 function render(){const target=q('#requestCalendar');if(!target)return;const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,start=new Date(first);start.setDate(first.getDate()-offset);const title=first.toLocaleDateString('de-DE',{month:'long',year:'numeric'});q('#requestCalendarMonth').textContent=title;const byDate=new Map();reqs().forEach(r=>{if(!r.date)return;if(!byDate.has(r.date))byDate.set(r.date,[]);byDate.get(r.date).push(r)});byDate.forEach(v=>v.sort((a,b)=>String(a.start||'').localeCompare(String(b.start||''))));const weekdays=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'],today=iso(new Date());let rows='';for(let w=0;w<6;w++){let cells='';for(let d=0;d<7;d++){const cur=new Date(start);cur.setDate(start.getDate()+w*7+d);const key=iso(cur),items=byDate.get(key)||[],other=cur.getMonth()!==first.getMonth();cells+=`<td class="${other?'other-month ':''}${key===today?'today':''}" data-date="${key}"><span class="calendar-date">${cur.getDate()}</span><div class="calendar-events">${items.map(r=>`<button type="button" class="calendar-event ${statusClass(r.status)}" data-request-detail="${esc(r.id)}" aria-label="${esc((r.start||'')+' '+r.title+', '+statusLabel(r.status))}"><strong>${esc(r.start||'')} · ${esc(r.title)}</strong><small>${esc(statusLabel(r.status))}</small></button>`).join('')}</div></td>`}rows+=`<tr>${cells}</tr>`}target.innerHTML=`<table class="request-calendar"><caption>${esc(title)} · alle Anfragen</caption><thead><tr>${weekdays.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`}
 function init(){styles();ensure();const rv=q('#requestsView');if(rv&&!rv.__calendarObserver){const o=new MutationObserver(ensure);o.observe(rv,{childList:true,subtree:false});rv.__calendarObserver=true}}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();