import { KEYS, readString, writeString } from './storage.js';

const MESSAGES = {
  de: {
    'app.title': 'Conference Manager', 'app.internalServices': 'Internal Services', 'app.mvp': 'MVP · Kalenderintegration simuliert',
    'nav.welcome': 'Willkommen', 'nav.newRequest': 'Neue Anfrage', 'nav.myRequests': 'Meine Anfragen', 'nav.manager': 'Manager Cockpit', 'nav.profile': 'Profil',
    'common.back': 'Zurück', 'common.next': 'Weiter', 'common.close': 'Schließen', 'common.cancel': 'Abbrechen', 'common.save': 'Speichern', 'common.delete': 'Löschen', 'common.edit': 'Bearbeiten', 'common.none': 'Keine', 'common.optional': 'optional', 'common.yes': 'Ja', 'common.no': 'Nein', 'common.today': 'Heute', 'common.all': 'Alle', 'common.active': 'Aktiv', 'common.past': 'Vergangen', 'common.person': 'Person',
    'a11y.skip': 'Direkt zum Hauptinhalt', 'a11y.mainNav': 'Hauptnavigation', 'a11y.steps': 'Schritte der Konferenzanfrage', 'a11y.step': 'Schritt {step} von 6: {label}', 'a11y.loggedIn': 'Angemeldeter Benutzer {name}', 'a11y.availableRooms': 'Verfügbare Räume', 'a11y.services': 'Services auswählen', 'a11y.catering': 'Catering auswählen', 'a11y.roomSelect': 'Raum auswählen', 'a11y.selected': 'Ausgewählt', 'a11y.unavailable': 'Nicht verfügbar', 'a11y.serviceAdd': '{name} hinzufügen', 'a11y.serviceRemove': '{name} entfernen', 'a11y.quantityDecrease': '{name} reduzieren', 'a11y.quantityIncrease': '{name} erhöhen', 'a11y.costCenter': 'Kostenstelle {index}', 'a11y.costPercent': 'Anteil Kostenstelle {index} in Prozent', 'a11y.removeCostCenter': 'Kostenstelle {index} entfernen',
    'welcome.greeting': 'Willkommen, {name}.', 'welcome.subtitle': 'Planen Sie eine Konferenz oder behalten Sie Ihre bestehenden Buchungen im Blick.', 'welcome.new': 'Neue Konferenz anfragen', 'welcome.bookings': 'Meine Buchungen ansehen', 'welcome.open': 'Offene Anfragen', 'welcome.upcoming': 'Kommende Buchungen', 'welcome.today': 'Heute', 'welcome.next': 'Nächste bestätigte Buchung', 'welcome.none': 'Noch keine kommende bestätigte Buchung.', 'welcome.noneText': 'Starten Sie eine neue Anfrage oder prüfen Sie Ihre offenen Vorgänge.', 'welcome.how': 'So funktioniert es', 'welcome.s1': 'Termin & Raum', 'welcome.s1d': 'Datum, Teilnehmende und passenden Raum auswählen.', 'welcome.s2': 'Leistungen auswählen', 'welcome.s2d': 'Services, Catering und Einzeloptionen ergänzen.', 'welcome.s3': 'Anfrage senden', 'welcome.s3d': 'Der Raum wird vorläufig reserviert und vom Conference Management geprüft.', 'welcome.s4': 'Bestätigung & Gästeinfo', 'welcome.s4d': 'Nach Bestätigung stehen Buchungsdetails und Gästeinformationen bereit.', 'welcome.notifications': 'Aktuelle Hinweise', 'welcome.noNotifications': 'Noch keine Benachrichtigungen.',
    'profile.title': 'Profil', 'profile.first': 'Vorname', 'profile.last': 'Name', 'profile.role': 'Rolle', 'profile.role.employee': 'Mitarbeiter', 'profile.role.manager': 'Conference Manager', 'profile.demo': 'Demo: Rolle wechseln', 'profile.demoNote': 'Nur für Demo-Zwecke. Produktiv wird die Rolle über SSO und Berechtigungen vorgegeben.', 'profile.language': 'Sprache', 'profile.languageNote': 'Weitere Sprachen können später ergänzt werden.', 'profile.help': 'Hilfe & Kontakt', 'profile.logout': 'Logout', 'profile.logoutMvp': 'Logout wird im MVP simuliert. Produktiv erfolgt die Abmeldung über SSO.',
    'request.heading': 'Neue Konferenzanfrage', 'request.subtitle': 'Raum, Services und Bewirtung in einer Anfrage.', 'request.step.schedule': 'Termin', 'request.step.room': 'Raum', 'request.step.services': 'Services', 'request.step.catering': 'Bewirtung', 'request.step.costs': 'Kosten', 'request.step.review': 'Prüfen',
    'schedule.heading': 'Termin und Anlass', 'schedule.desc': 'Diese Angaben werden für die Verfügbarkeitsprüfung verwendet.', 'schedule.title': 'Titel', 'schedule.location': 'Standort', 'schedule.date': 'Datum', 'schedule.internal': 'Interne Teilnehmende', 'schedule.external': 'Externe Teilnehmende', 'schedule.start': 'Start', 'schedule.end': 'Ende', 'schedule.total': 'Gesamt', 'schedule.totalHint': 'Relevant für Raumkapazität und Bewirtung', 'schedule.special': 'Besondere Anforderungen / Hinweise', 'schedule.specialPlaceholder': 'z. B. U-Bestuhlung, Vorbereitung ab 08:30, besondere Zugangsanforderungen', 'schedule.specialHint': 'Nutzen Sie dieses Feld für Anforderungen, die nicht durch Raum, Services oder Catering abgedeckt werden.', 'schedule.locationPlaceholder': 'Bitte Standort auswählen', 'schedule.titlePlaceholder': 'z. B. Management Workshop', 'schedule.participantPlaceholder': 'Anzahl eingeben',
    'room.heading': 'Verfügbare Räume', 'room.desc': 'Anzeige nach Kalenderverfügbarkeit, Standort und Kapazität.', 'room.refresh': 'Verfügbarkeit prüfen', 'room.refreshHint': 'Die Verfügbarkeit wird beim Öffnen dieses Schritts und erneut beim Absenden geprüft.', 'room.available': 'Verfügbar', 'room.busy': 'Belegt', 'room.cost': 'Raumkosten', 'room.capacity': 'Kapazität {capacity} · {needed} benötigt', 'room.reserve': '{count} Plätze Reserve', 'room.bestFit': 'Beste Kapazitätspassung', 'room.noLocation': 'An diesem Standort sind keine Räume verfügbar.', 'room.noCapacity': 'Kein Raum bietet ausreichend Kapazität. Der größte Raum bietet {capacity} Plätze.', 'room.noFree': 'Passende Räume sind im gewählten Zeitraum bereits belegt.', 'room.changeSchedule': 'Termin ändern', 'room.changeParticipants': 'Teilnehmerzahl ändern', 'room.contact': 'Conference Management kontaktieren', 'room.floorplan': 'Raumaufbau ansehen', 'room.floor': 'Etage', 'room.entrance': 'Eingang', 'room.table': 'Besprechungstisch', 'room.screen': 'Display / Screen', 'room.presentation': 'Präsentation',
    'services.heading': 'Personal & Services', 'services.desc': 'Die konkrete Person wird später durch das Conference Management disponiert.', 'services.none': 'Keine zusätzlichen Services benötigt? Sie können diesen Schritt ohne Auswahl fortsetzen.', 'services.recommended': 'Für Ihre Veranstaltung empfohlen', 'services.hostHint': 'Sinnvoll bei externen Gästen', 'services.avHint': 'Geeignet für hybride Veranstaltungen', 'services.itHint': 'Geeignet für technisch anspruchsvolle Meetings', 'services.staffHint': 'Sinnvoll mit Catering',
    'catering.heading': 'Bewirtung', 'catering.desc': 'Wählen Sie die passende Art der Bewirtung.', 'catering.mode.none': 'Keine Bewirtung', 'catering.mode.package': 'Catering-Paket', 'catering.mode.items': 'Nur Einzeloptionen', 'catering.mode.both': 'Paket + Extras', 'catering.people': 'Catering für wie viele Personen?', 'catering.peopleHint': 'Standardmäßig wird die Gesamtzahl der Teilnehmenden übernommen. Passen Sie die Anzahl nur an, wenn nicht alle Personen am Catering teilnehmen.', 'catering.dietary': 'Ernährung & Unverträglichkeiten', 'catering.dietaryPlaceholder': 'z. B. 2× vegan, 1× glutenfrei', 'catering.items': 'Einzeloptionen', 'catering.package': 'Paket', 'catering.noPackage': 'Kein Catering-Paket', 'catering.noItems': 'Keine Einzeloptionen', 'catering.noDietary': 'Keine Ernährungs- oder Unverträglichkeitsangaben',
    'cost.heading': 'Voraussichtliche Kosten & Verteilung', 'cost.desc': 'Die voraussichtlichen Kosten werden vor der Freigabe transparent ausgewiesen.', 'cost.room': 'Raum', 'cost.services': 'Services', 'cost.catering': 'Bewirtung', 'cost.total': 'Voraussichtlicher Gesamtbetrag', 'cost.allocations': 'Kostenanteile', 'cost.allocHint': 'Die Summe muss 100 % ergeben.', 'cost.add': 'Kostenstelle hinzufügen', 'cost.costCenter': 'Kostenstelle', 'cost.percent': 'Anteil in %', 'cost.help': 'Verwenden Sie die Kostenstelle, der die Veranstaltung belastet werden soll.', 'cost.sum': 'Summe: {sum} %', 'cost.note': 'Die Beträge basieren auf der aktuellen Auswahl. Änderungen im Prüfprozess können den finalen Betrag beeinflussen.',
    'review.heading': 'Anfrage prüfen', 'review.desc': 'Beim Absenden erfolgt eine finale Kalenderprüfung.', 'review.schedule': 'Termin', 'review.room': 'Raum', 'review.services': 'Services', 'review.catering': 'Catering-Details', 'review.costs': 'Kostenverteilung', 'review.total': 'Voraussichtliche Gesamtkosten', 'review.special': 'Besondere Anforderungen', 'review.after': 'Was passiert nach dem Absenden?', 'review.after1': 'Der ausgewählte Raum wird vorläufig reserviert.', 'review.after2': 'Das Conference Management prüft Raum, Services, Bewirtung und Kosten.', 'review.after3': 'Sie erhalten eine Bestätigung oder eine Änderungsanfrage.', 'review.after4': 'Nach Bestätigung stehen die Gästeinformationen zur Verfügung.', 'review.provisional': 'Raum wird vorläufig reserviert', 'review.provisionalText': 'Nach dem Absenden halten wir den ausgewählten Raum zunächst für Sie frei. Die Buchung wird verbindlich, sobald das Conference Management Ihre Anfrage bestätigt.', 'review.submit': 'Anfrage absenden', 'review.resubmit': 'Änderung erneut einreichen',
    'draft.saved': 'Entwurf gespeichert.', 'draft.autosaved': 'Entwurf automatisch gespeichert · {time}', 'draft.continue': 'Entwurf fortsetzen', 'draft.delete': 'Entwurf löschen', 'draft.restored': 'Entwurf wiederhergestellt.', 'draft.copiedPast': 'Die bisherigen Angaben wurden übernommen. Der ursprüngliche Termin liegt in der Vergangenheit – bitte wählen Sie einen neuen Termin.', 'draft.copied': 'Die Angaben wurden in eine neue Anfrage übernommen.',
    'validation.heading': 'Bitte noch eine Angabe prüfen', 'validation.title': 'Bitte einen Titel eingeben.', 'validation.location': 'Bitte einen Standort auswählen.', 'validation.date': 'Bitte ein Datum auswählen.', 'validation.dateFuture': 'Bitte ein heutiges oder zukünftiges Datum auswählen.', 'validation.start': 'Bitte eine Startzeit auswählen.', 'validation.end': 'Bitte eine gültige Endzeit nach der Startzeit auswählen.', 'validation.negative': 'Teilnehmerzahlen dürfen nicht negativ sein.', 'validation.participants': 'Bitte mindestens eine teilnehmende Person angeben.', 'validation.room': 'Bitte einen verfügbaren Raum auswählen.', 'validation.roomChanged': 'Der ausgewählte Raum passt nicht mehr zu Ihrer Anfrage. Bitte wählen Sie einen verfügbaren Raum erneut aus.', 'validation.roomBusy': 'Der ausgewählte Raum ist im gewählten Zeitraum inzwischen belegt. Bitte wählen Sie einen anderen Raum.', 'validation.centers': 'Bitte alle Kostenstellen ausfüllen.', 'validation.percentRange': 'Jeder Kostenanteil muss zwischen 0 % und 100 % liegen.', 'validation.alloc': 'Die Kostenanteile müssen zusammen 100 % ergeben.',
    'requests.heading': 'Meine Anfragen', 'requests.subtitle': 'Status und Details Ihrer Konferenzanfragen.', 'requests.list': 'Liste', 'requests.calendar': 'Kalender', 'requests.none': 'Noch keine Anfragen vorhanden.', 'requests.details': 'Details anzeigen', 'requests.guest': 'Gästeinformationen', 'requests.pdf': 'Willkommens-PDF', 'requests.cancel': 'Anfrage stornieren', 'requests.repeat': 'Erneut anfragen', 'requests.repeatRejected': 'Neue Anfrage auf Basis dieser Daten', 'requests.editChange': 'Änderung bearbeiten', 'requests.action': 'Aktion erforderlich', 'requests.noAction': 'Keine Aktion erforderlich', 'requests.provisional': 'Der Raum ist vorläufig reserviert. Das Conference Management prüft Ihre Anfrage.', 'requests.confirmed': 'Die Buchung ist verbindlich bestätigt. Gästeinformationen stehen zur Verfügung.', 'requests.rejectedText': 'Die Anfrage konnte nicht bestätigt werden.', 'requests.cancelledText': 'Die Reservierung wurde freigegeben.', 'requests.changeReason': 'Änderungsgrund', 'requests.rejectionReason': 'Grund der Ablehnung',
    'status.Submitted': 'Zur Prüfung', 'status.In Review': 'In Prüfung', 'status.Confirmed': 'Bestätigt', 'status.Rejected': 'Abgelehnt', 'status.Change Requested': 'Änderung angefordert', 'status.Cancelled': 'Storniert',
    'timeline.title': 'Buchungsverlauf', 'timeline.Submitted': 'Anfrage gesendet', 'timeline.In Review': 'In Prüfung', 'timeline.Confirmed': 'Bestätigt', 'timeline.Rejected': 'Abgelehnt', 'timeline.Change Requested': 'Änderung angefordert', 'timeline.Cancelled': 'Storniert', 'timeline.pending': 'Entscheidung offen', 'timeline.open': 'Noch offen',
    'dialog.changeTitle': 'Änderung anfordern', 'dialog.rejectTitle': 'Anfrage ablehnen', 'dialog.reason': 'Begründung', 'dialog.reasonPlaceholder': 'Konkreten Hinweis für den Mitarbeiter beschreiben', 'dialog.reasonRequired': 'Bitte eine Begründung angeben.', 'dialog.cancelTitle': 'Anfrage stornieren?', 'dialog.cancelText': 'Die Raumreservierung wird freigegeben.', 'dialog.cancelConfirm': 'Anfrage stornieren',
    'guest.title': 'Gästeinformationen', 'guest.subtitle': 'Alles Wichtige für Ihren Besuch.', 'guest.welcome': 'Willkommen zu „{title}“', 'guest.demo': 'Die Standort- und WLAN-Daten sind Mock-Daten.', 'guest.scheduleRoom': 'Termin & Raum', 'guest.address': 'Adresse & Anreise', 'guest.parking': 'Parken & Ankommen', 'guest.contact': 'Kontakt & Barrierefreiheit', 'guest.route': 'Route öffnen', 'guest.wifi': 'WLAN für Gäste', 'guest.network': 'Netzwerk', 'guest.code': 'WLAN-Code', 'guest.print': 'Drucken / Als PDF speichern', 'guest.askOrganizer': 'Bitte beim Veranstalter erfragen', 'guest.contactDefault': 'Conference Management',
    'help.title': 'Hilfe & Kontakt', 'help.subtitle': 'Antworten auf häufige Fragen zur Konferenzanfrage.', 'help.noRoom': 'Kein Raum verfügbar?', 'help.noRoomText': 'Prüfen Sie Datum, Uhrzeit, Standort und Teilnehmerzahl. Wenn weiterhin kein Raum passt, wenden Sie sich an das Conference Management.', 'help.cost': 'Welche Kostenstelle?', 'help.costText': 'Verwenden Sie die Kostenstelle, der die Veranstaltung belastet werden soll.', 'help.binding': 'Wann ist die Buchung verbindlich?', 'help.bindingText': 'Nach dem Absenden wird der Raum zunächst vorläufig reserviert. Verbindlich wird die Buchung erst nach Bestätigung durch das Conference Management.', 'help.special': 'Sonderwünsche?', 'help.specialText': 'Nutzen Sie „Besondere Anforderungen / Hinweise“ sowie bei Catering „Ernährung & Unverträglichkeiten“.', 'help.contact': 'Conference Management kontaktieren', 'help.message': 'Ihre Frage oder Ihr Anliegen', 'help.send': 'Nachricht senden', 'help.sent': 'Ihre Nachricht wurde im MVP lokal simuliert.',
    'manager.heading': 'Manager Cockpit', 'manager.bookings': 'Buchungen', 'manager.roomPlan': 'Raumplanung', 'manager.reports': 'Reports', 'manager.admin': 'Administration', 'manager.confirm': 'Bestätigen', 'manager.change': 'Änderung anfordern', 'manager.reject': 'Ablehnen', 'manager.noRequests': 'Keine Anfragen zur Prüfung.', 'manager.filter': 'Filter', 'manager.search': 'Suche', 'manager.status': 'Status', 'manager.location': 'Standort', 'manager.allStatuses': 'Alle Status', 'manager.allLocations': 'Alle Standorte', 'manager.roomPlanDesc': 'Tagesübersicht der Raumbelegung.', 'manager.referenceDate': 'Bezugsdatum', 'manager.reportDesc': 'Operative Übersicht für den gewählten Zeitraum.', 'manager.confirmedBookings': 'Bestätigte Buchungen', 'manager.openRequests': 'Offene Anfragen', 'manager.cateringBookings': 'Buchungen mit Catering', 'manager.totalParticipants': 'Teilnehmende', 'manager.adminDesc': 'Räume, Services, Catering und Standortinformationen verwalten.', 'manager.rooms': 'Räume', 'manager.services': 'Services', 'manager.catering': 'Catering', 'manager.sites': 'Standorte', 'manager.addRoom': 'Raum hinzufügen', 'manager.addService': 'Service hinzufügen', 'manager.addItem': 'Einzeloption hinzufügen', 'manager.name': 'Bezeichnung', 'manager.capacity': 'Kapazität', 'manager.price': 'Preis', 'manager.equipment': 'Ausstattung', 'manager.active': 'Aktiv', 'manager.description': 'Beschreibung', 'manager.unit': 'Einheit', 'manager.address': 'Adresse', 'manager.publicTransport': 'ÖPNV-Anfahrt', 'manager.parking': 'Parken', 'manager.reception': 'Empfang / Zutritt', 'manager.accessibility': 'Barrierefreiheit', 'manager.contact': 'Kontakt', 'manager.saveCatalog': 'Stammdaten speichern', 'manager.saved': 'Stammdaten gespeichert.',
    'notification.received': 'Anfrage eingegangen', 'notification.receivedText': '{title} wurde zur Prüfung eingereicht.', 'notification.confirmed': 'Buchung bestätigt', 'notification.confirmedText': '{title} wurde bestätigt.', 'notification.change': 'Änderung angefordert', 'notification.rejected': 'Anfrage abgelehnt', 'notification.cancelled': 'Anfrage storniert', 'notification.resubmitted': 'Änderung eingereicht'
  },
  en: {}
};

const EN = {
  'app.title': 'Conference Manager', 'app.internalServices': 'Internal Services', 'app.mvp': 'MVP · calendar integration simulated',
  'nav.welcome': 'Welcome', 'nav.newRequest': 'New request', 'nav.myRequests': 'My requests', 'nav.manager': 'Manager cockpit', 'nav.profile': 'Profile',
  'common.back': 'Back', 'common.next': 'Next', 'common.close': 'Close', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit', 'common.none': 'None', 'common.optional': 'optional', 'common.yes': 'Yes', 'common.no': 'No', 'common.today': 'Today', 'common.all': 'All', 'common.active': 'Active', 'common.past': 'Past', 'common.person': 'person',
  'a11y.skip': 'Skip to main content', 'a11y.mainNav': 'Main navigation', 'a11y.steps': 'Conference request steps', 'a11y.step': 'Step {step} of 6: {label}', 'a11y.loggedIn': 'Signed-in user {name}', 'a11y.availableRooms': 'Available rooms', 'a11y.services': 'Choose services', 'a11y.catering': 'Choose catering', 'a11y.roomSelect': 'Select room', 'a11y.selected': 'Selected', 'a11y.unavailable': 'Unavailable', 'a11y.serviceAdd': 'Add {name}', 'a11y.serviceRemove': 'Remove {name}', 'a11y.quantityDecrease': 'Decrease {name}', 'a11y.quantityIncrease': 'Increase {name}', 'a11y.costCenter': 'Cost center {index}', 'a11y.costPercent': 'Percentage for cost center {index}', 'a11y.removeCostCenter': 'Remove cost center {index}',
  'welcome.greeting': 'Welcome, {name}.', 'welcome.subtitle': 'Plan a conference or keep track of your existing bookings.', 'welcome.new': 'Request a new conference', 'welcome.bookings': 'View my bookings', 'welcome.open': 'Open requests', 'welcome.upcoming': 'Upcoming bookings', 'welcome.today': 'Today', 'welcome.next': 'Next confirmed booking', 'welcome.none': 'No upcoming confirmed booking yet.', 'welcome.noneText': 'Start a new request or review your open items.', 'welcome.how': 'How it works', 'welcome.s1': 'Schedule & room', 'welcome.s1d': 'Choose a date, participants and a suitable room.', 'welcome.s2': 'Choose services', 'welcome.s2d': 'Add services, catering and individual items.', 'welcome.s3': 'Submit request', 'welcome.s3d': 'The room is provisionally held and reviewed by Conference Management.', 'welcome.s4': 'Confirmation & guest info', 'welcome.s4d': 'After confirmation, booking details and guest information are available.', 'welcome.notifications': 'Recent updates', 'welcome.noNotifications': 'No notifications yet.',
  'profile.title': 'Profile', 'profile.first': 'First name', 'profile.last': 'Last name', 'profile.role': 'Role', 'profile.role.employee': 'Employee', 'profile.role.manager': 'Conference Manager', 'profile.demo': 'Demo: switch role', 'profile.demoNote': 'Demo only. In production, the role is provided by SSO and permissions.', 'profile.language': 'Language', 'profile.languageNote': 'Additional languages can be added later.', 'profile.help': 'Help & contact', 'profile.logout': 'Logout', 'profile.logoutMvp': 'Logout is simulated in the MVP. Production logout will use SSO.',
  'request.heading': 'New conference request', 'request.subtitle': 'Room, services and catering in one request.', 'request.step.schedule': 'Schedule', 'request.step.room': 'Room', 'request.step.services': 'Services', 'request.step.catering': 'Catering', 'request.step.costs': 'Costs', 'request.step.review': 'Review',
  'schedule.heading': 'Schedule and purpose', 'schedule.desc': 'These details are used to check availability.', 'schedule.title': 'Title', 'schedule.location': 'Location', 'schedule.date': 'Date', 'schedule.internal': 'Internal participants', 'schedule.external': 'External participants', 'schedule.start': 'Start', 'schedule.end': 'End', 'schedule.total': 'Total', 'schedule.totalHint': 'Relevant for room capacity and catering', 'schedule.special': 'Special requirements / notes', 'schedule.specialPlaceholder': 'e.g. U-shape seating, preparation from 08:30, special access requirements', 'schedule.specialHint': 'Use this field for requirements not covered by room, services or catering.', 'schedule.locationPlaceholder': 'Select location', 'schedule.titlePlaceholder': 'e.g. Management workshop', 'schedule.participantPlaceholder': 'Enter number',
  'room.heading': 'Available rooms', 'room.desc': 'Shown by calendar availability, location and capacity.', 'room.refresh': 'Check availability', 'room.refreshHint': 'Availability is checked when this step opens and again when you submit.', 'room.available': 'Available', 'room.busy': 'Occupied', 'room.cost': 'Room cost', 'room.capacity': 'Capacity {capacity} · {needed} needed', 'room.reserve': '{count} seats spare', 'room.bestFit': 'Best capacity fit', 'room.noLocation': 'No rooms are available at this location.', 'room.noCapacity': 'No room has sufficient capacity. The largest room has {capacity} seats.', 'room.noFree': 'Suitable rooms are already occupied during the selected time.', 'room.changeSchedule': 'Change schedule', 'room.changeParticipants': 'Change participant count', 'room.contact': 'Contact Conference Management', 'room.floorplan': 'View room layout', 'room.floor': 'Floor', 'room.entrance': 'Entrance', 'room.table': 'Meeting table', 'room.screen': 'Display / screen', 'room.presentation': 'Presentation',
  'services.heading': 'Staff & services', 'services.desc': 'The specific person will be assigned later by Conference Management.', 'services.none': 'No additional services needed? You can continue without selecting anything.', 'services.recommended': 'Recommended for your event', 'services.hostHint': 'Useful for external guests', 'services.avHint': 'Suitable for hybrid events', 'services.itHint': 'Suitable for technically demanding meetings', 'services.staffHint': 'Useful with catering',
  'catering.heading': 'Catering', 'catering.desc': 'Choose the type of catering you need.', 'catering.mode.none': 'No catering', 'catering.mode.package': 'Catering package', 'catering.mode.items': 'Individual items only', 'catering.mode.both': 'Package + extras', 'catering.people': 'Catering for how many people?', 'catering.peopleHint': 'The total participant count is used by default. Change it only if not everyone will join the catering.', 'catering.dietary': 'Dietary requirements & intolerances', 'catering.dietaryPlaceholder': 'e.g. 2× vegan, 1× gluten-free', 'catering.items': 'Individual items', 'catering.package': 'Package', 'catering.noPackage': 'No catering package', 'catering.noItems': 'No individual items', 'catering.noDietary': 'No dietary or intolerance information',
  'cost.heading': 'Estimated costs & allocation', 'cost.desc': 'Estimated costs are shown transparently before approval.', 'cost.room': 'Room', 'cost.services': 'Services', 'cost.catering': 'Catering', 'cost.total': 'Estimated total', 'cost.allocations': 'Cost allocation', 'cost.allocHint': 'The total must equal 100%.', 'cost.add': 'Add cost center', 'cost.costCenter': 'Cost center', 'cost.percent': 'Percentage', 'cost.help': 'Use the cost center that should be charged for the event.', 'cost.sum': 'Total: {sum}%', 'cost.note': 'Amounts are based on the current selection. Changes during review may affect the final amount.',
  'review.heading': 'Review request', 'review.desc': 'A final calendar check is performed when you submit.', 'review.schedule': 'Schedule', 'review.room': 'Room', 'review.services': 'Services', 'review.catering': 'Catering details', 'review.costs': 'Cost allocation', 'review.total': 'Estimated total cost', 'review.special': 'Special requirements', 'review.after': 'What happens after submitting?', 'review.after1': 'The selected room is provisionally reserved.', 'review.after2': 'Conference Management reviews room, services, catering and costs.', 'review.after3': 'You receive a confirmation or a change request.', 'review.after4': 'Guest information is available after confirmation.', 'review.provisional': 'Room will be provisionally reserved', 'review.provisionalText': 'After submitting, we initially hold the selected room for you. The booking becomes binding once Conference Management confirms your request.', 'review.submit': 'Submit request', 'review.resubmit': 'Resubmit changes',
  'draft.saved': 'Draft saved.', 'draft.autosaved': 'Draft autosaved · {time}', 'draft.continue': 'Continue draft', 'draft.delete': 'Delete draft', 'draft.restored': 'Draft restored.', 'draft.copiedPast': 'The previous details were copied. The original date is in the past — please choose a new schedule.', 'draft.copied': 'The details were copied into a new request.',
  'validation.heading': 'Please review one more field', 'validation.title': 'Please enter a title.', 'validation.location': 'Please select a location.', 'validation.date': 'Please select a date.', 'validation.dateFuture': 'Please select today or a future date.', 'validation.start': 'Please select a start time.', 'validation.end': 'Please select a valid end time after the start time.', 'validation.negative': 'Participant counts cannot be negative.', 'validation.participants': 'Please enter at least one participant.', 'validation.room': 'Please select an available room.', 'validation.roomChanged': 'The selected room no longer matches your request. Please select an available room again.', 'validation.roomBusy': 'The selected room is now occupied during the selected time. Please choose another room.', 'validation.centers': 'Please complete all cost centers.', 'validation.percentRange': 'Each cost allocation must be between 0% and 100%.', 'validation.alloc': 'Cost allocations must total 100%.',
  'requests.heading': 'My requests', 'requests.subtitle': 'Status and details of your conference requests.', 'requests.list': 'List', 'requests.calendar': 'Calendar', 'requests.none': 'No requests yet.', 'requests.details': 'View details', 'requests.guest': 'Guest information', 'requests.pdf': 'Welcome PDF', 'requests.cancel': 'Cancel request', 'requests.repeat': 'Request again', 'requests.repeatRejected': 'Create new request from these details', 'requests.editChange': 'Edit requested change', 'requests.action': 'Action required', 'requests.noAction': 'No action required', 'requests.provisional': 'The room is provisionally reserved. Conference Management is reviewing your request.', 'requests.confirmed': 'The booking is confirmed. Guest information is available.', 'requests.rejectedText': 'The request could not be confirmed.', 'requests.cancelledText': 'The reservation has been released.', 'requests.changeReason': 'Change reason', 'requests.rejectionReason': 'Reason for rejection',
  'status.Submitted': 'Pending review', 'status.In Review': 'In review', 'status.Confirmed': 'Confirmed', 'status.Rejected': 'Rejected', 'status.Change Requested': 'Change requested', 'status.Cancelled': 'Cancelled',
  'timeline.title': 'Booking history', 'timeline.Submitted': 'Request submitted', 'timeline.In Review': 'In review', 'timeline.Confirmed': 'Confirmed', 'timeline.Rejected': 'Rejected', 'timeline.Change Requested': 'Change requested', 'timeline.Cancelled': 'Cancelled', 'timeline.pending': 'Decision pending', 'timeline.open': 'Still open',
  'dialog.changeTitle': 'Request changes', 'dialog.rejectTitle': 'Reject request', 'dialog.reason': 'Reason', 'dialog.reasonPlaceholder': 'Describe the requested change for the employee', 'dialog.reasonRequired': 'Please provide a reason.', 'dialog.cancelTitle': 'Cancel request?', 'dialog.cancelText': 'The room reservation will be released.', 'dialog.cancelConfirm': 'Cancel request',
  'guest.title': 'Guest information', 'guest.subtitle': 'Everything you need for your visit.', 'guest.welcome': 'Welcome to “{title}”', 'guest.demo': 'The location and Wi-Fi data are mock data.', 'guest.scheduleRoom': 'Schedule & room', 'guest.address': 'Address & directions', 'guest.parking': 'Parking & arrival', 'guest.contact': 'Contact & accessibility', 'guest.route': 'Open route', 'guest.wifi': 'Guest Wi-Fi', 'guest.network': 'Network', 'guest.code': 'Wi-Fi code', 'guest.print': 'Print / Save as PDF', 'guest.askOrganizer': 'Please ask the organizer', 'guest.contactDefault': 'Conference Management',
  'help.title': 'Help & contact', 'help.subtitle': 'Answers to common questions about conference requests.', 'help.noRoom': 'No room available?', 'help.noRoomText': 'Check date, time, location and participant count. If no room is suitable, contact Conference Management.', 'help.cost': 'Which cost center?', 'help.costText': 'Use the cost center that should be charged for the event.', 'help.binding': 'When is the booking binding?', 'help.bindingText': 'After submitting, the room is provisionally reserved. The booking becomes binding only after confirmation by Conference Management.', 'help.special': 'Special requests?', 'help.specialText': 'Use “Special requirements / notes” and, for catering, “Dietary requirements & intolerances”.', 'help.contact': 'Contact Conference Management', 'help.message': 'Your question or request', 'help.send': 'Send message', 'help.sent': 'Your message was simulated locally in the MVP.',
  'manager.heading': 'Manager cockpit', 'manager.bookings': 'Bookings', 'manager.roomPlan': 'Room planning', 'manager.reports': 'Reports', 'manager.admin': 'Administration', 'manager.confirm': 'Confirm', 'manager.change': 'Request changes', 'manager.reject': 'Reject', 'manager.noRequests': 'No requests to review.', 'manager.filter': 'Filter', 'manager.search': 'Search', 'manager.status': 'Status', 'manager.location': 'Location', 'manager.allStatuses': 'All statuses', 'manager.allLocations': 'All locations', 'manager.roomPlanDesc': 'Daily overview of room occupancy.', 'manager.referenceDate': 'Reference date', 'manager.reportDesc': 'Operational overview for the selected period.', 'manager.confirmedBookings': 'Confirmed bookings', 'manager.openRequests': 'Open requests', 'manager.cateringBookings': 'Bookings with catering', 'manager.totalParticipants': 'Participants', 'manager.adminDesc': 'Manage rooms, services, catering and location information.', 'manager.rooms': 'Rooms', 'manager.services': 'Services', 'manager.catering': 'Catering', 'manager.sites': 'Locations', 'manager.addRoom': 'Add room', 'manager.addService': 'Add service', 'manager.addItem': 'Add individual item', 'manager.name': 'Name', 'manager.capacity': 'Capacity', 'manager.price': 'Price', 'manager.equipment': 'Equipment', 'manager.active': 'Active', 'manager.description': 'Description', 'manager.unit': 'Unit', 'manager.address': 'Address', 'manager.publicTransport': 'Public transport', 'manager.parking': 'Parking', 'manager.reception': 'Reception / access', 'manager.accessibility': 'Accessibility', 'manager.contact': 'Contact', 'manager.saveCatalog': 'Save master data', 'manager.saved': 'Master data saved.',
  'notification.received': 'Request received', 'notification.receivedText': '{title} was submitted for review.', 'notification.confirmed': 'Booking confirmed', 'notification.confirmedText': '{title} was confirmed.', 'notification.change': 'Change requested', 'notification.rejected': 'Request rejected', 'notification.cancelled': 'Request cancelled', 'notification.resubmitted': 'Changes submitted'
};
Object.assign(MESSAGES.en, EN);

const SUPPORTED = Object.freeze(['de', 'en']);
let currentLanguage = SUPPORTED.includes(readString(KEYS.language, 'de')) ? readString(KEYS.language, 'de') : 'de';

export function language() { return currentLanguage; }
export function locale() { return currentLanguage === 'en' ? 'en-GB' : 'de-DE'; }
export function supportedLanguages() { return [...SUPPORTED]; }

export function t(key, values = {}) {
  const template = MESSAGES[currentLanguage]?.[key] ?? MESSAGES.de[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, token) => String(values[token] ?? ''));
}

export function setLanguage(nextLanguage) {
  if (!SUPPORTED.includes(nextLanguage) || nextLanguage === currentLanguage) return;
  currentLanguage = nextLanguage;
  writeString(KEYS.language, nextLanguage);
  document.documentElement.lang = nextLanguage;
  window.dispatchEvent(new CustomEvent('conference-language-changed', { detail: { language: nextLanguage } }));
}

export function formatDate(value, options = { day: '2-digit', month: '2-digit', year: 'numeric' }) {
  if (!value) return '';
  const date = new Date(/^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T12:00:00` : value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(locale(), options).format(date);
}

export function formatDateTime(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(locale(), { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date);
}

export function formatTime(value) { return value || ''; }
export function formatMoney(value) { return new Intl.NumberFormat(locale(), { style: 'currency', currency: 'EUR' }).format(Number(value || 0)); }
export function formatNumber(value, options) { return new Intl.NumberFormat(locale(), options).format(Number(value || 0)); }

document.documentElement.lang = currentLanguage;
