import { KEYS, readString, writeString } from './storage.js';

const MESSAGES = {
  de: {
    'app.title': 'Conference Manager', 'app.internalServices': 'Internal Services', 'app.mvp': 'MVP · Kalenderintegration simuliert',
    'nav.welcome': 'Willkommen', 'nav.newRequest': 'Neue Anfrage', 'nav.myRequests': 'Meine Anfragen', 'nav.manager': 'Manager Cockpit', 'nav.profile': 'Profil',
    'common.back': 'Zurück', 'common.next': 'Weiter', 'common.close': 'Schließen', 'common.cancel': 'Abbrechen', 'common.save': 'Speichern', 'common.delete': 'Löschen', 'common.edit': 'Bearbeiten', 'common.none': 'Keine', 'common.optional': 'optional', 'common.yes': 'Ja', 'common.no': 'Nein', 'common.today': 'Heute', 'common.all': 'Alle', 'common.active': 'Aktiv', 'common.past': 'Vergangen', 'common.person': 'Person',
    'a11y.skip': 'Direkt zum Hauptinhalt', 'a11y.mainNav': 'Hauptnavigation', 'a11y.steps': 'Schritte der Konferenzanfrage', 'a11y.step': 'Schritt {step} von 6: {label}', 'a11y.loggedIn': 'Angemeldeter Benutzer {name}', 'a11y.availableRooms': 'Verfügbare Räume', 'a11y.services': 'Services auswählen', 'a11y.catering': 'Catering auswählen', 'a11y.roomSelect': 'Raum auswählen', 'a11y.selected': 'Ausgewählt', 'a11y.unavailable': 'Nicht verfügbar', 'a11y.serviceAdd': '{name} hinzufügen', 'a11y.serviceRemove': '{name} entfernen', 'a11y.quantityDecrease': '{name} reduzieren', 'a11y.quantityIncrease': '{name} erhöhen', 'a11y.costCenter': 'Kostenstelle {index}', 'a11y.costPercent': 'Anteil Kostenstelle {index} in Prozent', 'a11y.removeCostCenter': 'Kostenstelle {index} entfernen',
    'welcome.greeting': 'Willkommen, {name}.', 'welcome.subtitle': 'Planen Sie eine Konferenz oder behalten Sie Ihre bestehenden Buchungen im Blick.', 'welcome.new': 'Neue Konferenz anfragen', 'welcome.bookings': 'Meine Buchungen ansehen', 'welcome.open': 'Offene Anfragen', 'welcome.upcoming': 'Kommende Buchungen', 'welcome.today': 'Heute', 'welcome.next': 'Nächste bestätigte Buchung', 'welcome.none': 'Noch keine kommende bestätigte Buchung.', 'welcome.noneText': 'Starten Sie eine neue Anfrage oder prüfen Sie Ihre offenen Vorgänge.', 'welcome.how': 'So funktioniert es', 'welcome.s1': 'Termin & Raum', 'welcome.s1d': 'Datum, Teilnehmende und passenden Raum auswählen.', 'welcome.s2': 'Leistungen auswählen', 'welcome.s2d': 'Services, Catering und Einzeloptionen ergänzen.', 'welcome.s3': 'Anfrage senden', 'welcome.s3d': 'Der Raum wird vorläufig reserviert und vom Conference Management geprüft.', 'welcome.s4': 'Bestätigung & Gästeinfo', 'welcome.s4d': 'Nach Bestätigung stehen Buchungsdetails und Gästeinformationen bereit.', 'welcome.notifications': 'Aktuelle Hinweise', 'welcome.noNotifications': 'Noch keine Benachrichtigungen.',
    'profile.title': 'Profil', 'profile.first': 'Vorname', 'profile.last': 'Name', 'profile.role': 'Rolle', 'profile.role.employee': 'Mitarbeiter', 'profile.role.manager': 'Conference Manager', 'profile.demo': 'Demo: Rolle wechseln', 'profile.demoNote': 'Nur für Demo-Zwecke. Produktiv wird die Rolle über SSO und Berechtigungen vorgegeben.', 'profile.language': 'Sprache', 'profile.languageNote': 'Weitere Sprachen können später ergänzt werden.', 'profile.help': 'Hilfe & Kontakt', 'profile.logout': 'Logout', 'profile.logoutMvp': 'Logout wird im MVP simuliert. Produktiv erfolgt die Abmeldung über SSO.',
    'request.heading': 'Neue Konferenzanfrage', 'request.subtitle': 'Raum, Services und Bewirtung in einer Anfrage.', 'request.step.schedule': 'Termin', 'request.step.room': 'Raum', 'request.step.services': 'Services', 'request.step.catering': 'Bewirtung', 'request.step.costs': 'Kosten', 'request.step.review': 'Prüfen',
    'schedule.heading': 'Termin und Anlass', 'schedule.desc': 'Diese Angaben werden für die Verfügbarkeitsprüfung verwendet.', 'schedule.title': 'Titel', 'schedule.location': 'Standort', 'schedule.date': 'Datum', 'schedule.internal': 'Interne Teilnehmende', 'schedule.external': 'Externe Teilnehmende', 'schedule.start': 'Start', 'schedule.end': 'Ende', 'schedule.total': 'Gesamt', 'schedule.totalHint': 'Relevant für Raumkapazität und Bewirtung', 'schedule.special': 'Besondere Anforderungen / Hinweise', 'schedule.specialPlaceholder': 'z. B. U-Bestuhlung, Vorbereitung ab 08:30, besondere Zugangsanforderungen', 'schedule.specialHint': 'Nutzen Sie dieses Feld für Anforderungen, die nicht durch Raum, Services oder Catering abgedeckt werden.', 'schedule.locationPlaceholder': 'Bitte Standort auswählen', 'schedule.titlePlaceholder': 'z. B. Management Workshop', 'schedule.participantPlaceholder': 'Anzahl eingeben',
    'room.heading': 'Verfügbare Räume', 'room.desc': 'Anzeige nach Kalenderverfügbarkeit, Standort und Kapazität.', 'room.refresh': 'Verfügbarkeit prüfen', 'room.refreshHint': 'Die Verfügbarkeit wird beim Öffnen dieses Schritts und erneut beim Absenden geprüft.', 'room.available': 'Verfügbar', 'room.busy': 'Belegt', 'room.cost': 'Raumkosten', 'room.capacity': 'Kapazität {capacity} · {needed} benötigt', 'room.reserve': '{count} Plätze Reserve', 'room.bestFit': 'Beste Kapazitätspassung', 'room.noLocation': 'An diesem Standort sind keine Räume verfügbar.', 'room.noCapacity': 'Kein Raum bietet ausreichend Kapazität. Der größte Raum bietet {capacity} Plätze.', 'room.noFree': 'Passende Räume sind im gewählten Zeitraum bereits belegt.', 'room.changeSchedule': 'Termin ändern', 'room.changeParticipants': 'Teilnehmerzahl ändern', 'room.contact': 'Conference Management kontaktieren', 'room.floorplan': 'Raumaufbau ansehen', 'room.floor': 'Etage', 'room.entrance': 'Eingang', 'room.table': 'Besprechungstisch', 'room.screen': 'Display / Screen', 'room.presentation': 'Präsentation',
    'services.heading': 'Personal & Services', 'services.desc': 'Die konkrete Person wird später durch das Conference Management disponiert.', 'services.none': 'Keine zusätzlichen Services benötigt? Sie können diesen Schritt ohne Auswahl fortsetzen.', 'services.recommended': 'Für Ihre Veranstaltung empfohlen', 'services.hostHint': 'Sinnvoll bei externen Gästen', 'services.avHint': 'Geeignet für hybride Veranstaltungen', 'services.itHint': 'Geeignet für technisch anspruchsvolle Meetings', 'services.staffHint': 'Sinnvoll mit Catering',
    'catering.heading': 'Bewirtung', 'catering.desc': 'Wählen Sie die passende Art der Bewirtung.', 'catering.mode.none': 'Keine Bewirtung', 'catering.mode.package': 'Catering-Paket', 'catering.mode.items': 'Nur Einzeloptionen', 'catering.mode.both': 'Paket + Extras', 'catering.people': 'Catering für wie viele Personen?', 'catering.peopleHint': 'Standardmäßig wird die Gesamtzahl der Teilnehmenden übernommen. Passen Sie die Anzahl nur an, wenn nicht alle Personen am Catering teilnehmen.', 'catering.dietary': 'Ernährung & Unverträglichkeiten', 'catering.dietaryPlaceholder': 'z. B. 2× vegan, 1× glutenfrei', 'catering.items': 'Einzeloptionen', 'catering.package': 'Paket', 'catering.noPackage': 'Kein Catering-Paket', 'catering.noItems': 'Keine Einzeloptionen', 'catering.noDietary': 'Keine Ernährungs- oder Unverträglichkeitsangaben',
    'cost.heading': 'Voraussichtliche Kosten & Verteilung', 'cost.desc': 'Die voraussichtlichen Kosten werden vor der Freigabe transparent ausgewiesen.', 'cost.room': 'Raum', 'cost.services': 'Services', 'cost.catering': 'Bewirtung', 'cost.total': 'Voraussichtlicher Gesamtbetrag', 'cost.allocations': 'Kostenanteile', 'cost.allocHint': 'Die Summe muss 100 % ergeben.', 'cost.add': 'Kostenstelle hinzufügen', 'cost.costCenter': 'Kostenstelle', 'cost.percent': 'Anteil in %', 'cost.help': 'Verwenden Sie die Kostenstelle, der die Veranstaltung belastet werden soll.', 'cost.sum': 'Summe: {sum} %', 'cost.note': 'Die Beträge basieren auf der aktuellen Auswahl. Änderungen im Prüfprozess können den finalen Betrag beeinflussen.',
    'review.heading': 'Anfrage prüfen', 'review.desc': 'Beim Absenden erfolgt eine finale Kalenderprüfung.', 'review.schedule': 'Termin', 'review.room': 'Raum', 'review.services': 'Services', 'review.catering': 'Catering-Details', 'review.costs': 'Kostenverteilung', 'review.total': 'Voraussichtliche Gesamtkosten', 'review.special': 'Besondere Anforderungen', 'review.after': 'Was passiert nach dem Absenden?', 'review.after1': 'Der ausgewählte Raum wird vorläufig reserviert.', 'review.after2': 'Das Conference Management prüft Raum, Services, Bewirtung und Kosten.', 'review.after3': 'Sie erhalten eine Bestätigung oder eine Änderungsanfrage.', 'review.after4': 'Nach Bestätigung stehen die Gästeinformationen zur Verfügung.', 'review.provisional': 'Raum wird vorläufig reserviert', 'review.provisionalText': 'Nach dem Absenden halten wir den ausgewählten Raum zunächst für Sie frei. Die Buchung wird verbindlich, sobald das Conference Management Ihre Anfrage bestätigt.', 'review.submit': 'Anfrage absenden', 'review.resubmit': 'Änderung erneut einreichen',
    'draft.saved': 'Entwurf gespeichert.', 'draft.autosaved': 'Entwurf automatisch gespeichert · {time}', 'draft.continue': 'Entwurf fortsetzen', 'draft.delete': 'Entwurf löschen', 'draft.restored': 'Entwurf wiederhergestellt.', 'draft.copiedPast': 'Die bisherigen Angaben wurden übernommen. Der ursprüngliche Termin liegt in der Vergangenheit – bitte wählen Sie einen neuen Termin.', 'draft.copied': 'Die Angaben wurden in eine neue Anfrage übernommen.',
    'validation.heading': 'Bitte noch eine Angabe prüfen', 'validation.title': 'Bitte einen Titel eingeben.', 'validation.location': 'Bitte einen Standort auswählen.', 'validation.date': 'Bitte ein Datum auswählen.', 'validation.dateFuture': 'Bitte ein heutiges oder zukünftiges Datum auswählen.', 'validation.start': 'Bitte eine Startzeit auswählen.', 'validation.end': 'Bitte eine gültige Endzeit nach der Startzeit auswählen.', 'validation.negative': 'Teilnehmerzahlen dürfen nicht negativ oder unendlich sein.', 'validation.participantRange': 'Teilnehmerzahlen müssen ganze Zahlen zwischen 0 und 500 sein.', 'validation.participants': 'Bitte mindestens eine teilnehmende Person angeben.', 'validation.room': 'Bitte einen verfügbaren Raum auswählen.', 'validation.roomChanged': 'Der ausgewählte Raum passt nicht mehr zu Ihrer Anfrage. Bitte wählen Sie einen verfügbaren Raum erneut aus.', 'validation.roomBusy': 'Der ausgewählte Raum ist im gewählten Zeitraum inzwischen belegt. Bitte wählen Sie einen anderen Raum.', 'validation.centers': 'Bitte alle Kostenstellen ausfüllen.', 'validation.percentRange': 'Jeder Kostenanteil muss zwischen 0 % und 100 % liegen.', 'validation.alloc': 'Die Kostenanteile müssen zusammen 100 % ergeben.',
    'requests.heading': 'Meine Anfragen', 'requests.subtitle': 'Status und Details Ihrer Konferenzanfragen.', 'requests.list': 'Liste', 'requests.calendar': 'Kalender', 'requests.none': 'Noch keine Anfragen vorhanden.', 'requests.details': 'Details anzeigen', 'requests.guest': 'Gästeinformationen', 'requests.pdf': 'Willkommens-PDF', 'requests.cancel': 'Anfrage stornieren', 'requests.repeat': 'Erneut anfragen', 'requests.repeatRejected': 'Neue Anfrage auf Basis dieser Daten', 'requests.editChange': 'Änderung bearbeiten', 'requests.action': 'Aktion erforderlich', 'requests.noAction': 'Keine Aktion erforderlich', 'requests.provisional': 'Der Raum ist vorläufig reserviert. Das Conference Management prüft Ihre Anfrage.', 'requests.confirmed': 'Die Buchung ist verbindlich bestätigt. Gästeinformationen stehen zur Verfügung.', 'requests.rejectedText': 'Die Anfrage konnte nicht bestätigt werden.', 'requests.cancelledText': 'Die Reservierung wurde freigegeben.', 'requests.changeReason': 'Änderungsgrund', 'requests.rejectionReason': 'Grund der Ablehnung',
    'status.Submitted': 'Zur Prüfung', 'status.In Review': 'In Prüfung', 'status.Confirmed': 'Bestätigt', 'status.Rejected': 'Abgelehnt', 'status.Change Requested': 'Änderung angefordert', 'status.Cancelled': 'Storniert',
    'timeline.title': 'Buchungsverlauf', 'timeline.Submitted': 'Anfrage gesendet', 'timeline.In Review': 'In Prüfung', 'timeline.Confirmed': 'Bestätigt', 'timeline.Rejected': 'Abgelehnt', 'timeline.Change Requested': 'Änderung angefordert', 'timeline.Cancelled': 'Storniert', 'timeline.pending': 'Entscheidung offen', 'timeline.open': 'Noch offen',
    'dialog.changeTitle': 'Änderung anfordern', 'dialog.rejectTitle': 'Anfrage ablehnen', 'dialog.reason': 'Begründung', 'dialog.reasonPlaceholder': 'Konkreten Hinweis für den Mitarbeiter beschreiben', 'dialog.reasonRequired': 'Bitte eine Begründung angeben.', 'dialog.cancelTitle': 'Anfrage stornieren?', 'dialog.cancelText': 'Die Raumreservierung wird freigegeben.', 'dialog.cancelConfirm': 'Anfrage stornieren',
    'guest.title': 'Gästeinformationen', 'guest.subtitle': 'Alles Wichtige für Ihren Besuch.', 'guest.welcome': 'Willkommen zu „{title}“', 'guest.demo': 'Die Standort- und WLAN-Daten sind Mock-Daten.', 'guest.scheduleRoom': 'Termin & Raum', 'guest.address': 'Adresse & Anreise', 'guest.parking': 'Parken & Ankommen', 'guest.contact': 'Kontakt & Barrierefreiheit', 'guest.route': 'Route öffnen', 'guest.wifi': 'WLAN für Gäste', 'guest.network': 'Netzwerk', 'guest.code': 'WLAN-Code', 'guest.print': 'Drucken / Als PDF speichern', 'guest.askOrganizer': 'Bitte beim Veranstalter erfragen', 'guest.contactDefault': 'Conference Management',
    'help.title': 'Hilfe & Kontakt', 'help.subtitle': 'Antworten auf häufige Fragen zur Konferenzanfrage.', 'help.noRoom': 'Kein Raum verfügbar?', 'help.noRoomText': 'Prüfen Sie Datum, Uhrzeit, Standort und Teilnehmerzahl. Wenn weiterhin kein Raum passt, wenden Sie sich an das Conference Management.', 'help.cost': 'Welche Kostenstelle?', 'help.costText': 'Verwenden Sie die Kostenstelle, der die Veranstaltung belastet werden soll.', 'help.binding': 'Wann ist die Buchung verbindlich?', 'help.bindingText': 'Nach dem Absenden wird der Raum zunächst vorläufig reserviert. Verbindlich wird die Buchung erst nach Bestätigung durch das Conference Management.', 'help.special': 'Sonderwünsche?', 'help.specialText': 'Nutzen Sie „Besondere Anforderungen / Hinweise“ sowie bei Catering „Ernährung & Unverträglichkeiten“.', 'help.contact': 'Conference Management kontaktieren', 'help.message': 'Ihre Frage oder Ihr Anliegen', 'help.send': 'Nachricht senden', 'help.sent': 'Ihre Nachricht wurde im MVP lokal simuliert.',
    'manager.heading': 'Manager Cockpit', 'manager.bookings': 'Buchungen', 'manager.roomPlan': 'Raumplanung', 'manager.reports': 'Reports', 'manager.admin': 'Administration', 'manager.confirm': 'Bestätigen', 'manager.change': 'Änderung anfordern', 'manager.reject': 'Ablehnen', 'manager.noRequests': 'Keine Anfragen zur Prüfung.', 'manager.filter': 'Filter', 'manager.search': 'Suche', 'manager.status': 'Status', 'manager.location': 'Standort', 'manager.allStatuses': 'Alle Status', 'manager.allLocations': 'Alle Standorte', 'manager.roomPlanDesc': 'Tagesübersicht der Raumbelegung.', 'manager.referenceDate': 'Bezugsdatum', 'manager.reportDesc': 'Operative Übersicht für den gewählten Zeitraum.', 'manager.confirmedBookings': 'Bestätigte Buchungen', 'manager.openRequests': 'Offene Anfragen', 'manager.cateringBookings': 'Buchungen mit Catering', 'manager.totalParticipants': 'Teilnehmende', 'manager.adminDesc': 'Räume, Services, Catering und Standortinformationen verwalten.', 'manager.rooms': 'Räume', 'manager.services': 'Services', 'manager.catering': 'Catering', 'manager.sites': 'Standorte', 'manager.addRoom': 'Raum hinzufügen', 'manager.addService': 'Service hinzufügen', 'manager.addItem': 'Einzeloption hinzufügen', 'manager.name': 'Bezeichnung', 'manager.capacity': 'Kapazität', 'manager.price': 'Preis', 'manager.equipment': 'Ausstattung', 'manager.active': 'Aktiv', 'manager.description': 'Beschreibung', 'manager.unit': 'Einheit', 'manager.address': 'Adresse', 'manager.publicTransport': 'ÖPNV-Anfahrt', 'manager.parking': 'Parken', 'manager.reception': 'Empfang / Zutritt', 'manager.accessibility': 'Barrierefreiheit', 'manager.contact': 'Kontakt', 'manager.saveCatalog': 'Stammdaten speichern', 'manager.saved': 'Stammdaten gespeichert.',

    'brand.internalServices': 'Interne Services', 'welcome.firstUseSubtitle': 'Planen Sie Ihre Veranstaltung – Raum, Services und Bewirtung in einer Anfrage.', 'progress.label': 'Schritt {step} von 6: {label}', 'progress.future': 'Bitte schließen Sie zuerst den aktuellen Schritt ab.', 'review.edit': 'Ändern', 'review.editAria': '{section} ändern', 'price.perRequest': 'pro Anfrage', 'cost.guidanceTitle': 'Kosten transparent prüfen', 'cost.guidance': 'Die angezeigten Raum- und Servicepreise werden einmal je Anfrage angesetzt. Bewirtung wird anhand Ihrer Paket-, Einzeloptionen- und Personenauswahl berechnet.', 'cost.centerTitle': 'Welche Kostenstelle soll ich angeben?', 'cost.centerHelp': 'Geben Sie die Kostenstelle ein, der die Veranstaltung belastet werden soll. Falls Sie sie nicht kennen, klären Sie sie vor dem Absenden mit Ihrem Team oder der zuständigen Kostenstellenverantwortung.', 'cost.centerPlaceholder': 'z. B. 471100', 'room.refreshAgain': 'Verfügbarkeit neu prüfen', 'catering.selectPackage': 'Auswählen', 'catering.selectPackageAria': '{package} auswählen', 'catering.packageGroupLabel': 'Catering-Paket auswählen', 'catering.packageLunch': 'Mittagessen', 'catering.tierBasic': 'Basis', 'catering.tierStandard': 'Standard', 'catering.tierDeluxe': 'Deluxe', 'catering.serviceTitle': 'Servicepersonal empfohlen', 'catering.serviceCopy': 'Bei Bewirtung kann {service} die Ausgabe und Betreuung während der Veranstaltung übernehmen.', 'catering.serviceAdd': 'Servicepersonal hinzufügen', 'submission.sentTitle': 'Anfrage erfolgreich gesendet', 'submission.sentText': 'Der Raum ist vorläufig reserviert. Das Conference Management prüft jetzt Raum, Zusatzleistungen, Bewirtung und Kosten.', 'submission.resubmittedTitle': 'Änderung erfolgreich eingereicht', 'submission.resubmittedText': 'Die aktualisierte Anfrage wurde erneut zur Prüfung eingereicht. Der Raum bleibt vorläufig reserviert.',

    'employee.accessibility.brandSubtitle': 'Konferenzservice', 'employee.accessibility.genericWelcome': 'Willkommen', 'employee.accessibility.profile': 'Profil', 'employee.accessibility.profileOpen': 'Profil öffnen', 'employee.accessibility.profileMissing': 'Nicht hinterlegt', 'employee.accessibility.firstUseSubtitle': 'Planen Sie Ihre Veranstaltung – Raum, Zusatzleistungen und Bewirtung in einer Anfrage.', 'employee.accessibility.requestSubtitle': 'Raum, Zusatzleistungen und Bewirtung in einer Anfrage.', 'employee.accessibility.welcomeServicesStep': 'Zusatzleistungen, Bewirtung und Einzeloptionen ergänzen.', 'employee.accessibility.additionalServices': 'Zusatzleistungen', 'employee.accessibility.additionalServicesOptional': 'Zusatzleistungen (optional)', 'employee.accessibility.additionalServicesEdit': 'Zusatzleistungen ändern', 'employee.accessibility.additionalServicesSelect': 'Zusatzleistungen auswählen', 'employee.accessibility.servicesDescription': 'Sie wählen nur die benötigte Leistung aus. Das Conference Management teilt anschließend die passende Person zu.', 'employee.accessibility.specialRequirementsHint': 'Nutzen Sie dieses Feld für Anforderungen, die nicht durch Raum, Zusatzleistungen oder Bewirtung abgedeckt werden.', 'employee.accessibility.participantInternal': 'Interne Teilnehmende', 'employee.accessibility.participantExternal': 'Externe Teilnehmende', 'employee.accessibility.participantRule': 'Bitte insgesamt mindestens eine Person angeben. Relevant für Raumkapazität und Bewirtung.', 'employee.accessibility.roomRecommendation': 'Empfohlen – passend für Ihre Teilnehmerzahl', 'employee.accessibility.cateringPeople': 'Bewirtung für wie viele Personen?', 'employee.accessibility.cateringSelect': 'Bewirtung auswählen', 'employee.accessibility.costServices': 'Zusatzleistungen', 'employee.accessibility.costGuidance': 'Die angezeigten Raumpreise und Preise für Zusatzleistungen werden einmal je Anfrage angesetzt. Bewirtung wird anhand Ihrer Paket-, Einzeloptionen- und Personenauswahl berechnet.', 'employee.accessibility.allocationCostCenter': 'Kostenstelle', 'employee.accessibility.allocationPercent': 'Anteil (%)', 'employee.accessibility.allocationAmount': 'Betrag', 'employee.accessibility.packageGroupLabel': 'Bewirtungspaket auswählen', 'employee.accessibility.packageMode': 'Bewirtungspaket', 'employee.accessibility.packageExtrasMode': 'Bewirtungspaket + Extras', 'employee.accessibility.reviewCatering': 'Bewirtungsdetails', 'employee.accessibility.reviewCateringEdit': 'Bewirtungsdetails ändern', 'employee.accessibility.reviewAfter2': 'Das Conference Management prüft Raum, Zusatzleistungen, Bewirtung und Kosten.', 'employee.accessibility.cateringTerm': 'Bewirtung', 'employee.accessibility.stepLabel': '{step}. {label}',
    'employee.personalization.welcomePageTitle': 'Start', 'employee.personalization.newRequestNav': 'Neue Konferenz', 'employee.personalization.serviceNone': 'Keine Zusatzleistungen benötigt? Sie können diesen Schritt ohne Auswahl fortsetzen.', 'employee.personalization.packageExtras': 'Bewirtungspaket + Einzeloptionen', 'employee.personalization.roomRefresh': 'Aktualisieren', 'employee.personalization.roomRefreshAria': 'Raumverfügbarkeit aktualisieren',

    'manager.experience.title': 'Conference Management', 'manager.experience.subtitle.bookings': 'Prüfen und steuern Sie offene Anfragen, heutige Veranstaltungen und kommende Buchungen.', 'manager.experience.subtitle.roomPlan': 'Behalten Sie die Raumbelegung für den gewählten Tag und Standort im Blick.', 'manager.experience.subtitle.reports': 'Analysieren Sie Buchungen, Auslastung, Services und Catering im gewählten Zeitraum.', 'manager.experience.subtitle.admin': 'Verwalten Sie Räume, Standorte, Services und Catering-Stammdaten.', 'manager.experience.firstUse.title': 'Neu im Conference Management?', 'manager.experience.firstUse.description': 'Starten Sie mit dem Handlungsbedarf. Öffnen Sie eine Anfrage, prüfen Sie alle relevanten Angaben und treffen Sie anschließend Ihre Entscheidung.', 'manager.experience.firstUse.step1': '1. Handlungsbedarf priorisieren', 'manager.experience.firstUse.step2': '2. Anfrage vollständig prüfen', 'manager.experience.firstUse.step3': '3. Bestätigen, Änderung anfordern oder ablehnen', 'manager.experience.firstUse.dismiss': 'Verstanden', 'manager.experience.moreFilters': 'Weitere Filter', 'manager.experience.filterHint': 'Suche, Status und Standort', 'manager.experience.noServices': 'Keine zusätzlichen Services', 'manager.experience.noCostCenters': 'Keine Kostenstellen angegeben', 'manager.experience.notStored': 'Nicht gespeichert', 'manager.experience.noInformation': 'Keine Angaben', 'manager.experience.event': 'Veranstaltung', 'manager.experience.requester': 'Anfragende Person', 'manager.experience.requesterFallback': 'Im MVP aus dem lokalen Demo-Profil angezeigt.', 'manager.experience.scheduleRoom': 'Termin & Raum', 'manager.experience.cateringRequirements': 'Catering & Anforderungen', 'manager.experience.keyDetails': 'Kerndaten', 'manager.experience.confirmBinding': 'Verbindlich bestätigen', 'manager.experience.confirmTitle': 'Buchung verbindlich bestätigen?', 'manager.experience.confirmDescription': 'Prüfen Sie die Kerndaten noch einmal. Die bestehende Bestätigungslogik bleibt unverändert.', 'manager.experience.reviewTitle': 'Anfrage prüfen · {id}', 'manager.experience.reviewDescription': 'Prüfen Sie die Angaben vollständig, bevor Sie eine Entscheidung treffen.', 'manager.experience.reviewAction': 'Prüfen & entscheiden', 'manager.experience.detailsAction': 'Details ansehen',
    'manager.ux.navManager': 'Conference Management', 'manager.ux.navRequests': 'Meine Buchungen', 'manager.ux.firstUseDescription': 'Starten Sie mit offenen Anfragen. Prüfen Sie die Angaben vollständig und treffen Sie anschließend Ihre Entscheidung.', 'manager.ux.firstUseStep1': '1. Offene Anfragen priorisieren', 'manager.ux.howItWorks': 'So funktioniert es', 'manager.ux.openRequests': 'Offene Anfragen', 'manager.ux.reviewNow': 'Jetzt prüfen', 'manager.ux.noOpenRequests': 'Keine offenen Anfragen.', 'manager.ux.searchDescriptor': 'Suche: {value}', 'manager.ux.statusDescriptor': 'Status: {value}', 'manager.ux.locationDescriptor': 'Standort: {value}', 'manager.ux.filterCountOne': '1 Filter aktiv', 'manager.ux.filterCountMany': '{count} Filter aktiv', 'manager.ux.activeFilters': 'Aktive Filter', 'manager.ux.resetFilters': 'Alle Filter zurücksetzen', 'manager.ux.noMatches': 'Keine Buchungen passen zu den aktuellen Filtern.', 'manager.ux.requester': 'Anfragende Person', 'manager.ux.requesterMissing': 'Nicht in der Anfrage gespeichert', 'manager.ux.requesterMissingNote': 'Für diese Anfrage wurde keine anfragende Person gespeichert.', 'manager.ux.confirmDescription': 'Mit der Bestätigung wird die Anfrage bestätigt und der Raum verbindlich als belegt geführt.', 'manager.ux.tentative': 'Vorläufig reserviert',
    'manager.final.calendarTentative': 'Vorläufig reserviert', 'manager.final.calendarBusy': 'Verbindlich belegt', 'manager.final.calendarReleased': 'Freigegeben', 'manager.final.notSpecified': 'Nicht angegeben', 'manager.final.decisionRequired': 'Entscheidung erforderlich', 'manager.final.noDecisionRequired': 'Keine Entscheidung erforderlich', 'manager.final.request': 'Anfrage', 'manager.final.room': 'Raum', 'manager.final.nextStep': 'Nächster Schritt', 'manager.final.closeReview': 'Prüfansicht schließen', 'manager.final.open': 'Öffnen', 'manager.final.noUpcoming': 'Keine weiteren Buchungen in den nächsten 7 Tagen.',
    'manager.ready.bookingsTab': 'Anfragen & Buchungen', 'manager.ready.helpTitle': 'Hilfe zum Conference Management', 'manager.ready.help1Title': '1. Offene Anfragen zuerst', 'manager.ready.help1Text': 'Bearbeiten Sie zuerst Vorgänge mit „Zur Prüfung“ oder „In Prüfung“.', 'manager.ready.help2Title': '2. Anfrage und Raum getrennt lesen', 'manager.ready.help2Text': '„Vorläufig reserviert“ hält den Raum frei; verbindlich wird er erst nach Ihrer Bestätigung.', 'manager.ready.help3Title': '3. Vollständig prüfen', 'manager.ready.help3Text': 'Prüfen Sie Termin, Raum, Teilnehmende, Services, Catering, Anforderungen und Kosten.', 'manager.ready.help4Title': '4. Entscheidung treffen', 'manager.ready.help4Text': 'Bestätigen Sie die Anfrage, fordern Sie eine Änderung an oder lehnen Sie mit Begründung ab.', 'manager.ready.periodActive': 'Zeitraum: {value}', 'manager.ready.morePeriods': 'Weitere Zeiträume',

    'notification.received': 'Anfrage eingegangen', 'notification.receivedText': '{title} wurde zur Prüfung eingereicht.', 'notification.confirmed': 'Buchung bestätigt', 'notification.confirmedText': '{title} wurde bestätigt.', 'notification.change': 'Änderung angefordert', 'notification.rejected': 'Anfrage abgelehnt', 'notification.cancelled': 'Anfrage storniert', 'notification.resubmitted': 'Änderung eingereicht'
  },
  en: {}
};

const EN = {
  'app.title': 'Conference Manager', 'app.internalServices': 'Internal Services', 'app.mvp': 'MVP · calendar integration simulated',
  'nav.welcome': 'Welcome', 'nav.newRequest': 'New request', 'nav.myRequests': 'My requests', 'nav.manager': 'Manager cockpit', 'nav.profile': 'Profile',
  'common.back': 'Back', 'common.next': 'Next', 'common.close': 'Close', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit', 'common.none': 'None', 'common.optional': 'optional', 'common.yes': 'Yes', 'common.no': 'No', 'common.today': 'Today', 'common.all': 'All', 'common.active': 'Active', 'common.past': 'Past', 'common.person': 'person',
  'a11y.skip': 'Skip to main content', 'a11y.mainNav': 'Main navigation', 'a11y.steps': 'Conference request steps', 'a11y.step': 'Step {step} of 6: {label}', 'a11y.loggedIn': 'Signed-in user {name}', 'a11y.availableRooms': 'Available rooms', 'a11y.services': 'Choose services', 'a11y.catering': 'Choose catering', 'a11y.roomSelect': 'Select room', 'a11y.selected': 'Selected', 'a11y.unavailable': 'Unavailable', 'a11y.serviceAdd': 'Add {name}', 'a11y.serviceRemove': 'Remove {name}', 'a11y.quantityDecrease': 'Decrease {name}', 'a11y.quantityIncrease': 'Increase {name}', 'a11y.costCenter': 'Cost center {index}', 'a11y.costPercent': 'Percentage for cost center {index}', 'a11y.removeCostCenter': 'Remove cost center {index}',
  'welcome.greeting': 'Welcome, {name}.', 'welcome.subtitle': 'Plan a conference or keep track of your existing bookings.', 'welcome.new': 'Request a new conference', 'welcome.bookings': 'View my bookings', 'welcome.open': 'Open requests', 'welcome.upcoming': 'Upcoming bookings', 'welcome.today': 'Today', 'welcome.next': 'Next confirmed booking', 'welcome.none': 'No upcoming confirmed booking yet.', 'welcome.noneText': 'Start a new request or review your open items.', 'welcome.how': 'How it works', 'welcome.s1': 'Schedule & room', 'welcome.s1d': 'Choose a date, participants and a suitable room.', 'welcome.s2': 'Choose services', 'welcome.s2d': 'Add services, catering and individual items.', 'welcome.s3': 'Submit request', 'welcome.s3d': 'The room is provisionally held and reviewed by Conference Management.', 'welcome.s4': 'Confirmation & guest info', 'welcome.s4d': 'After confirmation, booking details and guest information are available.', 'welcome.notifications': 'Recent updates', 'welcome.noNotifications': 'No notifications yet.',
  'profile.title': 'Profile', 'profile.first': 'First name', 'profile.last': 'Last name', 'profile.role': 'Role', 'profile.role.employee': 'Employee', 'profile.role.manager': 'Conference Manager', 'profile.demo': 'Demo: switch role', 'profile.demoNote': 'Demo only. In production, the role is provided by SSO and permissions.', 'profile.language': 'Language', 'profile.languageNote': 'Additional languages can be added later.', 'profile.help': 'Help & contact', 'profile.logout': 'Logout', 'profile.logoutMvp': 'Logout is simulated in the MVP. Production logout will use SSO.',
  'request.heading': 'New conference request', 'request.subtitle': 'Room, services and catering in one request.', 'request.step.schedule': 'Schedule', 'request.step.room': 'Room', 'request.step.services': 'Services', 'request.step.catering': 'Catering', 'request.step.costs': 'Costs', 'request.step.review': 'Review',
  'schedule.heading': 'Schedule and purpose', 'schedule.desc': 'These details are used to check availability.', 'schedule.title': 'Title', 'schedule.location': 'Location', 'schedule.date': 'Date', 'schedule.internal': 'Internal participants', 'schedule.external': 'External participants', 'schedule.start': 'Start', 'schedule.end': 'End', 'schedule.total': 'Total', 'schedule.totalHint': 'Relevant for room capacity and catering', 'schedule.special': 'Special requirements / notes', 'schedule.specialPlaceholder': 'e.g. U-shape seating, preparation from 08:30, special access requirements', 'schedule.specialHint': 'Use this field for requirements not covered by room, services or catering.', 'schedule.locationPlaceholder': 'Select location', 'schedule.titlePlaceholder': 'e.g. Management workshop', 'schedule.participantPlaceholder': 'Enter number',
  'room.heading': 'Available rooms', 'room.desc': 'Shown by calendar availability, location and capacity.', 'room.refresh': 'Check availability', 'room.refreshHint': 'Availability is checked when this step opens and again when you submit.', 'room.available': 'Available', 'room.busy': 'Occupied', 'room.cost': 'Room cost', 'room.capacity': 'Capacity {capacity} · {needed} needed', 'room.reserve': '{count} seats spare', 'room.bestFit': 'Best capacity fit', 'room.noLocation': 'No rooms are available at this location.', 'room.noCapacity': 'No room has sufficient capacity. The largest room has {capacity} seats.', 'room.noFree': 'Suitable rooms are already occupied during the selected time.', 'room.changeSchedule': 'Change schedule', 'room.changeParticipants': 'Change participant count', 'room.contact': 'Contact Conference Management', 'room.floorplan': 'View room layout', 'room.floor': 'Floor', 'room.entrance': 'Entrance', 'room.table': 'Meeting table', 'room.screen': 'Display / screen', 'room.presentation': 'Presentation',
  'services.heading': 'Staff & services', 'services.desc': 'The specific person will be assigned later by Conference Management.', 'services.none': 'No additional services needed? You can continue without selecting anything.', 'services.recommended': 'Recommended for your event', 'services.hostHint': 'Useful for external guests', 'services.avHint': 'Suitable for hybrid events', 'services.itHint': 'Suitable for technically demanding meetings', 'services.staffHint': 'Useful with catering',
  'catering.heading': 'Catering', 'catering.desc': 'Choose the type of catering you need.', 'catering.mode.none': 'No catering', 'catering.mode.package': 'Catering package', 'catering.mode.items': 'Individual items only', 'catering.mode.both': 'Package + extras', 'catering.people': 'Catering for how many people?', 'catering.peopleHint': 'The total participant count is used by default. Change it only if not everyone will join the catering.', 'catering.dietary': 'Dietary requirements & intolerances', 'catering.dietaryPlaceholder': 'e.g. 2× vegan, 1× gluten-free', 'catering.items': 'Individual items', 'catering.package': 'Package', 'catering.noPackage': 'No catering package', 'catering.noItems': 'No individual items', 'catering.noDietary': 'No dietary or intolerance information',
  'cost.heading': 'Estimated costs & allocation', 'cost.desc': 'Estimated costs are shown transparently before approval.', 'cost.room': 'Room', 'cost.services': 'Services', 'cost.catering': 'Catering', 'cost.total': 'Estimated total', 'cost.allocations': 'Cost allocation', 'cost.allocHint': 'The total must equal 100%.', 'cost.add': 'Add cost center', 'cost.costCenter': 'Cost center', 'cost.percent': 'Percentage', 'cost.help': 'Use the cost center that should be charged for the event.', 'cost.sum': 'Total: {sum}%', 'cost.note': 'Amounts are based on the current selection. Changes during review may affect the final amount.',
  'review.heading': 'Review request', 'review.desc': 'A final calendar check is performed when you submit.', 'review.schedule': 'Schedule', 'review.room': 'Room', 'review.services': 'Services', 'review.catering': 'Catering details', 'review.costs': 'Cost allocation', 'review.total': 'Estimated total cost', 'review.special': 'Special requirements', 'review.after': 'What happens after submitting?', 'review.after1': 'The selected room is provisionally reserved.', 'review.after2': 'Conference Management reviews room, services, catering and costs.', 'review.after3': 'You receive a confirmation or a change request.', 'review.after4': 'Guest information is available after confirmation.', 'review.provisional': 'Room will be provisionally reserved', 'review.provisionalText': 'After submitting, we initially hold the selected room for you. The booking becomes binding once Conference Management confirms your request.', 'review.submit': 'Submit request', 'review.resubmit': 'Resubmit changes',
  'draft.saved': 'Draft saved.', 'draft.autosaved': 'Draft autosaved · {time}', 'draft.continue': 'Continue draft', 'draft.delete': 'Delete draft', 'draft.restored': 'Draft restored.', 'draft.copiedPast': 'The previous details were copied. The original date is in the past — please choose a new schedule.', 'draft.copied': 'The details were copied into a new request.',
  'validation.heading': 'Please review one more field', 'validation.title': 'Please enter a title.', 'validation.location': 'Please select a location.', 'validation.date': 'Please select a date.', 'validation.dateFuture': 'Please select today or a future date.', 'validation.start': 'Please select a start time.', 'validation.end': 'Please select a valid end time after the start time.', 'validation.negative': 'Participant counts cannot be negative or infinite.', 'validation.participantRange': 'Participant counts must be whole numbers between 0 and 500.', 'validation.participants': 'Please enter at least one participant.', 'validation.room': 'Please select an available room.', 'validation.roomChanged': 'The selected room no longer matches your request. Please select an available room again.', 'validation.roomBusy': 'The selected room is now occupied during the selected time. Please choose another room.', 'validation.centers': 'Please complete all cost centers.', 'validation.percentRange': 'Each cost allocation must be between 0% and 100%.', 'validation.alloc': 'Cost allocations must total 100%.',
  'requests.heading': 'My requests', 'requests.subtitle': 'Status and details of your conference requests.', 'requests.list': 'List', 'requests.calendar': 'Calendar', 'requests.none': 'No requests yet.', 'requests.details': 'View details', 'requests.guest': 'Guest information', 'requests.pdf': 'Welcome PDF', 'requests.cancel': 'Cancel request', 'requests.repeat': 'Request again', 'requests.repeatRejected': 'Create new request from these details', 'requests.editChange': 'Edit requested change', 'requests.action': 'Action required', 'requests.noAction': 'No action required', 'requests.provisional': 'The room is provisionally reserved. Conference Management is reviewing your request.', 'requests.confirmed': 'The booking is confirmed. Guest information is available.', 'requests.rejectedText': 'The request could not be confirmed.', 'requests.cancelledText': 'The reservation has been released.', 'requests.changeReason': 'Change reason', 'requests.rejectionReason': 'Reason for rejection',
  'status.Submitted': 'Pending review', 'status.In Review': 'In review', 'status.Confirmed': 'Confirmed', 'status.Rejected': 'Rejected', 'status.Change Requested': 'Change requested', 'status.Cancelled': 'Cancelled',
  'timeline.title': 'Booking history', 'timeline.Submitted': 'Request submitted', 'timeline.In Review': 'In review', 'timeline.Confirmed': 'Confirmed', 'timeline.Rejected': 'Rejected', 'timeline.Change Requested': 'Change requested', 'timeline.Cancelled': 'Cancelled', 'timeline.pending': 'Decision pending', 'timeline.open': 'Still open',
  'dialog.changeTitle': 'Request changes', 'dialog.rejectTitle': 'Reject request', 'dialog.reason': 'Reason', 'dialog.reasonPlaceholder': 'Describe the requested change for the employee', 'dialog.reasonRequired': 'Please provide a reason.', 'dialog.cancelTitle': 'Cancel request?', 'dialog.cancelText': 'The room reservation will be released.', 'dialog.cancelConfirm': 'Cancel request',
  'guest.title': 'Guest information', 'guest.subtitle': 'Everything you need for your visit.', 'guest.welcome': 'Welcome to “{title}”', 'guest.demo': 'The location and Wi-Fi data are mock data.', 'guest.scheduleRoom': 'Schedule & room', 'guest.address': 'Address & directions', 'guest.parking': 'Parking & arrival', 'guest.contact': 'Contact & accessibility', 'guest.route': 'Open route', 'guest.wifi': 'Guest Wi-Fi', 'guest.network': 'Network', 'guest.code': 'Wi-Fi code', 'guest.print': 'Print / Save as PDF', 'guest.askOrganizer': 'Please ask the organizer', 'guest.contactDefault': 'Conference Management',
  'help.title': 'Help & contact', 'help.subtitle': 'Answers to common questions about conference requests.', 'help.noRoom': 'No room available?', 'help.noRoomText': 'Check date, time, location and participant count. If no room is suitable, contact Conference Management.', 'help.cost': 'Which cost center?', 'help.costText': 'Use the cost center that should be charged for the event.', 'help.binding': 'When is the booking binding?', 'help.bindingText': 'After submitting, the room is provisionally reserved. The booking becomes binding only after confirmation by Conference Management.', 'help.special': 'Special requests?', 'help.specialText': 'Use “Special requirements / notes” and, for catering, “Dietary requirements & intolerances”.', 'help.contact': 'Contact Conference Management', 'help.message': 'Your question or request', 'help.send': 'Send message', 'help.sent': 'Your message was simulated locally in the MVP.',
  'manager.heading': 'Manager cockpit', 'manager.bookings': 'Bookings', 'manager.roomPlan': 'Room planning', 'manager.reports': 'Reports', 'manager.admin': 'Administration', 'manager.confirm': 'Confirm', 'manager.change': 'Request changes', 'manager.reject': 'Reject', 'manager.noRequests': 'No requests to review.', 'manager.filter': 'Filter', 'manager.search': 'Search', 'manager.status': 'Status', 'manager.location': 'Location', 'manager.allStatuses': 'All statuses', 'manager.allLocations': 'All locations', 'manager.roomPlanDesc': 'Daily overview of room occupancy.', 'manager.referenceDate': 'Reference date', 'manager.reportDesc': 'Operational overview for the selected period.', 'manager.confirmedBookings': 'Confirmed bookings', 'manager.openRequests': 'Open requests', 'manager.cateringBookings': 'Bookings with catering', 'manager.totalParticipants': 'Participants', 'manager.adminDesc': 'Manage rooms, services, catering and location information.', 'manager.rooms': 'Rooms', 'manager.services': 'Services', 'manager.catering': 'Catering', 'manager.sites': 'Locations', 'manager.addRoom': 'Add room', 'manager.addService': 'Add service', 'manager.addItem': 'Add individual item', 'manager.name': 'Name', 'manager.capacity': 'Capacity', 'manager.price': 'Price', 'manager.equipment': 'Equipment', 'manager.active': 'Active', 'manager.description': 'Description', 'manager.unit': 'Unit', 'manager.address': 'Address', 'manager.publicTransport': 'Public transport', 'manager.parking': 'Parking', 'manager.reception': 'Reception / access', 'manager.accessibility': 'Accessibility', 'manager.contact': 'Contact', 'manager.saveCatalog': 'Save master data', 'manager.saved': 'Master data saved.',

  'brand.internalServices': 'Internal Services', 'welcome.firstUseSubtitle': 'Plan your event – room, services and catering in one request.', 'progress.label': 'Step {step} of 6: {label}', 'progress.future': 'Please complete the current step first.', 'review.edit': 'Edit', 'review.editAria': 'Edit {section}', 'price.perRequest': 'per request', 'cost.guidanceTitle': 'Review costs transparently', 'cost.guidance': 'The displayed room and service prices are applied once per request. Catering is calculated from your package, item and participant selections.', 'cost.centerTitle': 'Which cost center should I enter?', 'cost.centerHelp': 'Enter the cost center that should be charged for the event. If you do not know it, clarify it with your team or the responsible cost-center owner before submitting.', 'cost.centerPlaceholder': 'e.g. 471100', 'room.refreshAgain': 'Check availability again', 'catering.selectPackage': 'Select', 'catering.selectPackageAria': 'Select {package}', 'catering.packageGroupLabel': 'Select catering package', 'catering.packageLunch': 'Lunch', 'catering.tierBasic': 'Basic', 'catering.tierStandard': 'Standard', 'catering.tierDeluxe': 'Deluxe', 'catering.serviceTitle': 'Service staff recommended', 'catering.serviceCopy': 'With catering, {service} can support serving and event service during your meeting.', 'catering.serviceAdd': 'Add service staff', 'submission.sentTitle': 'Request sent successfully', 'submission.sentText': 'The room is provisionally reserved. Conference Management will now review the room, additional services, catering and costs.', 'submission.resubmittedTitle': 'Changes submitted successfully', 'submission.resubmittedText': 'The updated request has been submitted for review again. The room remains provisionally reserved.',

  'employee.accessibility.brandSubtitle': 'Conference services', 'employee.accessibility.genericWelcome': 'Welcome', 'employee.accessibility.profile': 'Profile', 'employee.accessibility.profileOpen': 'Open profile', 'employee.accessibility.profileMissing': 'Not provided', 'employee.accessibility.firstUseSubtitle': 'Plan your event – room, additional services and catering in one request.', 'employee.accessibility.requestSubtitle': 'Room, additional services and catering in one request.', 'employee.accessibility.welcomeServicesStep': 'Add additional services, catering and individual items.', 'employee.accessibility.additionalServices': 'Additional services', 'employee.accessibility.additionalServicesOptional': 'Additional services (optional)', 'employee.accessibility.additionalServicesEdit': 'Edit additional services', 'employee.accessibility.additionalServicesSelect': 'Select additional services', 'employee.accessibility.servicesDescription': 'Select the service you need. Conference Management will then assign the appropriate person.', 'employee.accessibility.specialRequirementsHint': 'Use this field for requirements that are not covered by the room, additional services or catering.', 'employee.accessibility.participantInternal': 'Internal participants', 'employee.accessibility.participantExternal': 'External participants', 'employee.accessibility.participantRule': 'Enter at least one participant in total. This is used for room capacity and catering.', 'employee.accessibility.roomRecommendation': 'Recommended – suitable for your participant count', 'employee.accessibility.cateringPeople': 'Catering for how many people?', 'employee.accessibility.cateringSelect': 'Select catering', 'employee.accessibility.costServices': 'Additional services', 'employee.accessibility.costGuidance': 'The displayed room and additional-service prices are applied once per request. Catering is calculated from your package, item and participant selections.', 'employee.accessibility.allocationCostCenter': 'Cost center', 'employee.accessibility.allocationPercent': 'Share (%)', 'employee.accessibility.allocationAmount': 'Amount', 'employee.accessibility.packageGroupLabel': 'Select catering package', 'employee.accessibility.packageMode': 'Catering package', 'employee.accessibility.packageExtrasMode': 'Catering package + extras', 'employee.accessibility.reviewCatering': 'Catering details', 'employee.accessibility.reviewCateringEdit': 'Edit catering details', 'employee.accessibility.reviewAfter2': 'Conference Management reviews the room, additional services, catering and costs.', 'employee.accessibility.cateringTerm': 'Catering', 'employee.accessibility.stepLabel': '{step}. {label}',
  'employee.personalization.welcomePageTitle': 'Home', 'employee.personalization.newRequestNav': 'New request', 'employee.personalization.serviceNone': 'No additional services needed? You can continue without selecting anything.', 'employee.personalization.packageExtras': 'Catering package + individual items', 'employee.personalization.roomRefresh': 'Refresh', 'employee.personalization.roomRefreshAria': 'Refresh room availability',

  'manager.experience.title': 'Conference Management', 'manager.experience.subtitle.bookings': 'Review and manage open requests, today’s events and upcoming bookings.', 'manager.experience.subtitle.roomPlan': 'Keep track of room occupancy for the selected day and location.', 'manager.experience.subtitle.reports': 'Analyse bookings, utilisation, services and catering for the selected period.', 'manager.experience.subtitle.admin': 'Manage room, location, service and catering master data.', 'manager.experience.firstUse.title': 'New to Conference Management?', 'manager.experience.firstUse.description': 'Start with items that need attention. Open a request, review all relevant information and then make your decision.', 'manager.experience.firstUse.step1': '1. Prioritise action required', 'manager.experience.firstUse.step2': '2. Review the full request', 'manager.experience.firstUse.step3': '3. Confirm, request changes or reject', 'manager.experience.firstUse.dismiss': 'Got it', 'manager.experience.moreFilters': 'More filters', 'manager.experience.filterHint': 'Search, status and location', 'manager.experience.noServices': 'No additional services', 'manager.experience.noCostCenters': 'No cost centres provided', 'manager.experience.notStored': 'Not stored', 'manager.experience.noInformation': 'No information provided', 'manager.experience.event': 'Event', 'manager.experience.requester': 'Requester', 'manager.experience.requesterFallback': 'Shown from the local demo profile in the MVP.', 'manager.experience.scheduleRoom': 'Schedule & room', 'manager.experience.cateringRequirements': 'Catering & requirements', 'manager.experience.keyDetails': 'Key details', 'manager.experience.confirmBinding': 'Confirm booking', 'manager.experience.confirmTitle': 'Confirm booking as binding?', 'manager.experience.confirmDescription': 'Review the key details once more. The existing confirmation logic remains unchanged.', 'manager.experience.reviewTitle': 'Review request · {id}', 'manager.experience.reviewDescription': 'Review the complete request before making a decision.', 'manager.experience.reviewAction': 'Review & decide', 'manager.experience.detailsAction': 'View details',
  'manager.ux.navManager': 'Conference Management', 'manager.ux.navRequests': 'My bookings', 'manager.ux.firstUseDescription': 'Start with open requests. Review the information completely and then make your decision.', 'manager.ux.firstUseStep1': '1. Prioritise open requests', 'manager.ux.howItWorks': 'How it works', 'manager.ux.openRequests': 'Open requests', 'manager.ux.reviewNow': 'Review now', 'manager.ux.noOpenRequests': 'No open requests.', 'manager.ux.searchDescriptor': 'Search: {value}', 'manager.ux.statusDescriptor': 'Status: {value}', 'manager.ux.locationDescriptor': 'Location: {value}', 'manager.ux.filterCountOne': '1 filter active', 'manager.ux.filterCountMany': '{count} filters active', 'manager.ux.activeFilters': 'Active filters', 'manager.ux.resetFilters': 'Reset all filters', 'manager.ux.noMatches': 'No bookings match the current filters.', 'manager.ux.requester': 'Requester', 'manager.ux.requesterMissing': 'Not stored in the request', 'manager.ux.requesterMissingNote': 'No requester was stored for this request.', 'manager.ux.confirmDescription': 'Confirming approves the request and marks the room as bindingly occupied.', 'manager.ux.tentative': 'Provisionally reserved',
  'manager.final.calendarTentative': 'Provisionally reserved', 'manager.final.calendarBusy': 'Bindingly occupied', 'manager.final.calendarReleased': 'Released', 'manager.final.notSpecified': 'Not specified', 'manager.final.decisionRequired': 'Decision required', 'manager.final.noDecisionRequired': 'No decision required', 'manager.final.request': 'Request', 'manager.final.room': 'Room', 'manager.final.nextStep': 'Next step', 'manager.final.closeReview': 'Close review', 'manager.final.open': 'Open', 'manager.final.noUpcoming': 'No additional bookings in the next 7 days.',
  'manager.ready.bookingsTab': 'Requests & bookings', 'manager.ready.helpTitle': 'Conference Management help', 'manager.ready.help1Title': '1. Open requests first', 'manager.ready.help1Text': 'Start with items marked “Pending review” or “In review”.', 'manager.ready.help2Title': '2. Read request and room separately', 'manager.ready.help2Text': '“Provisionally reserved” holds the room; it becomes binding only after your confirmation.', 'manager.ready.help3Title': '3. Review completely', 'manager.ready.help3Text': 'Review schedule, room, participants, services, catering, requirements and costs.', 'manager.ready.help4Title': '4. Make a decision', 'manager.ready.help4Text': 'Confirm the request, request a change or reject it with a reason.', 'manager.ready.periodActive': 'Period: {value}', 'manager.ready.morePeriods': 'More time periods',

  'notification.received': 'Request received', 'notification.receivedText': '{title} was submitted for review.', 'notification.confirmed': 'Booking confirmed', 'notification.confirmedText': '{title} was confirmed.', 'notification.change': 'Change requested', 'notification.rejected': 'Request rejected', 'notification.cancelled': 'Request cancelled', 'notification.resubmitted': 'Changes submitted'
};
Object.assign(MESSAGES.en, EN);

const SUPPORTED = Object.freeze(['de', 'en']);
let currentLanguage = SUPPORTED.includes(readString(KEYS.language, 'de')) ? readString(KEYS.language, 'de') : 'de';

export function language() { return currentLanguage; }
export function locale() { return currentLanguage === 'en' ? 'en-GB' : 'de-DE'; }
export function supportedLanguages() { return [...SUPPORTED]; }

export function t(key, values = {}) {
  const template = MESSAGES[currentLanguage]?.[key] ?? MESSAGES.de[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, token) => String(values[token] ?? ''));
}

export function setLanguage(nextLanguage) {
  if (!SUPPORTED.includes(nextLanguage) || nextLanguage === currentLanguage) return;
  currentLanguage = nextLanguage;
  writeString(KEYS.language, nextLanguage);
  document.documentElement.lang = nextLanguage;
  window.dispatchEvent(new CustomEvent('conference-language-changed', { detail: { language: nextLanguage } }));
}

export function formatDate(value, options = { day: '2-digit', month: '2-digit', year: 'numeric' }) {
  if (!value) return '';
  const date = new Date(/^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T12:00:00` : value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(locale(), options).format(date);
}

export function formatDateTime(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(locale(), { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date);
}

export function formatTime(value) { return value || ''; }
export function formatMoney(value) { return new Intl.NumberFormat(locale(), { style: 'currency', currency: 'EUR' }).format(Number(value || 0)); }
export function formatNumber(value, options) { return new Intl.NumberFormat(locale(), options).format(Number(value || 0)); }

document.documentElement.lang = currentLanguage;
