import {
  CALENDAR_STATUS,
  REQUEST_STATUS,
  appendHistory,
  calculateCosts,
  cloneForRepeat,
  isRoomConflict,
  localTodayIso,
  requestTimeline,
  totalParticipants,
  validateAllocations,
  validateRequest,
  validateRoom,
  validateSchedule,
} from './core/domain.js';
import { loadCatalog, loadSiteInfo, localizedValue } from './core/catalog.js';
import { formatDate, formatDateTime, formatMoney, language, setLanguage, t } from './core/i18n.js';
import { KEYS, notificationRepository, readJson, readString, remove, requestRepository, writeJson, writeString } from './core/storage.js';
import { announce, button, clear, clearValidation, el, field, openDialog, safeHttpsUrl, setFieldInvalid, showToast, validationSummary } from './core/ui.js';

const APP_BUILD = '2026.08.22.40';
const appRoot = document.getElementById('app');
const navigationRoot = document.getElementById('primaryNavigation');
const titleRoot = document.getElementById('viewTitle');
const subtitleRoot = document.getElementById('viewSubtitle');
const profile = readJson(KEYS.profile, { firstName: 'Florian', lastName: 'Kreutzer' });
let catalog = loadCatalog();
let siteInfo = loadSiteInfo();
let draftTimer = null;

const emptyForm = () => ({ title: '', location: '', date: '', start: '', end: '', internalParticipants: '', externalParticipants: '', specialRequirements: '', dietaryRequirements: '', cateringParticipants: '' });
const state = {
  view: 'welcome', step: 1, form: emptyForm(), roomId: null, serviceIds: [], cateringMode: 'NONE', packageSelection: null,
  quantities: Object.fromEntries(catalog.cateringItems.map((item) => [item.id, 0])), allocations: [{ costCenter: '', percent: 100 }], editingRequestId: null,
  requestFilter: 'ACTIVE', requestDisplay: 'LIST', calendarReference: localTodayIso(), managerTab: 'BOOKINGS', managerSearch: '', managerStatus: 'ALL', managerLocation: 'ALL', roomPlanDate: localTodayIso(), adminTab: 'ROOMS'
};

const localized = (value) => localizedValue(value, language());
const requests = () => requestRepository.all();
const role = () => readString(KEYS.role, 'employee');
const isManager = () => role() === 'manager';
const fullName = () => `${profile.firstName || ''} ${profile.lastName || ''}`.trim();
const initials = () => `${profile.firstName?.[0] || ''}${profile.lastName?.[0] || ''}`.toUpperCase();
const currentRoom = () => catalog.rooms.find((room) => room.id === state.roomId) || null;

function selectedPackage() {
  if (!state.packageSelection) return null;
  const pack = catalog.cateringPackages.find((entry) => entry.id === state.packageSelection.packageId);
  const variant = pack?.variants.find((entry) => entry.tier === state.packageSelection.tier);
  return pack && variant ? { pack, variant } : null;
}

function cateringCount() {
  if (state.cateringMode === 'NONE') return 0;
  const manual = Number(state.form.cateringParticipants || 0);
  return manual > 0 ? manual : totalParticipants(state.form);
}

function costSummary() {
  const pack = selectedPackage();
  return calculateCosts({ room: currentRoom(), services: catalog.services, selectedServiceIds: state.serviceIds, cateringPackage: pack ? { pricePerPerson: pack.variant.pricePerPerson } : null, cateringParticipants: cateringCount(), items: catalog.cateringItems, quantities: state.quantities });
}

const localizedStatus = (status) => t(`status.${status}`);
function notify(key, request, values = {}) { const list = notificationRepository.all(); list.unshift({ id: crypto.randomUUID(), key, requestId: request?.id || null, values, at: new Date().toISOString() }); notificationRepository.save(list.slice(0, 30)); }
function notificationText(notification) { if (notification.key) { const title = t(`notification.${notification.key}`); const textKey = `notification.${notification.key}Text`; const text = t(textKey, notification.values || {}); return { title, text: text === textKey ? '' : text }; } return { title: notification.title || '', text: notification.text || '' }; }

function setView(view) { if (view === 'manager' && !isManager()) view = 'welcome'; state.view = view; render(); requestAnimationFrame(() => titleRoot?.focus()); }
function resetRequestState() { state.step = 1; state.form = emptyForm(); state.roomId = null; state.serviceIds = []; state.cateringMode = 'NONE'; state.packageSelection = null; state.quantities = Object.fromEntries(catalog.cateringItems.map((item) => [item.id, 0])); state.allocations = [{ costCenter: '', percent: 100 }]; state.editingRequestId = null; }
const activeRooms = () => catalog.rooms.filter((room) => room.active !== false);

function availableRoomModel() {
  const location = state.form.location;
  const participantCount = totalParticipants(state.form);
  const candidateBase = activeRooms().filter((room) => room.location === location);
  if (!location) return { type: 'empty', rooms: [] };
  if (!candidateBase.length) return { type: 'location', rooms: [] };
  const largestCapacity = Math.max(...candidateBase.map((room) => Number(room.capacity || 0)), 0);
  const capacityCandidates = candidateBase.filter((room) => Number(room.capacity || 0) >= participantCount);
  if (!capacityCandidates.length) return { type: 'capacity', rooms: [], largestCapacity };
  const currentRequests = requests();
  const freeRooms = capacityCandidates.filter((room) => !isRoomConflict(currentRequests, { roomId: room.id, date: state.form.date, start: state.form.start, end: state.form.end }, state.editingRequestId));
  if (!freeRooms.length && state.form.date && state.form.start && state.form.end) return { type: 'busy', rooms: [] };
  const sorted = [...capacityCandidates].sort((left, right) => {
    const leftBusy = isRoomConflict(currentRequests, { roomId: left.id, date: state.form.date, start: state.form.start, end: state.form.end }, state.editingRequestId);
    const rightBusy = isRoomConflict(currentRequests, { roomId: right.id, date: state.form.date, start: state.form.start, end: state.form.end }, state.editingRequestId);
    if (leftBusy !== rightBusy) return Number(leftBusy) - Number(rightBusy);
    return (Number(left.capacity) - participantCount) - (Number(right.capacity) - participantCount);
  });
  return { type: 'available', rooms: sorted };
}

function scheduleDraftSave() { clearTimeout(draftTimer); draftTimer = setTimeout(saveDraft, 650); }
function draftPayload() { return { savedAt: new Date().toISOString(), form: structuredClone(state.form), step: state.step, roomId: state.roomId, serviceIds: [...state.serviceIds], cateringMode: state.cateringMode, packageSelection: state.packageSelection ? structuredClone(state.packageSelection) : null, quantities: structuredClone(state.quantities), allocations: structuredClone(state.allocations) }; }
function saveDraft({ notifyUser = false } = {}) {
  if (state.editingRequestId) return;
  const draft = draftPayload();
  const meaningful = Boolean(draft.form.title || draft.form.location || draft.form.date || draft.form.start || draft.form.end || draft.form.internalParticipants || draft.form.externalParticipants || draft.form.specialRequirements || draft.roomId || draft.serviceIds.length || draft.packageSelection);
  if (!meaningful) return;
  writeJson(KEYS.draft, draft);
  if (notifyUser) showToast(t('draft.saved'));
  const status = document.getElementById('draftStatus');
  if (status) status.textContent = t('draft.autosaved', { time: new Intl.DateTimeFormat(language() === 'en' ? 'en-GB' : 'de-DE', { hour: '2-digit', minute: '2-digit' }).format(new Date()) });
}
function restoreDraft() { const draft = readJson(KEYS.draft, null); if (!draft) return; state.form = { ...emptyForm(), ...(draft.form || {}) }; state.step = Math.min(6, Math.max(1, Number(draft.step || 1))); state.roomId = draft.roomId || null; state.serviceIds = [...(draft.serviceIds || [])]; state.cateringMode = draft.cateringMode || 'NONE'; state.packageSelection = draft.packageSelection ? structuredClone(draft.packageSelection) : null; state.quantities = { ...Object.fromEntries(catalog.cateringItems.map((item) => [item.id, 0])), ...(draft.quantities || {}) }; state.allocations = structuredClone(draft.allocations?.length ? draft.allocations : [{ costCenter: '', percent: 100 }]); state.view = 'employee'; showToast(t('draft.restored')); render(); }

function inputControl(type, value, options = {}) { const input = el('input', { type, value: value ?? '', placeholder: options.placeholder || '', attrs: {} }); if (options.min !== undefined) input.min = String(options.min); if (options.max !== undefined) input.max = String(options.max); if (options.step !== undefined) input.step = String(options.step); if (options.required) input.required = true; return input; }
function bindStateInput(control, key, { numeric = false, rerender = false } = {}) { const eventName = control.tagName === 'SELECT' ? 'change' : 'input'; control.addEventListener(eventName, () => { state.form[key] = numeric && control.value !== '' ? Number(control.value) : control.value; if (['internalParticipants', 'externalParticipants'].includes(key) && !state.form.cateringParticipants) state.form.cateringParticipants = ''; scheduleDraftSave(); if (rerender) renderRequest(); }); }
function navButton(key, view) { const item = button(t(key), { className: `nav-item${state.view === view ? ' active' : ''}`, attrs: state.view === view ? { 'aria-current': 'page' } : {}, dataset: { view } }); item.addEventListener('click', () => setView(view)); return el('li', {}, item); }

function renderNavigation() {
  document.title = t('app.title');
  document.getElementById('skipLink').textContent = t('a11y.skip');
  document.getElementById('sidebar').setAttribute('aria-label', t('app.title'));
  document.getElementById('brandTitle').textContent = t('app.title');
  document.getElementById('brandSubtitle').textContent = t('app.internalServices');
  clear(navigationRoot);
  const list = el('ul', { className: 'nav-list' });
  list.append(navButton('nav.welcome', 'welcome'), navButton('nav.newRequest', 'employee'), navButton('nav.myRequests', 'requests'));
  if (isManager()) list.append(navButton('nav.manager', 'manager'));
  const profileButton = button(`${initials()} · ${t('nav.profile')}`, { className: 'nav-item', attrs: { 'aria-haspopup': 'dialog', 'aria-label': t('a11y.loggedIn', { name: fullName() }) } });
  profileButton.addEventListener('click', openProfile);
  list.append(el('li', {}, profileButton)); navigationRoot.appendChild(list); navigationRoot.setAttribute('aria-label', t('a11y.mainNav')); document.getElementById('sidebarFooter').textContent = t('app.mvp');
}
function setPageHeading(title, subtitle) { titleRoot.textContent = title; subtitleRoot.textContent = subtitle; }
function kpi(label, value) { return el('article', { className: 'kpi' }, [el('span', { text: label }), el('strong', { text: String(value) })]); }

function renderWelcome() {
  setPageHeading(t('nav.welcome'), t('welcome.subtitle'));
  const currentRequests = requests(); const today = localTodayIso(); const openCount = currentRequests.filter((request) => [REQUEST_STATUS.SUBMITTED, REQUEST_STATUS.IN_REVIEW, REQUEST_STATUS.CHANGE_REQUESTED].includes(request.status)).length; const upcoming = currentRequests.filter((request) => request.status === REQUEST_STATUS.CONFIRMED && request.date >= today); const next = [...upcoming].sort((a, b) => `${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`))[0];
  const hero = el('section', { className: 'welcome-hero', attrs: { 'aria-labelledby': 'welcomeHeading' } }); hero.append(el('p', { className: 'eyebrow', text: t('app.title') }), el('h2', { id: 'welcomeHeading', text: t('welcome.greeting', { name: profile.firstName }) }), el('p', { text: t('welcome.subtitle') }));
  const heroActions = el('div', { className: 'button-row' }); const newButton = button(t('welcome.new'), { className: 'primary' }); newButton.addEventListener('click', () => setView('employee')); const requestButton = button(t('welcome.bookings')); requestButton.addEventListener('click', () => setView('requests')); heroActions.append(newButton, requestButton); if (readJson(KEYS.draft, null)) { const draftButton = button(t('draft.continue')); draftButton.addEventListener('click', restoreDraft); heroActions.appendChild(draftButton); } hero.appendChild(heroActions);
  const overview = el('section', { className: 'dashboard-grid', attrs: { 'aria-label': t('welcome.open') } }); overview.append(kpi(t('welcome.open'), openCount), kpi(t('welcome.upcoming'), upcoming.length), kpi(t('welcome.today'), upcoming.filter((request) => request.date === today).length));
  const nextSection = el('section', { className: 'card' }, [el('h3', { text: t('welcome.next') })]); if (next) nextSection.append(el('p', { text: `${next.title} · ${formatDate(next.date)} · ${next.start}–${next.end}` }), el('p', { text: localized(catalog.rooms.find((room) => room.id === next.roomId)?.name || next.roomId) })); else nextSection.append(el('strong', { text: t('welcome.none') }), el('p', { text: t('welcome.noneText') }));
  const how = el('section', { className: 'card' }, [el('h3', { text: t('welcome.how') })]); const list = el('ol', { className: 'how-list' }); [[t('welcome.s1'), t('welcome.s1d')], [t('welcome.s2'), t('welcome.s2d')], [t('welcome.s3'), t('welcome.s3d')], [t('welcome.s4'), t('welcome.s4d')]].forEach(([heading, text]) => list.append(el('li', {}, [el('strong', { text: heading }), el('span', { text })]))); how.appendChild(list);
  const notifications = el('section', { className: 'card' }, [el('h3', { text: t('welcome.notifications') })]); const notificationList = notificationRepository.all().slice(0, 4); if (!notificationList.length) notifications.appendChild(el('p', { className: 'muted', text: t('welcome.noNotifications') })); else notificationList.forEach((notification) => { const text = notificationText(notification); notifications.append(el('article', { className: 'notification-card' }, [el('strong', { text: text.title }), text.text ? el('p', { text: text.text }) : null, el('small', { text: formatDateTime(notification.at) })])); }); appRoot.append(hero, overview, nextSection, how, notifications);
}

function renderStepper() { const labels = ['request.step.schedule', 'request.step.room', 'request.step.services', 'request.step.catering', 'request.step.costs', 'request.step.review']; const nav = el('nav', { className: 'stepper', attrs: { 'aria-label': t('a11y.steps') } }); const list = el('ol'); labels.forEach((key, index) => { const step = index + 1; const stepButton = button(`${step}. ${t(key)}`, { className: `step${state.step === step ? ' active' : ''}${state.step > step ? ' done' : ''}`, attrs: { 'aria-label': t('a11y.step', { step, label: t(key) }), ...(state.step === step ? { 'aria-current': 'step' } : {}) } }); stepButton.addEventListener('click', () => moveToStep(step)); list.append(el('li', {}, stepButton)); }); nav.appendChild(list); return nav; }
function validationForStep(step) { if (step === 1) return validateSchedule(state.form); if (step === 2) return validateRoom({ roomId: state.roomId, form: state.form, rooms: activeRooms(), requests: requests(), excludeRequestId: state.editingRequestId }); if (step === 5) return validateAllocations(state.allocations); return null; }
function showValidationError(error) { state.step = error.step; renderRequest(); const panel = document.querySelector(`[data-step-panel="${error.step}"]`); const message = t(error.key); validationSummary(panel, message); setFieldInvalid(error.field, true); const target = document.getElementById(error.field); if (target && !target.matches('input,select,textarea,button,a[href],[tabindex]')) target.tabIndex = -1; target?.focus(); announce(message, { assertive: true }); }
function moveToStep(targetStep) { if (targetStep > state.step) { const error = validationForStep(state.step); if (error) { showValidationError(error); return; } } clearValidation(); state.step = targetStep; renderRequest(); }

function renderRequest() {
  setPageHeading(state.editingRequestId ? t('requests.editChange') : t('request.heading'), t('request.subtitle')); clear(appRoot); appRoot.appendChild(renderStepper()); const panel = el('section', { className: 'card wizard-card', dataset: { stepPanel: String(state.step) } }); const renderers = [renderScheduleStep, renderRoomStep, renderServiceStep, renderCateringStep, renderCostStep, renderReviewStep]; panel.appendChild(renderers[state.step - 1]()); const actions = el('footer', { className: 'wizard-actions' }); if (state.step > 1) { const back = button(t('common.back')); back.addEventListener('click', () => moveToStep(state.step - 1)); actions.appendChild(back); } const spacer = el('span', { className: 'spacer' }); actions.appendChild(spacer); const draftStatus = el('span', { id: 'draftStatus', className: 'draft-status', attrs: { role: 'status', 'aria-live': 'polite' } }); actions.appendChild(draftStatus); if (state.step < 6) { const next = button(t('common.next'), { className: 'primary' }); next.addEventListener('click', () => moveToStep(state.step + 1)); actions.appendChild(next); } else { const submit = button(state.editingRequestId ? t('review.resubmit') : t('review.submit'), { className: 'primary' }); submit.addEventListener('click', submitRequest); actions.appendChild(submit); } panel.appendChild(actions); appRoot.appendChild(panel);
}
function sectionHeading(title, description) { return el('header', { className: 'section-heading' }, [el('h2', { text: title }), description ? el('p', { text: description }) : null]); }

function renderScheduleStep() {
  const fragment = document.createDocumentFragment(); fragment.appendChild(sectionHeading(t('schedule.heading'), t('schedule.desc'))); const grid = el('div', { className: 'form-grid two' }); const title = inputControl('text', state.form.title, { placeholder: t('schedule.titlePlaceholder'), required: true }); bindStateInput(title, 'title'); grid.appendChild(field({ id: 'title', label: t('schedule.title'), control: title, required: true })); const location = el('select'); location.append(el('option', { value: '', text: t('schedule.locationPlaceholder') })); [...new Set(activeRooms().map((room) => room.location))].sort().forEach((value) => location.append(el('option', { value, text: value }))); location.value = state.form.location; bindStateInput(location, 'location', { rerender: true }); grid.appendChild(field({ id: 'location', label: t('schedule.location'), control: location, required: true })); const date = inputControl('date', state.form.date, { required: true }); date.min = localTodayIso(); bindStateInput(date, 'date'); grid.appendChild(field({ id: 'date', label: t('schedule.date'), control: date, required: true })); const internal = inputControl('number', state.form.internalParticipants, { min: 0, placeholder: t('schedule.participantPlaceholder'), required: true }); bindStateInput(internal, 'internalParticipants', { numeric: true }); grid.appendChild(field({ id: 'internalParticipants', label: t('schedule.internal'), control: internal, required: true })); const start = inputControl('time', state.form.start, { required: true }); bindStateInput(start, 'start'); grid.appendChild(field({ id: 'start', label: t('schedule.start'), control: start, required: true })); const end = inputControl('time', state.form.end, { required: true }); bindStateInput(end, 'end'); grid.appendChild(field({ id: 'end', label: t('schedule.end'), control: end, required: true })); const external = inputControl('number', state.form.externalParticipants, { min: 0, placeholder: '0' }); bindStateInput(external, 'externalParticipants', { numeric: true }); grid.appendChild(field({ id: 'externalParticipants', label: t('schedule.external'), control: external })); const total = el('section', { className: 'participant-total', attrs: { 'aria-live': 'polite' } }, [el('span', { text: t('schedule.total') }), el('strong', { text: String(totalParticipants(state.form)) }), el('small', { text: t('schedule.totalHint') })]); grid.appendChild(total); fragment.appendChild(grid); const special = el('textarea', { value: state.form.specialRequirements, placeholder: t('schedule.specialPlaceholder') }); special.value = state.form.specialRequirements; bindStateInput(special, 'specialRequirements'); fragment.appendChild(field({ id: 'specialRequirements', label: t('schedule.special'), control: special, hint: t('schedule.specialHint'), optional: true })); return fragment;
}

function renderRoomStep() {
  const fragment = document.createDocumentFragment(); const heading = sectionHeading(t('room.heading'), t('room.desc')); const refresh = button(t('room.refresh')); refresh.addEventListener('click', renderRequest); heading.appendChild(refresh); fragment.appendChild(heading); fragment.appendChild(el('aside', { className: 'info-box', attrs: { role: 'note' }, text: t('room.refreshHint') })); const roomRoot = el('section', { id: 'rooms', className: 'selection-grid', attrs: { 'aria-label': t('a11y.availableRooms') } }); const model = availableRoomModel();
  if (model.type !== 'available') { const key = model.type === 'location' ? 'room.noLocation' : model.type === 'capacity' ? 'room.noCapacity' : model.type === 'busy' ? 'room.noFree' : 'validation.room'; const box = el('article', { className: 'recovery-card' }, [el('strong', { text: t(key, { capacity: model.largestCapacity || 0 }) })]); const actions = el('div', { className: 'button-row' }); const dateAction = button(t('room.changeSchedule')); dateAction.addEventListener('click', () => { state.step = 1; renderRequest(); requestAnimationFrame(() => document.getElementById('date')?.focus()); }); const peopleAction = button(t('room.changeParticipants')); peopleAction.addEventListener('click', () => { state.step = 1; renderRequest(); requestAnimationFrame(() => document.getElementById('internalParticipants')?.focus()); }); const helpAction = button(t('room.contact'), { className: 'primary' }); helpAction.addEventListener('click', openHelp); actions.append(dateAction, peopleAction, helpAction); box.appendChild(actions); roomRoot.appendChild(box); }
  else { const participantCount = totalParticipants(state.form); const smallestFreeCapacity = Math.min(...model.rooms.filter((room) => !isRoomConflict(requests(), { roomId: room.id, date: state.form.date, start: state.form.start, end: state.form.end }, state.editingRequestId)).map((room) => Number(room.capacity)), Infinity); model.rooms.forEach((room) => { const busy = isRoomConflict(requests(), { roomId: room.id, date: state.form.date, start: state.form.start, end: state.form.end }, state.editingRequestId); const selected = state.roomId === room.id; const card = el('article', { className: `option-card${selected ? ' selected' : ''}${busy ? ' disabled' : ''}` }); card.append(el('span', { className: `badge ${busy ? 'danger' : 'success'}`, text: busy ? t('room.busy') : t('room.available') }), el('h3', { text: localized(room.name) }), el('p', { text: t('room.capacity', { capacity: room.capacity, needed: participantCount }) }), el('p', { text: localized(room.equipment) }), el('strong', { className: 'price', text: `${formatMoney(room.rate)} · ${t('room.cost')}` })); if (!busy && Number(room.capacity) === smallestFreeCapacity) card.appendChild(el('span', { className: 'recommendation', text: t('room.bestFit') })); const actions = el('div', { className: 'button-row' }); const select = button(selected ? t('a11y.selected') : t('a11y.roomSelect'), { className: selected ? 'primary' : 'secondary', disabled: busy, attrs: { 'aria-pressed': String(selected) } }); select.addEventListener('click', () => { state.roomId = room.id; scheduleDraftSave(); renderRequest(); }); const plan = button(t('room.floorplan')); plan.addEventListener('click', () => openFloorplan(room)); actions.append(select, plan); card.appendChild(actions); roomRoot.appendChild(card); }); }
  fragment.appendChild(roomRoot); return fragment;
}

function openFloorplan(room) {
  const content = el('section', { className: 'floorplan-layout' }); const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('viewBox', '0 0 800 420'); svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', localized(room.name)); svg.classList.add('floorplan-svg'); const title = document.createElementNS(svg.namespaceURI, 'title'); title.textContent = localized(room.name); svg.appendChild(title); const addRect = (x, y, width, height, className) => { const node = document.createElementNS(svg.namespaceURI, 'rect'); Object.entries({ x, y, width, height }).forEach(([key, value]) => node.setAttribute(key, String(value))); node.setAttribute('class', className); svg.appendChild(node); }; const addText = (x, y, text, className) => { const node = document.createElementNS(svg.namespaceURI, 'text'); node.setAttribute('x', String(x)); node.setAttribute('y', String(y)); node.setAttribute('class', className); node.textContent = text; svg.appendChild(node); }; addRect(20, 20, 760, 380, 'fp-room'); addRect(170, 135, 330, 150, 'fp-table'); addText(335, 215, t('room.table'), 'fp-label'); addRect(570, 70, 150, 42, 'fp-screen'); addText(645, 98, t('room.screen'), 'fp-small'); addRect(575, 160, 140, 90, 'fp-presentation'); addText(645, 210, t('room.presentation'), 'fp-small'); addText(65, 370, t('room.entrance'), 'fp-small'); content.append(svg, el('dl', { className: 'details-list' }, [el('dt', { text: t('room.floor') }), el('dd', { text: localized(room.floor) }), el('dt', { text: t('manager.capacity') }), el('dd', { text: String(room.capacity) }), el('dt', { text: t('manager.equipment') }), el('dd', { text: localized(room.equipment) })])); const close = button(t('common.close'), { className: 'primary' }); const dialog = openDialog({ title: localized(room.name), content, actions: [close], labelledById: 'floorplanTitle' }); close.addEventListener('click', () => dialog.close());
}

function renderServiceStep() {
  const fragment = document.createDocumentFragment(); fragment.appendChild(sectionHeading(`${t('services.heading')} (${t('common.optional')})`, t('services.desc')), el('p', { className: 'muted', text: t('services.none') })); const grid = el('section', { className: 'selection-grid compact', attrs: { 'aria-label': t('a11y.services') } }); const external = Number(state.form.externalParticipants || 0); const withCatering = state.cateringMode !== 'NONE'; catalog.services.filter((service) => service.active !== false).forEach((service) => { const selected = state.serviceIds.includes(service.id); const card = el('article', { className: `option-card${selected ? ' selected' : ''}` }); const hintKey = service.id === 'host' ? 'services.hostHint' : service.id === 'av' ? 'services.avHint' : service.id === 'it' ? 'services.itHint' : 'services.staffHint'; const recommended = (service.id === 'host' && external > 0) || (service.id === 'service' && withCatering); card.append(el('h3', { text: localized(service.name) }), el('p', { text: localized(service.description) }), el('strong', { className: 'price', text: formatMoney(service.price) }), el('p', { className: recommended ? 'recommendation' : 'muted', text: recommended ? t('services.recommended') : t(hintKey) })); const select = button(selected ? t('a11y.serviceRemove', { name: localized(service.name) }) : t('a11y.serviceAdd', { name: localized(service.name) }), { className: selected ? 'primary' : 'secondary', attrs: { 'aria-pressed': String(selected) } }); select.addEventListener('click', () => { state.serviceIds = selected ? state.serviceIds.filter((id) => id !== service.id) : [...state.serviceIds, service.id]; scheduleDraftSave(); renderRequest(); }); card.appendChild(select); grid.appendChild(card); }); fragment.appendChild(grid); return fragment;
}

function renderCateringStep() {
  const fragment = document.createDocumentFragment(); fragment.appendChild(sectionHeading(`${t('catering.heading')} (${t('common.optional')})`, t('catering.desc'))); const modes = el('fieldset', { className: 'mode-selector' }); modes.appendChild(el('legend', { text: t('catering.desc') })); [['NONE', 'catering.mode.none'], ['PACKAGE', 'catering.mode.package'], ['ITEMS', 'catering.mode.items'], ['BOTH', 'catering.mode.both']].forEach(([value, key]) => { const label = el('label', { className: 'mode-option' }); const radio = inputControl('radio', ''); radio.name = 'cateringMode'; radio.value = value; radio.checked = state.cateringMode === value; radio.addEventListener('change', () => { state.cateringMode = value; if (value === 'NONE') { state.packageSelection = null; state.quantities = Object.fromEntries(catalog.cateringItems.map((item) => [item.id, 0])); } scheduleDraftSave(); renderRequest(); }); label.append(radio, el('span', { text: t(key) })); modes.appendChild(label); }); fragment.appendChild(modes); if (state.cateringMode === 'NONE') return fragment; const count = inputControl('number', state.form.cateringParticipants || totalParticipants(state.form), { min: 1, step: 1 }); bindStateInput(count, 'cateringParticipants', { numeric: true }); fragment.appendChild(field({ id: 'cateringParticipants', label: t('catering.people'), control: count, hint: t('catering.peopleHint') }));
  if (['PACKAGE', 'BOTH'].includes(state.cateringMode)) { const packageGrid = el('section', { className: 'package-grid', attrs: { 'aria-label': t('catering.package') } }); catalog.cateringPackages.forEach((pack) => pack.variants.forEach((variant) => { const selected = state.packageSelection?.packageId === pack.id && state.packageSelection?.tier === variant.tier; const card = el('article', { className: `option-card${selected ? ' selected' : ''}` }, [el('h3', { text: `${localized(pack.name)} · ${variant.tier}` }), el('p', { text: localized(variant.description) }), el('strong', { className: 'price', text: `${formatMoney(variant.pricePerPerson)} / ${t('common.person')} · ${formatMoney(Number(variant.pricePerPerson) * cateringCount())}` })]); const select = button(selected ? t('a11y.selected') : t('common.edit'), { className: selected ? 'primary' : 'secondary', attrs: { 'aria-pressed': String(selected) } }); select.addEventListener('click', () => { state.packageSelection = selected ? null : { packageId: pack.id, tier: variant.tier }; scheduleDraftSave(); renderRequest(); }); card.appendChild(select); packageGrid.appendChild(card); })); fragment.appendChild(packageGrid); }
  if (['ITEMS', 'BOTH'].includes(state.cateringMode)) { fragment.appendChild(el('h3', { text: t('catering.items') })); const itemList = el('section', { className: 'item-list', attrs: { 'aria-label': t('catering.items') } }); catalog.cateringItems.filter((item) => item.active !== false).forEach((item) => { const quantity = Number(state.quantities[item.id] || 0); const row = el('article', { className: 'item-row' }, [el('div', {}, [el('strong', { text: localized(item.name) }), el('small', { text: `${formatMoney(item.price)} / ${localized(item.unit)}` })])]); const controls = el('div', { className: 'quantity-control' }); const decrease = button('−', { attrs: { 'aria-label': t('a11y.quantityDecrease', { name: localized(item.name) }) } }); decrease.disabled = quantity <= 0; decrease.addEventListener('click', () => { state.quantities[item.id] = Math.max(0, quantity - 1); scheduleDraftSave(); renderRequest(); }); const amount = el('strong', { text: String(quantity), attrs: { 'aria-live': 'polite' } }); const increase = button('+', { attrs: { 'aria-label': t('a11y.quantityIncrease', { name: localized(item.name) }) } }); increase.addEventListener('click', () => { state.quantities[item.id] = quantity + 1; scheduleDraftSave(); renderRequest(); }); controls.append(decrease, amount, increase); row.append(controls, el('strong', { text: formatMoney(quantity * Number(item.price)) })); itemList.appendChild(row); }); fragment.appendChild(itemList); }
  const dietary = el('textarea', { placeholder: t('catering.dietaryPlaceholder') }); dietary.value = state.form.dietaryRequirements; bindStateInput(dietary, 'dietaryRequirements'); fragment.appendChild(field({ id: 'dietaryRequirements', label: t('catering.dietary'), control: dietary, optional: true })); return fragment;
}

function renderCostStep() {
  const fragment = document.createDocumentFragment(); fragment.appendChild(sectionHeading(t('cost.heading'), t('cost.desc'))); const costs = costSummary(); const summary = el('section', { className: 'cost-summary' }); [[t('cost.room'), costs.roomCost], [t('cost.services'), costs.serviceCost], [t('cost.catering'), costs.cateringCost], [t('cost.total'), costs.total]].forEach(([label, value], index) => summary.append(el('article', { className: index === 3 ? 'total' : '' }, [el('span', { text: label }), el('strong', { text: formatMoney(value) })]))); fragment.append(summary, el('p', { className: 'muted', text: t('cost.help') })); const header = el('header', { className: 'allocation-header' }, [el('div', {}, [el('h3', { text: t('cost.allocations') }), el('p', { text: t('cost.allocHint') })])]); const add = button(t('cost.add')); add.addEventListener('click', () => { state.allocations.push({ costCenter: '', percent: 0 }); scheduleDraftSave(); renderRequest(); }); header.appendChild(add); fragment.appendChild(header); const allocations = el('section', { id: 'allocations', className: 'allocations' }); state.allocations.forEach((allocation, index) => { const row = el('article', { className: 'allocation-row' }); const cc = inputControl('text', allocation.costCenter, { placeholder: t('cost.costCenter') }); cc.id = `allocation-cost-center-${index}`; cc.setAttribute('aria-label', t('a11y.costCenter', { index: index + 1 })); cc.addEventListener('input', () => { state.allocations[index].costCenter = cc.value; scheduleDraftSave(); }); const pct = inputControl('number', allocation.percent, { min: 0, max: 100, step: 1 }); pct.id = `allocation-percent-${index}`; pct.setAttribute('aria-label', t('a11y.costPercent', { index: index + 1 })); pct.addEventListener('input', () => { state.allocations[index].percent = Number(pct.value || 0); scheduleDraftSave(); }); const amount = el('output', { text: formatMoney(costs.total * Number(allocation.percent || 0) / 100) }); row.append(cc, pct, amount); if (state.allocations.length > 1) { const removeButton = button('×', { attrs: { 'aria-label': t('a11y.removeCostCenter', { index: index + 1 }) } }); removeButton.addEventListener('click', () => { state.allocations.splice(index, 1); scheduleDraftSave(); renderRequest(); }); row.appendChild(removeButton); } allocations.appendChild(row); }); fragment.appendChild(allocations); const sum = state.allocations.reduce((total, allocation) => total + Number(allocation.percent || 0), 0); fragment.append(el('p', { className: Math.abs(sum - 100) < 0.01 ? 'validation-ok' : 'validation-bad', text: t('cost.sum', { sum: sum.toFixed(0) }), attrs: { role: 'status', 'aria-live': 'polite' } }), el('p', { className: 'muted', text: t('cost.note') })); return fragment;
}

function renderReviewStep() {
  const fragment = document.createDocumentFragment(); fragment.appendChild(sectionHeading(t('review.heading'), t('review.desc'))); const grid = el('section', { className: 'review-grid' }); const room = currentRoom(); const pack = selectedPackage(); const selectedServices = catalog.services.filter((service) => state.serviceIds.includes(service.id)); const selectedItems = catalog.cateringItems.filter((item) => Number(state.quantities[item.id] || 0) > 0); const costs = costSummary(); grid.append(reviewCard(t('review.schedule'), [`${state.form.title}`, `${formatDate(state.form.date)} · ${state.form.start}–${state.form.end}`, `${totalParticipants(state.form)} · ${state.form.location}`]), reviewCard(t('review.room'), [localized(room?.name || ''), localized(room?.equipment || '')]), reviewCard(t('review.services'), [selectedServices.length ? selectedServices.map((service) => localized(service.name)).join(' · ') : t('common.none')]), reviewCard(t('review.catering'), [pack ? `${localized(pack.pack.name)} · ${pack.variant.tier}` : t('catering.noPackage'), selectedItems.length ? selectedItems.map((item) => `${state.quantities[item.id]}× ${localized(item.name)}`).join(' · ') : t('catering.noItems'), state.cateringMode !== 'NONE' ? `${cateringCount()} · ${state.form.dietaryRequirements || t('catering.noDietary')}` : '']), reviewCard(t('review.costs'), state.allocations.map((allocation) => `${allocation.costCenter} · ${allocation.percent}%`)), reviewCard(t('review.total'), [formatMoney(costs.total)])); if (state.form.specialRequirements) grid.appendChild(reviewCard(t('review.special'), [state.form.specialRequirements])); fragment.appendChild(grid); const after = el('section', { className: 'info-box' }, [el('h3', { text: t('review.after') })]); const list = el('ol'); ['review.after1', 'review.after2', 'review.after3', 'review.after4'].forEach((key) => list.append(el('li', { text: t(key) }))); after.appendChild(list); fragment.append(after, el('aside', { className: 'tentative-box', attrs: { role: 'note' } }, [el('strong', { text: t('review.provisional') }), el('p', { text: t('review.provisionalText') })])); return fragment;
}
function reviewCard(title, lines) { const card = el('article', { className: 'review-card' }, [el('h3', { text: title })]); lines.filter(Boolean).forEach((line) => card.appendChild(el('p', { text: line }))); return card; }

function submitRequest() {
  const error = validateRequest({ roomId: state.roomId, form: state.form, rooms: activeRooms(), requests: requests(), allocations: state.allocations, excludeRequestId: state.editingRequestId, today: localTodayIso() }); if (error) { showValidationError(error); return; } const pack = selectedPackage(); const costs = costSummary(); const now = new Date().toISOString();
  if (state.editingRequestId) { requestRepository.update((list) => list.map((request) => { if (request.id !== state.editingRequestId) return request; const updated = { ...request, ...requestData(pack, costs), status: REQUEST_STATUS.SUBMITTED, calendarStatus: CALENDAR_STATUS.PROVISIONAL, resubmittedAt: now, updatedAt: now }; return appendHistory(updated, REQUEST_STATUS.SUBMITTED, '', now); })); const request = requests().find((entry) => entry.id === state.editingRequestId); if (request) notify('resubmitted', request, { title: request.title }); }
  else { const id = `CR-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`; let request = { id, ...requestData(pack, costs), status: REQUEST_STATUS.SUBMITTED, calendarStatus: CALENDAR_STATUS.PROVISIONAL, createdAt: now, updatedAt: now, statusHistory: [] }; request = appendHistory(request, REQUEST_STATUS.SUBMITTED, '', now); requestRepository.save([request, ...requests()]); notify('received', request, { title: request.title }); }
  remove(KEYS.draft); resetRequestState(); state.view = 'requests'; showToast(t('notification.received')); render();
}
function requestData(pack, costs) { return { title: String(state.form.title).trim(), location: state.form.location, date: state.form.date, start: state.form.start, end: state.form.end, participants: totalParticipants(state.form), internalParticipants: Number(state.form.internalParticipants || 0), externalParticipants: Number(state.form.externalParticipants || 0), specialRequirements: String(state.form.specialRequirements || '').trim(), dietaryRequirements: String(state.form.dietaryRequirements || '').trim(), cateringParticipants: cateringCount(), roomId: state.roomId, serviceIds: [...state.serviceIds], packageSelection: pack ? { packageId: pack.pack.id, packageName: localized(pack.pack.name), tier: pack.variant.tier, pricePerPerson: Number(pack.variant.pricePerPerson) } : null, quantities: structuredClone(state.quantities), allocations: structuredClone(state.allocations), estimatedCost: costs.total }; }

function requestMatchesFilter(request) { if (state.requestFilter === 'ALL') return true; if (state.requestFilter === 'PAST') return request.date < localTodayIso(); return request.date >= localTodayIso() && ![REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED].includes(request.status); }
function renderRequests() { setPageHeading(t('requests.heading'), t('requests.subtitle')); const current = requests().filter(requestMatchesFilter); const tools = el('section', { className: 'toolbar' }); const filters = el('div', { className: 'segmented', attrs: { 'aria-label': t('manager.filter') } }); [['ACTIVE', 'common.active'], ['PAST', 'common.past'], ['ALL', 'common.all']].forEach(([value, key]) => { const control = button(t(key), { attrs: { 'aria-pressed': String(state.requestFilter === value) } }); control.addEventListener('click', () => { state.requestFilter = value; renderRequestsViewOnly(); }); filters.appendChild(control); }); const displays = el('div', { className: 'segmented' }); [['LIST', 'requests.list'], ['CALENDAR', 'requests.calendar']].forEach(([value, key]) => { const control = button(t(key), { attrs: { 'aria-pressed': String(state.requestDisplay === value) } }); control.addEventListener('click', () => { state.requestDisplay = value; renderRequestsViewOnly(); }); displays.appendChild(control); }); tools.append(filters, displays); appRoot.appendChild(tools); if (state.requestDisplay === 'CALENDAR') appRoot.appendChild(renderRequestCalendar(current)); else appRoot.appendChild(renderRequestList(current)); }
function renderRequestsViewOnly() { clear(appRoot); renderRequests(); }
function renderRequestList(list) { const section = el('section', { className: 'request-list' }); if (!list.length) { section.appendChild(el('p', { className: 'info-box', text: t('requests.none') })); return section; } list.forEach((request) => section.appendChild(requestCard(request, false))); return section; }

function requestCard(request, manager) {
  const room = catalog.rooms.find((entry) => entry.id === request.roomId); const card = el('article', { className: `request-card status-${request.status.toLowerCase().replaceAll(' ', '-')}` }); const header = el('header', { className: 'request-card-header' }, [el('div', {}, [el('h3', { text: request.title }), el('p', { className: 'muted', text: `${request.id} · ${formatDate(request.date)} · ${request.start}–${request.end}` })]), el('span', { className: 'status-badge', text: localizedStatus(request.status) })]); card.appendChild(header); const grid = el('dl', { className: 'request-grid' }); [[t('review.room'), localized(room?.name || request.roomId || '')], [t('schedule.total'), String(request.participants ?? totalParticipants(request))], [t('cost.total'), formatMoney(request.estimatedCost || 0)]].forEach(([term, value]) => grid.append(el('div', {}, [el('dt', { text: term }), el('dd', { text: value })]))); card.appendChild(grid);
  if (!manager) { const guidance = el('aside', { className: request.status === REQUEST_STATUS.CHANGE_REQUESTED ? 'state-guidance action-required' : 'state-guidance' }); if ([REQUEST_STATUS.SUBMITTED, REQUEST_STATUS.IN_REVIEW].includes(request.status)) guidance.append(el('strong', { text: t('requests.noAction') }), el('p', { text: t('requests.provisional') })); if (request.status === REQUEST_STATUS.CHANGE_REQUESTED) guidance.append(el('strong', { text: t('requests.action') }), el('p', { text: `${t('requests.changeReason')}: ${request.changeReason || ''}` })); if (request.status === REQUEST_STATUS.CONFIRMED) guidance.append(el('strong', { text: localizedStatus(request.status) }), el('p', { text: t('requests.confirmed') })); if (request.status === REQUEST_STATUS.REJECTED) guidance.append(el('strong', { text: localizedStatus(request.status) }), el('p', { text: request.rejectionReason ? `${t('requests.rejectionReason')}: ${request.rejectionReason}` : t('requests.rejectedText') })); if (request.status === REQUEST_STATUS.CANCELLED) guidance.append(el('strong', { text: localizedStatus(request.status) }), el('p', { text: t('requests.cancelledText') })); if (guidance.childNodes.length) card.appendChild(guidance); }
  card.appendChild(renderTimeline(request)); const actions = el('footer', { className: 'request-actions' }); if (manager && [REQUEST_STATUS.SUBMITTED, REQUEST_STATUS.IN_REVIEW].includes(request.status)) { const confirm = button(t('manager.confirm'), { className: 'primary' }); confirm.addEventListener('click', () => managerAction(request.id, 'confirm')); const change = button(t('manager.change')); change.addEventListener('click', () => reasonAction(request, 'change')); const reject = button(t('manager.reject'), { className: 'danger' }); reject.addEventListener('click', () => reasonAction(request, 'reject')); actions.append(confirm, change, reject); }
  if (!manager) { const details = button(t('requests.details')); details.addEventListener('click', () => openRequestDetails(request)); actions.appendChild(details); if (request.status === REQUEST_STATUS.CONFIRMED) { const guest = button(t('requests.guest')); guest.addEventListener('click', () => openGuestInfo(request)); const pdf = button(t('requests.pdf')); pdf.addEventListener('click', () => printWelcome(request)); actions.append(guest, pdf); } if (request.status === REQUEST_STATUS.CHANGE_REQUESTED) { const editChange = button(t('requests.editChange'), { className: 'primary' }); editChange.addEventListener('click', () => editChangeRequest(request)); actions.appendChild(editChange); } if ([REQUEST_STATUS.SUBMITTED, REQUEST_STATUS.CONFIRMED, REQUEST_STATUS.CHANGE_REQUESTED].includes(request.status)) { const cancel = button(t('requests.cancel'), { className: 'danger' }); cancel.addEventListener('click', () => confirmCancel(request)); actions.appendChild(cancel); } if ([REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED].includes(request.status)) { const repeat = button(request.status === REQUEST_STATUS.REJECTED ? t('requests.repeatRejected') : t('requests.repeat'), { className: 'primary' }); repeat.addEventListener('click', () => repeatRequest(request)); actions.appendChild(repeat); } }
  if (actions.childNodes.length) card.appendChild(actions); return card;
}

function renderTimeline(request) { const section = el('section', { className: 'request-timeline' }, [el('h4', { text: t('timeline.title') })]); const list = el('ol'); const events = requestTimeline(request); events.forEach((event) => list.append(el('li', {}, [el('strong', { text: t(`timeline.${event.status}`) }), el('small', { text: formatDateTime(event.at) }), event.note ? el('p', { text: event.note }) : null]))); if (![REQUEST_STATUS.CONFIRMED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED, REQUEST_STATUS.CHANGE_REQUESTED].includes(request.status)) list.append(el('li', { attrs: { 'aria-current': 'step' } }, [el('strong', { text: t('timeline.pending') }), el('small', { text: t('timeline.open') })])); section.appendChild(list); return section; }
function renderRequestCalendar(list) { const reference = new Date(`${state.calendarReference}T12:00:00`); const year = reference.getFullYear(); const month = reference.getMonth(); const first = new Date(year, month, 1, 12); const offset = (first.getDay() + 6) % 7; const gridStart = new Date(year, month, 1 - offset, 12); const wrapper = el('section', { className: 'calendar-shell' }); const header = el('header', { className: 'calendar-header' }); const prev = button('‹', { attrs: { 'aria-label': t('common.back') } }); prev.addEventListener('click', () => { const d = new Date(year, month - 1, 1, 12); state.calendarReference = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`; renderRequestsViewOnly(); }); const next = button('›', { attrs: { 'aria-label': t('common.next') } }); next.addEventListener('click', () => { const d = new Date(year, month + 1, 1, 12); state.calendarReference = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`; renderRequestsViewOnly(); }); header.append(prev, el('h3', { text: new Intl.DateTimeFormat(language() === 'en' ? 'en-GB' : 'de-DE', { month: 'long', year: 'numeric' }).format(reference) }), next); wrapper.appendChild(header); const table = el('table', { className: 'calendar-table' }); const thead = el('thead'); const hr = el('tr'); const baseMonday = new Date(2026, 0, 5, 12); for (let i = 0; i < 7; i += 1) { const d = new Date(baseMonday); d.setDate(baseMonday.getDate() + i); hr.append(el('th', { text: new Intl.DateTimeFormat(language() === 'en' ? 'en-GB' : 'de-DE', { weekday: 'short' }).format(d) })); } thead.appendChild(hr); table.appendChild(thead); const tbody = el('tbody'); for (let week = 0; week < 6; week += 1) { const row = el('tr'); for (let day = 0; day < 7; day += 1) { const d = new Date(gridStart); d.setDate(gridStart.getDate() + week * 7 + day); const iso = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; const cell = el('td', { className: d.getMonth() === month ? '' : 'other-month' }, [el('span', { className: 'calendar-day', text: String(d.getDate()) })]); list.filter((request) => request.date === iso).forEach((request) => { const event = button(`${request.start} · ${request.title}`, { className: 'calendar-event' }); event.addEventListener('click', () => openRequestDetails(request)); cell.appendChild(event); }); row.appendChild(cell); } tbody.appendChild(row); } table.appendChild(tbody); wrapper.appendChild(table); return wrapper; }

function openRequestDetails(request) { const room = catalog.rooms.find((entry) => entry.id === request.roomId); const content = el('section', { className: 'details-grid' }); const add = (label, value) => content.append(el('section', { className: 'detail-card' }, [el('h3', { text: label }), el('p', { text: value || '—' })])); add(t('review.schedule'), `${formatDate(request.date)} · ${request.start}–${request.end}`); add(t('review.room'), localized(room?.name || request.roomId || '')); add(t('schedule.total'), String(request.participants || totalParticipants(request))); add(t('review.services'), request.serviceIds?.length ? catalog.services.filter((service) => request.serviceIds.includes(service.id)).map((service) => localized(service.name)).join(' · ') : t('common.none')); add(t('review.special'), request.specialRequirements || t('common.none')); add(t('catering.dietary'), request.dietaryRequirements || t('catering.noDietary')); add(t('cost.total'), formatMoney(request.estimatedCost || 0)); if (request.changeReason) add(t('requests.changeReason'), request.changeReason); if (request.rejectionReason) add(t('requests.rejectionReason'), request.rejectionReason); const close = button(t('common.close'), { className: 'primary' }); const dialog = openDialog({ title: `${request.id} · ${request.title}`, content, actions: [close], labelledById: 'requestDetailsTitle' }); close.addEventListener('click', () => dialog.close()); }
function confirmCancel(request) { const content = el('p', { text: `${request.title} · ${formatDate(request.date)} · ${request.start}–${request.end}. ${t('dialog.cancelText')}` }); const close = button(t('common.back')); const confirm = button(t('dialog.cancelConfirm'), { className: 'danger' }); const dialog = openDialog({ title: t('dialog.cancelTitle'), content, actions: [close, confirm], labelledById: 'cancelTitle' }); close.addEventListener('click', () => dialog.close()); confirm.addEventListener('click', () => { const now = new Date().toISOString(); requestRepository.update((list) => list.map((entry) => entry.id === request.id ? appendHistory({ ...entry, status: REQUEST_STATUS.CANCELLED, calendarStatus: CALENDAR_STATUS.RELEASED, cancelledAt: now, updatedAt: now }, REQUEST_STATUS.CANCELLED, '', now) : entry)); notify('cancelled', request, { title: request.title }); dialog.close(); renderRequestsViewOnly(); }); }
function repeatRequest(request) { const copied = cloneForRepeat(request); resetRequestState(); Object.assign(state.form, copied); state.roomId = copied.roomId; state.serviceIds = copied.serviceIds; state.packageSelection = copied.packageSelection; state.quantities = copied.quantities; state.allocations = copied.allocations; const hasItems = Object.values(copied.quantities).some((value) => Number(value) > 0); state.cateringMode = copied.packageSelection && hasItems ? 'BOTH' : copied.packageSelection ? 'PACKAGE' : hasItems ? 'ITEMS' : 'NONE'; state.view = 'employee'; state.step = 1; showToast(copied.copiedFromPast ? t('draft.copiedPast') : t('draft.copied')); render(); }
function editChangeRequest(request) { resetRequestState(); state.editingRequestId = request.id; Object.assign(state.form, { title: request.title || '', location: request.location || '', date: request.date || '', start: request.start || '', end: request.end || '', internalParticipants: request.internalParticipants ?? '', externalParticipants: request.externalParticipants ?? '', specialRequirements: request.specialRequirements || '', dietaryRequirements: request.dietaryRequirements || '', cateringParticipants: request.cateringParticipants || '' }); state.roomId = request.roomId || null; state.serviceIds = [...(request.serviceIds || [])]; state.packageSelection = request.packageSelection ? { packageId: request.packageSelection.packageId, tier: request.packageSelection.tier } : null; state.quantities = structuredClone(request.quantities || {}); state.allocations = structuredClone(request.allocations?.length ? request.allocations : [{ costCenter: '', percent: 100 }]); const hasItems = Object.values(state.quantities).some((value) => Number(value) > 0); state.cateringMode = state.packageSelection && hasItems ? 'BOTH' : state.packageSelection ? 'PACKAGE' : hasItems ? 'ITEMS' : 'NONE'; state.view = 'employee'; state.step = 1; render(); }

function openGuestInfo(request) { const room = catalog.rooms.find((entry) => entry.id === request.roomId); const site = siteInfo[request.location] || {}; const content = el('section'); if (site.mockData) content.appendChild(el('aside', { className: 'info-box', attrs: { role: 'note' }, text: t('guest.demo') })); const grid = el('section', { className: 'details-grid' }); const card = (title, values) => { const section = el('article', { className: 'detail-card' }, [el('h3', { text: title })]); values.filter(Boolean).forEach((value) => section.appendChild(el('p', { text: localized(value) }))); return section; }; grid.append(card(t('guest.scheduleRoom'), [formatDate(request.date, { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' }), `${request.start}–${request.end}`, localized(room?.name || request.roomId || '')]), card(t('guest.address'), [site.address || t('guest.askOrganizer'), site.publicTransport, site.carArrival]), card(t('guest.parking'), [site.parking, site.reception, site.building, site.visitorNotes]), card(t('guest.contact'), [site.contact || t('guest.contactDefault'), site.contactDetails, site.accessibility])); content.appendChild(grid); const route = safeHttpsUrl(site.mapsUrl); if (route) content.append(el('p', {}, el('a', { href: route, target: '_blank', rel: 'noopener noreferrer', text: t('guest.route') }))); if (site.wifiName && site.wifiPassword) content.append(el('section', { className: 'wifi-box' }, [el('h3', { text: t('guest.wifi') }), el('p', { text: `${t('guest.network')}: ${site.wifiName}` }), el('p', { text: `${t('guest.code')}: ${site.wifiPassword}` }), el('p', { text: localized(site.wifiInstructions) })])); const close = button(t('common.close')); const print = button(t('guest.print'), { className: 'primary' }); const dialog = openDialog({ title: t('guest.welcome', { title: request.title }), description: t('guest.subtitle'), content, actions: [close, print], labelledById: 'guestTitle' }); close.addEventListener('click', () => dialog.close()); print.addEventListener('click', () => printWelcome(request)); }
function printWelcome(request) { const room = catalog.rooms.find((entry) => entry.id === request.roomId); const site = siteInfo[request.location] || {}; const printWindow = window.open('', '_blank', 'noopener,noreferrer'); if (!printWindow) return; const doc = printWindow.document; doc.documentElement.lang = language(); doc.title = `${t('requests.pdf')} · ${request.id}`; const style = doc.createElement('style'); style.textContent = 'body{font-family:Arial,sans-serif;margin:40px;color:#111}header{border-bottom:6px solid #7A1F3D;padding-bottom:18px;margin-bottom:24px}h1{font-size:32px}section{margin:22px 0}dl{display:grid;grid-template-columns:180px 1fr;gap:8px}dt{font-weight:700}@media print{button{display:none}}'; doc.head.appendChild(style); const body = doc.body; body.append(el('header', {}, [el('p', { text: t('app.title') }), el('h1', { text: t('guest.welcome', { title: request.title }) }), el('p', { text: t('guest.subtitle') })])); const dl = el('dl'); [[t('schedule.date'), formatDate(request.date, { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })], [t('schedule.start'), `${request.start}–${request.end}`], [t('review.room'), localized(room?.name || request.roomId || '')], [t('schedule.location'), request.location], [t('guest.address'), site.address || t('guest.askOrganizer')], [t('guest.contact'), site.contact || t('guest.contactDefault')], [t('guest.network'), site.wifiName || '—'], [t('guest.code'), site.wifiPassword || '—']].forEach(([term, value]) => dl.append(el('dt', { text: term }), el('dd', { text: value }))); body.appendChild(dl); const printButton = el('button', { type: 'button', text: t('guest.print') }); printButton.addEventListener('click', () => printWindow.print()); body.appendChild(printButton); printWindow.focus(); }

function renderManager() { setPageHeading(t('manager.heading'), t('manager.adminDesc')); const tabs = el('nav', { className: 'manager-tabs', attrs: { 'aria-label': t('manager.heading') } }); [['BOOKINGS', 'manager.bookings'], ['ROOM_PLAN', 'manager.roomPlan'], ['REPORTS', 'manager.reports'], ['ADMIN', 'manager.admin']].forEach(([value, key]) => { const control = button(t(key), { attrs: { 'aria-pressed': String(state.managerTab === value) } }); control.addEventListener('click', () => { state.managerTab = value; renderManagerViewOnly(); }); tabs.appendChild(control); }); appRoot.appendChild(tabs); if (state.managerTab === 'BOOKINGS') appRoot.appendChild(renderManagerBookings()); if (state.managerTab === 'ROOM_PLAN') appRoot.appendChild(renderRoomPlan()); if (state.managerTab === 'REPORTS') appRoot.appendChild(renderReports()); if (state.managerTab === 'ADMIN') appRoot.appendChild(renderAdmin()); }
function renderManagerViewOnly() { clear(appRoot); renderManager(); }
function renderManagerBookings() { const section = el('section', { className: 'card' }); const filters = el('form', { className: 'manager-filters' }); const search = inputControl('search', state.managerSearch, { placeholder: t('manager.search') }); search.setAttribute('aria-label', t('manager.search')); search.addEventListener('input', () => { state.managerSearch = search.value; renderManagerViewOnly(); }); const status = el('select'); status.append(el('option', { value: 'ALL', text: t('manager.allStatuses') })); Object.values(REQUEST_STATUS).forEach((value) => status.append(el('option', { value, text: localizedStatus(value) }))); status.value = state.managerStatus; status.addEventListener('change', () => { state.managerStatus = status.value; renderManagerViewOnly(); }); const location = el('select'); location.append(el('option', { value: 'ALL', text: t('manager.allLocations') })); [...new Set(activeRooms().map((room) => room.location))].forEach((value) => location.append(el('option', { value, text: value }))); location.value = state.managerLocation; location.addEventListener('change', () => { state.managerLocation = location.value; renderManagerViewOnly(); }); filters.append(search, status, location); section.appendChild(filters); const list = requests().filter((request) => (state.managerStatus === 'ALL' || request.status === state.managerStatus) && (state.managerLocation === 'ALL' || request.location === state.managerLocation) && (!state.managerSearch || `${request.id} ${request.title}`.toLowerCase().includes(state.managerSearch.toLowerCase()))); if (!list.length) section.appendChild(el('p', { className: 'info-box', text: t('manager.noRequests') })); else list.forEach((request) => section.appendChild(requestCard(request, true))); return section; }
function managerAction(requestId, action) { const now = new Date().toISOString(); let changed = null; requestRepository.update((list) => list.map((request) => { if (request.id !== requestId) return request; if (action === 'confirm') { changed = appendHistory({ ...request, status: REQUEST_STATUS.CONFIRMED, calendarStatus: CALENDAR_STATUS.BUSY, confirmedAt: now, updatedAt: now }, REQUEST_STATUS.CONFIRMED, '', now); return changed; } return request; })); if (changed) notify('confirmed', changed, { title: changed.title }); renderManagerViewOnly(); }
function reasonAction(request, action) { const textarea = el('textarea', { placeholder: t('dialog.reasonPlaceholder'), attrs: { 'aria-label': t('dialog.reason') } }); const close = button(t('common.cancel')); const submit = button(action === 'reject' ? t('manager.reject') : t('manager.change'), { className: action === 'reject' ? 'danger' : 'primary' }); const content = field({ id: 'reasonText', label: t('dialog.reason'), control: textarea, required: true }); const dialog = openDialog({ title: action === 'reject' ? t('dialog.rejectTitle') : t('dialog.changeTitle'), content, actions: [close, submit], labelledById: 'reasonTitle' }); close.addEventListener('click', () => dialog.close()); submit.addEventListener('click', () => { const reason = textarea.value.trim(); if (!reason) { textarea.setAttribute('aria-invalid', 'true'); announce(t('dialog.reasonRequired'), { assertive: true }); textarea.focus(); return; } const now = new Date().toISOString(); let changed = null; requestRepository.update((list) => list.map((entry) => { if (entry.id !== request.id) return entry; const status = action === 'reject' ? REQUEST_STATUS.REJECTED : REQUEST_STATUS.CHANGE_REQUESTED; const next = { ...entry, status, calendarStatus: action === 'reject' ? CALENDAR_STATUS.RELEASED : CALENDAR_STATUS.PROVISIONAL, updatedAt: now, ...(action === 'reject' ? { rejectionReason: reason, rejectedAt: now } : { changeReason: reason, changeRequestedAt: now }) }; changed = appendHistory(next, status, reason, now); return changed; })); if (changed) notify(action === 'reject' ? 'rejected' : 'change', changed, { title: changed.title }); dialog.close(); renderManagerViewOnly(); }); }
function renderRoomPlan() { const section = el('section', { className: 'card' }, [sectionHeading(t('manager.roomPlan'), t('manager.roomPlanDesc'))]); const date = inputControl('date', state.roomPlanDate); date.addEventListener('change', () => { state.roomPlanDate = date.value; renderManagerViewOnly(); }); section.appendChild(field({ id: 'roomPlanDate', label: t('manager.referenceDate'), control: date })); const table = el('table', { className: 'data-table' }); const head = el('thead', {}, el('tr', {}, [el('th', { text: t('review.room') }), el('th', { text: t('schedule.start') }), el('th', { text: t('schedule.title') }), el('th', { text: t('manager.status') })])); const body = el('tbody'); activeRooms().forEach((room) => { const bookings = requests().filter((request) => request.roomId === room.id && request.date === state.roomPlanDate && ![REQUEST_STATUS.REJECTED, REQUEST_STATUS.CANCELLED].includes(request.status)); if (!bookings.length) body.append(el('tr', {}, [el('td', { text: localized(room.name) }), el('td', { text: '—' }), el('td', { text: '—' }), el('td', { text: t('room.available') })])); else bookings.forEach((request) => body.append(el('tr', {}, [el('td', { text: localized(room.name) }), el('td', { text: `${request.start}–${request.end}` }), el('td', { text: request.title }), el('td', { text: localizedStatus(request.status) })]))); }); table.append(head, body); section.appendChild(table); return section; }
function renderReports() { const section = el('section', { className: 'card' }, [sectionHeading(t('manager.reports'), t('manager.reportDesc'))]); const all = requests(); const confirmed = all.filter((request) => request.status === REQUEST_STATUS.CONFIRMED); const open = all.filter((request) => [REQUEST_STATUS.SUBMITTED, REQUEST_STATUS.IN_REVIEW, REQUEST_STATUS.CHANGE_REQUESTED].includes(request.status)); const catering = confirmed.filter((request) => request.packageSelection || Object.values(request.quantities || {}).some((value) => Number(value) > 0)); const participants = confirmed.reduce((sum, request) => sum + Number(request.participants || totalParticipants(request)), 0); const grid = el('section', { className: 'dashboard-grid' }); grid.append(kpi(t('manager.confirmedBookings'), confirmed.length), kpi(t('manager.openRequests'), open.length), kpi(t('manager.cateringBookings'), catering.length), kpi(t('manager.totalParticipants'), participants)); section.appendChild(grid); return section; }
function setLocalized(current, value) { const base = current && typeof current === 'object' ? { ...current } : { de: String(current || ''), en: String(current || '') }; base[language()] = value; return base; }
function renderAdmin() { const section = el('section', { className: 'card' }, [sectionHeading(t('manager.admin'), t('manager.adminDesc'))]); const tabs = el('nav', { className: 'segmented' }); [['ROOMS', 'manager.rooms'], ['SERVICES', 'manager.services'], ['CATERING', 'manager.catering'], ['SITES', 'manager.sites']].forEach(([value, key]) => { const control = button(t(key), { attrs: { 'aria-pressed': String(state.adminTab === value) } }); control.addEventListener('click', () => { state.adminTab = value; renderManagerViewOnly(); }); tabs.appendChild(control); }); section.appendChild(tabs); const editor = el('section', { className: 'admin-editor' }); if (state.adminTab === 'ROOMS') renderRoomAdmin(editor); if (state.adminTab === 'SERVICES') renderServiceAdmin(editor); if (state.adminTab === 'CATERING') renderCateringAdmin(editor); if (state.adminTab === 'SITES') renderSiteAdmin(editor); section.appendChild(editor); return section; }
function renderRoomAdmin(root) { catalog.rooms.forEach((room) => { const card = el('article', { className: 'admin-card' }); const name = inputControl('text', localized(room.name)); const capacity = inputControl('number', room.capacity, { min: 1 }); const price = inputControl('number', room.rate, { min: 0, step: 0.01 }); const equipment = inputControl('text', localized(room.equipment)); const active = inputControl('checkbox', ''); active.checked = room.active !== false; card.append(field({ id: `room-name-${room.id}`, label: t('manager.name'), control: name }), field({ id: `room-cap-${room.id}`, label: t('manager.capacity'), control: capacity }), field({ id: `room-price-${room.id}`, label: t('manager.price'), control: price }), field({ id: `room-equip-${room.id}`, label: t('manager.equipment'), control: equipment }), field({ id: `room-active-${room.id}`, label: t('manager.active'), control: active })); const save = button(t('common.save'), { className: 'primary' }); save.addEventListener('click', () => { room.name = setLocalized(room.name, name.value.trim()); room.capacity = Math.max(1, Number(capacity.value || 1)); room.rate = Math.max(0, Number(price.value || 0)); room.equipment = setLocalized(room.equipment, equipment.value.trim()); room.active = active.checked; persistCatalog(); }); card.appendChild(save); root.appendChild(card); }); const add = button(t('manager.addRoom')); add.addEventListener('click', () => { catalog.rooms.push({ id: `ROOM-${Date.now()}`, location: 'Berlin', name: { de: '', en: '' }, capacity: 8, equipment: { de: '', en: '' }, floor: { de: '', en: '' }, rate: 0, active: true }); persistCatalog(); renderManagerViewOnly(); }); root.appendChild(add); }
function renderServiceAdmin(root) { catalog.services.forEach((service) => { const card = el('article', { className: 'admin-card' }); const name = inputControl('text', localized(service.name)); const description = inputControl('text', localized(service.description)); const price = inputControl('number', service.price, { min: 0, step: 0.01 }); const active = inputControl('checkbox', ''); active.checked = service.active !== false; card.append(field({ id: `service-name-${service.id}`, label: t('manager.name'), control: name }), field({ id: `service-desc-${service.id}`, label: t('manager.description'), control: description }), field({ id: `service-price-${service.id}`, label: t('manager.price'), control: price }), field({ id: `service-active-${service.id}`, label: t('manager.active'), control: active })); const save = button(t('common.save'), { className: 'primary' }); save.addEventListener('click', () => { service.name = setLocalized(service.name, name.value.trim()); service.description = setLocalized(service.description, description.value.trim()); service.price = Math.max(0, Number(price.value || 0)); service.active = active.checked; persistCatalog(); }); card.appendChild(save); root.appendChild(card); }); const add = button(t('manager.addService')); add.addEventListener('click', () => { catalog.services.push({ id: `SERVICE-${Date.now()}`, name: { de: '', en: '' }, description: { de: '', en: '' }, price: 0, active: true }); persistCatalog(); renderManagerViewOnly(); }); root.appendChild(add); }
function renderCateringAdmin(root) { catalog.cateringItems.forEach((item) => { const card = el('article', { className: 'admin-card' }); const name = inputControl('text', localized(item.name)); const unit = inputControl('text', localized(item.unit)); const price = inputControl('number', item.price, { min: 0, step: 0.01 }); const active = inputControl('checkbox', ''); active.checked = item.active !== false; card.append(field({ id: `item-name-${item.id}`, label: t('manager.name'), control: name }), field({ id: `item-unit-${item.id}`, label: t('manager.unit'), control: unit }), field({ id: `item-price-${item.id}`, label: t('manager.price'), control: price }), field({ id: `item-active-${item.id}`, label: t('manager.active'), control: active })); const save = button(t('common.save'), { className: 'primary' }); save.addEventListener('click', () => { item.name = setLocalized(item.name, name.value.trim()); item.unit = setLocalized(item.unit, unit.value.trim()); item.price = Math.max(0, Number(price.value || 0)); item.active = active.checked; persistCatalog(); }); card.appendChild(save); root.appendChild(card); }); const add = button(t('manager.addItem')); add.addEventListener('click', () => { catalog.cateringItems.push({ id: `ITEM-${Date.now()}`, name: { de: '', en: '' }, unit: { de: '', en: '' }, price: 0, active: true }); persistCatalog(); renderManagerViewOnly(); }); root.appendChild(add); }
function renderSiteAdmin(root) { Object.keys(siteInfo).sort().forEach((location) => { const site = siteInfo[location]; const card = el('article', { className: 'admin-card' }, [el('h3', { text: location })]); const fields = [['address', 'manager.address'], ['publicTransport', 'manager.publicTransport'], ['parking', 'manager.parking'], ['reception', 'manager.reception'], ['accessibility', 'manager.accessibility'], ['contact', 'manager.contact']]; const controls = {}; fields.forEach(([key, label]) => { const control = inputControl('text', localized(site[key])); controls[key] = control; card.appendChild(field({ id: `site-${location}-${key}`, label: t(label), control })); }); const save = button(t('common.save'), { className: 'primary' }); save.addEventListener('click', () => { fields.forEach(([key]) => { site[key] = key === 'address' || key === 'contact' ? controls[key].value.trim() : setLocalized(site[key], controls[key].value.trim()); }); writeJson(KEYS.siteInfo, siteInfo); showToast(t('manager.saved')); }); card.appendChild(save); root.appendChild(card); }); }
function persistCatalog() { writeJson(KEYS.catalog, catalog); showToast(t('manager.saved')); renderNavigation(); }

function openProfile() { const content = el('section', { className: 'profile-content' }); const dl = el('dl', { className: 'details-list' }); [[t('profile.first'), profile.firstName], [t('profile.last'), profile.lastName], [t('profile.role'), isManager() ? t('profile.role.manager') : t('profile.role.employee')]].forEach(([term, value]) => dl.append(el('dt', { text: term }), el('dd', { text: value }))); content.appendChild(dl); const languageSelect = el('select'); [['de', 'Deutsch'], ['en', 'English']].forEach(([value, label]) => languageSelect.append(el('option', { value, text: label }))); languageSelect.value = language(); content.appendChild(field({ id: 'profileLanguage', label: t('profile.language'), control: languageSelect, hint: t('profile.languageNote') })); const roleSelect = el('select'); roleSelect.append(el('option', { value: 'employee', text: t('profile.role.employee') }), el('option', { value: 'manager', text: t('profile.role.manager') })); roleSelect.value = role(); content.appendChild(field({ id: 'profileRole', label: t('profile.demo'), control: roleSelect, hint: t('profile.demoNote') })); const help = button(t('profile.help')); const logout = button(t('profile.logout'), { className: 'danger' }); const close = button(t('common.close'), { className: 'primary' }); const dialog = openDialog({ title: t('profile.title'), content, actions: [help, logout, close], labelledById: 'profileTitle' }); close.addEventListener('click', () => dialog.close()); help.addEventListener('click', () => { dialog.close(); requestAnimationFrame(openHelp); }); logout.addEventListener('click', () => showToast(t('profile.logoutMvp'))); languageSelect.addEventListener('change', () => { setLanguage(languageSelect.value); dialog.close(); }); roleSelect.addEventListener('change', () => { writeString(KEYS.role, roleSelect.value); dialog.close(); if (!isManager() && state.view === 'manager') state.view = 'welcome'; render(); }); }
function openHelp() { const content = el('section', { className: 'help-grid' }); [[t('help.noRoom'), t('help.noRoomText')], [t('help.cost'), t('help.costText')], [t('help.binding'), t('help.bindingText')], [t('help.special'), t('help.specialText')]].forEach(([heading, text]) => content.append(el('article', { className: 'help-card' }, [el('h3', { text: heading }), el('p', { text })]))); const message = el('textarea', { placeholder: t('help.message') }); content.appendChild(field({ id: 'helpMessage', label: t('help.contact'), control: message })); const close = button(t('common.close')); const send = button(t('help.send'), { className: 'primary' }); const dialog = openDialog({ title: t('help.title'), description: t('help.subtitle'), content, actions: [close, send], labelledById: 'helpTitle' }); close.addEventListener('click', () => dialog.close()); send.addEventListener('click', () => { if (!message.value.trim()) { message.setAttribute('aria-invalid', 'true'); message.focus(); return; } dialog.close(); showToast(t('help.sent')); }); }

function render() { clear(appRoot); renderNavigation(); if (state.view === 'welcome') renderWelcome(); else if (state.view === 'employee') renderRequest(); else if (state.view === 'requests') renderRequests(); else if (state.view === 'manager') renderManager(); document.documentElement.dataset.appBuild = APP_BUILD; }
window.addEventListener('conference-language-changed', () => render());
window.addEventListener('storage', (event) => { if ([KEYS.requests, KEYS.catalog, KEYS.siteInfo, KEYS.role].includes(event.key)) { catalog = loadCatalog(); siteInfo = loadSiteInfo(); render(); } });
render();
